eclipse-jdtls/eclipse.jdt.ls

- server/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/JavaLanguageServerPlugin.java
- server/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/StatusFactory.java
- server/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/handlers/InitHandler.java
- server/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/managers/AbstractProjectImporter.java
- server/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/managers/EclipseProjectImporter.java
- server/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/managers/IProjectImporter.java
- server/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/managers/MavenProjectImporter.java
- server/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/managers/ProjectsManager.java
> Add basic Eclipse .project support #37

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/ProjectUtils.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/managers/ProjectsManager.java
- org.jboss.tools.vscode.tests/META-INF/MANIFEST.MF
- org.jboss.tools.vscode.tests/projects/eclipse/hello/.classpath
- org.jboss.tools.vscode.tests/projects/eclipse/hello/.project
- org.jboss.tools.vscode.tests/projects/eclipse/hello/.settings/org.eclipse.jdt.core.prefs
- org.jboss.tools.vscode.tests/projects/eclipse/hello/src/java/Foo.java
- org.jboss.tools.vscode.tests/projects/eclipse/multi/bar/.classpath
- org.jboss.tools.vscode.tests/projects/eclipse/multi/bar/.project
- org.jboss.tools.vscode.tests/projects/eclipse/multi/bar/.settings/org.eclipse.jdt.core.prefs
- org.jboss.tools.vscode.tests/projects/eclipse/multi/bar/src/bar/Bar.java
- org.jboss.tools.vscode.tests/projects/eclipse/multi/foo/.classpath
- org.jboss.tools.vscode.tests/projects/eclipse/multi/foo/.project
- org.jboss.tools.vscode.tests/projects/eclipse/multi/foo/.settings/org.eclipse.jdt.core.prefs
- org.jboss.tools.vscode.tests/projects/eclipse/multi/foo/src/foo/Foo.java
- org.jboss.tools.vscode.tests/projects/maven/salut/pom.xml
- org.jboss.tools.vscode.tests/projects/maven/salut/src/main/java/java/Foo.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/managers/AbstractProjectsManagerBasedTest.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/managers/EclipseProjectImporterTest.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/managers/MavenProjectImporterTest.java
> Add more tests

- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/JobHelpers.java
Signed-off-by: Olivier Thomann <Olivier_Thomann@ca.ibm.com>
This is a pull request for issur #103. Would be good to get it merge in master so I can resume the docker image build. Thanks
> [lsp] increase timeout for gradle project setup (#103)

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/ActionableNotification.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/JavaClientConnection.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/JavaLanguageServerPlugin.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/DocumentLifeCycleHandler.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/InitHandler.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/JDTLanguageServer.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/MapFlattener.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/preferences/PreferenceManager.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/preferences/Preferences.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/AbstractWorkspaceTest.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/handlers/CompletionHandlerTest.java
Required to fix https://github.com/redhat-developer/vscode-java/issues/107
> Send message.incompleteClasspathDetected according to preferences

- org.jboss.tools.vscode.java/META-INF/MANIFEST.MF
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/JavaLanguageServerPlugin.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/JDTLanguageServer.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/managers/GradleBuildSupport.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/managers/IBuildSupport.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/managers/MavenBuildSupport.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/managers/ProjectsManager.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/preferences/Preferences.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/managers/AbstractProjectsManagerBasedTest.java
Required to fix https://github.com/redhat-developer/vscode-java/issues/122
> Enable Java configuration auto-update

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/HoverInfoProvider.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/hover/JavaElementLabelComposer.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/hover/JavaElementLabels.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/javadoc/html/SingleCharReader.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/javadoc/html/SubstitutionTextReader.java
Fix for #100.
Change-Id: Ib5b7fb2d452327c0ef7e7064533e58c45666d238
Signed-off-by: oliviert <Olivier_Thomann@ca.ibm.com>
> Fix for #100

- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/handlers/HoverHandlerTest.java
This is a regression test for #100.
Change-Id: I5d2eb92e0be00c945195040fc639ae74b42ae3c3
Signed-off-by: oliviert <Olivier_Thomann@ca.ibm.com>
> Regression test for #100

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/managers/GradleBuildSupport.java
- target-platform/jdt_ls.target
> Update to BuildShip 2.x and other dependencies in the TP. Fixes #127 and #131

- target-platform/jdt_ls.target
> Regular TP update

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/HoverInfoProvider.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/contentassist/CompletionProposalReplacementProvider.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/contentassist/CompletionProposalRequestor.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/contentassist/TypeProposalUtils.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/CompletionHandler.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/CompletionResolveHandler.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/CompletionResponse.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/CompletionResponses.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/DocumentLifeCycleHandler.java
- org.jboss.tools.vscode.tests/META-INF/MANIFEST.MF
- org.jboss.tools.vscode.tests/pom.xml
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/Lsp4jAssertions.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/handlers/AbstractCompletionBasedTest.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/handlers/CompletionHandlerTest.java
Requires adding tests before applying.
> Lazy-load completion proposal replacements. Fixes #123

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/MapFlattener.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/handlers/MapFlattenerTest.java
> Add new unit tests for MapFlattener

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/CompletionHandler.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/HoverHandler.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/JDTLanguageServer.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/NavigateToDefinitionHandler.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/handlers/CompletionHandlerTest.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/handlers/HoverHandlerTest.java
> Adjust to latest lsp4j changes. Fixes #142

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/JavaLanguageServerPlugin.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/InitHandler.java
> Log server version

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/InitHandler.java
- target-platform/jdt_ls.target
> Fix backward compat with vscode     Back to M builds. Fixes #145

- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/CodeLensHandler.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/JDTLanguageServer.java
- org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/preferences/Preferences.java
- org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/handlers/CodeLensHandlerTest.java
Also fixes https://github.com/redhat-developer/vscode-java/issues/148
> Add preference to disable codelenses. Fix #147

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java
Implements workspace/applyEdit and window/showMessageRequest
on the client connection.
> Implement applyEdit

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
> Trace plugin stop() invocation

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
> Refresh saved java files to update compilation errors in the workspace. Fixes #187

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
> Expose Maven user settings preference. Fixes #184

- org.eclipse.jdt.ls.tests/pom.xml
removes unnecessary p2 repository reference
> remove repository reference

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
Fixes redhat-developer/vscode-java#179
> Include initial build progress monitor to compute overall readiness status

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
Added a timeout of 500ms to javadoc resolution, so completionItem resolve regardless of javadoc status.
It should be noted, however, that 500ms might still be too long for client-side, which could still experience issues like
https://github.com/redhat-developer/vscode-java/issues/176
> Slow javadoc resolution should not prevent completionItem resolution

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JsonRpcHelpers.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
eclipse.jdt.ls doesn't calculate locations properly. The vscode throws an exception and shows nothing.
https://github.com/redhat-developer/vscode-java/issues/206
> Class outline doesn't work for .class files not in the workspace

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
> Enable camel-case type search. Fixes #219

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SortTextHelper.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/contentassist/SortTextHelperTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/216
> Revisit content proposal sorttext/relevance conversion

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/214
> Don't send hover with null content

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/187
> Add filterText to types autocompletion

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactoryTest.java
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/218
> Connection over stdin/stdout breaks sometimes

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/175
> Add default insertText to textDocument/completion responses

- org.eclipse.jdt.ls.core/.classpath
- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/build.properties
- org.eclipse.jdt.ls.product/languageServer.product
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/236
> Add lsp4j to the target platform

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Bar.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Foo.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/226
> Return inherited javadoc on hover

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ClassfileContentHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ClassfileContentHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/222
> Can't navigate from disassembled source of a class file

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTest.java
> Ignore non-java file when faking ICompilationUnits

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetectorTest.java
> Test failures on Windows

- README.md
There are a few miscellaneous hiccups in the `README.md` file that could be fixed.
> Fix grammar and spelling errors in the README.md

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ClassfileContentHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentHighlightHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ClassfileContentHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
> Handle CompletableFutures more consistently across the board

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTest.java
> Ensure standalone files are always linked

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandler.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
> Add signature support for HoverHandler.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
> Fix NPE when hovering over package

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess.java
- org.eclipse.jdt.ls.tests/projects/maven/salut2/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/salut2/src/main/java/foo/Bar.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/SimpleLogListener.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/248
> Ignore missing HTML Javadoc errors on hover

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
> Dynamically (un)register textDocument/codeLens capability

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetector.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/maven/multi/project1/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/multi/project2/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
See https://github.com/redhat-developer/vscode-java/issues/229
Requires https://github.com/redhat-developer/vscode-java/pull/255
> Gradle error message on Maven project with Less.js node module

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/SharedASTProvider.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedVariablesQuickFixTest.java
> workaround for #300

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Foo2.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Foo3.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
Fixes #99 
Requires https://github.com/redhat-developer/vscode-java/pull/257
> CodeLens for Interfaces

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Fixes #303 
The issue happens because the Java LS changes the document's buffer asynchronously. The textDocument/codeLens command is sometimes executed before updating the document's buffer and returns incorrect results.
You can reproduce the issue by entering a space between "public" and "class" in @fbricon's screencast.
A workaround is to slow the textDocument/codeLens command down.
> CodeLens doesn't recompute properly when changing modifier

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentHighlightHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Highlight.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Highlight.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentHighlightHandlerTest.java
I've created a DocumentHighlightHandlerTest test class to perform a very simple test to ensure that DocumentHighlightHandler (#227) is returning the right stuff.
> Add a simple test for DocumentHighlightHandler

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/GetterSetterCompletionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/CodeGeneration.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/GetterSetterUtil.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/StubUtility.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeGenerationTemplate.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Add Getter and Setter support for code completion 
@fbricon @aeschli  @gorkem 
https://github.com/redhat-developer/vscode-java/issues/100
> Add Getter and Setter support in code completion.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/maven/invalid/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/132
> No way to force a recreation of classpath from gradle file

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporter.java
Fixes https://github.com/redhat-developer/vscode-java/issues/259
VSCode requires a UNC URI as file://server/path. Java/Eclipse requires such a URI as file:////server/path. 
I hope I have fixed the issue in all places in the code.
The changes are limited to Windows.
> java.lang.IllegalArgumentException: URI has an authority component

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/GetterSetterCorrectionSubProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/SelfEncapsulateFieldProposal.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
@fbricon  @gorkem  @aeschli 
Issue: 
https://github.com/redhat-developer/vscode-java/issues/263
Will add more tests and actions for other unused members in another PR. 
> Add code actions for unused private fields.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/274
> The declared package does not match the expected package

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Signed-off-by: Amiram Wingarten <amiramw@gmail.com>
> Fix NPE and support import static completion when method exists

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
Fixes https://github.com/redhat-developer/vscode-java/issues/232
> Gradle should respect system setup

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferencesTest.java
> Add null checks in ClientPreferences. Fixes #334

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java
Signed-off-by: Amiram Wingarten <amiramw@gmail.com>
> method proposal - remove irrelevant kinds and avoid possible null pointer

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/288
> <<MISSING COMMAND>> when calling code actions for unused private field

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.tests/projects/gradle/simple-gradle/.project
This is a similar fix used in #303
Fixes #340
> Join on document lifecycle jobs before resolving code lenses

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java
- org.eclipse.jdt.ls.tests/projects/maven/salut/src/main/java/org/sample/Bar.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/294
> Return Types when calling document/documentSymbol

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/AnonymousTypeCompletionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Code assist for Anonymous class creation is broken

- org.eclipse.jdt.ls.core/plugin.xml
- org.eclipse.jdt.ls.core/schema/org.eclipse.jdt.ls.core.delegateCommandHandler.exsd
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/IDelegateCommandHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceExecuteCommandHandler.java
- org.eclipse.jdt.ls.tests/plugin.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/TestDelegateCommandHandlerFactory.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceExecuteCommandHandlerTest.java
Separate PR for participant extension point to make change clear.
> Add participant extension point with workspace/executeCommand

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServer.java
> Remove logs to stdio

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/build.properties
- org.eclipse.jdt.ls.core/plugin.properties
- org.eclipse.jdt.ls.repository/.project
- org.eclipse.jdt.ls.repository/.settings/org.eclipse.core.resources.prefs
- org.eclipse.jdt.ls.repository/.settings/org.eclipse.m2e.core.prefs
- org.eclipse.jdt.ls.repository/category.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/build.properties
- org.eclipse.jdt.ls.tests/plugin.properties
- pom.xml
> Add p2 update site

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/unresolvedtype/.classpath
- org.eclipse.jdt.ls.tests/projects/eclipse/unresolvedtype/.project
- org.eclipse.jdt.ls.tests/projects/eclipse/unresolvedtype/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.jdt.ls.tests/projects/eclipse/unresolvedtype/src/internal/IFoo.java
- org.eclipse.jdt.ls.tests/projects/eclipse/unresolvedtype/src/pckg/Foo.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/333
> Incorrect hover for unresolved type

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
Fixes https://github.com/redhat-developer/vscode-java/issues/302
> Error logs show in the output file

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattener.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattenerTest.java
This will allow passing decompiler preferences to decompiler extensions. See #360 
> Refactor preferences mapping from JSON

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/StubUtility.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/CodeScopeBuilder.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/Selection.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/SelectionAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/Checks.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/base/JavaStatusContext.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/surround/ExceptionAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/surround/LocalDeclarationAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/surround/SurroundWithAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/surround/SurroundWithTryCatchAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/surround/SurroundWithTryCatchRefactoring.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/util/AbstractExceptionAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/util/CodeAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/util/CommentAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/util/RefactoringASTParser.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/util/ResourceUtil.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/util/SelectionAwareSourceRangeComputer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/util/StatementAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeTemplateContextType.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ChangeMethodSignatureProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LinkedCorrectionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/RefactoringCorrectionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeGenerationTemplate.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
@fbricon @gorkem @aeschli 
Most of the code are from jdt.ui and adopted to the JDT.LS.
> Add code action for uncaught exception.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DefaultLogFilter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ILogFilter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/LogHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/ignored-filter/.classpath
- org.eclipse.jdt.ls.tests/projects/eclipse/ignored-filter/.project
- org.eclipse.jdt.ls.tests/projects/eclipse/ignored-filter/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.jdt.ls.tests/projects/eclipse/ignored-filter/src/foo/Main.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
> Filter outgoing log messages

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTest.java
> StringIndexOutOfBoundsException in JDTUtils.getPackageName

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Add Java 9 support for Eclipse and Maven projects

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
Signed-off-by: Mickael Istria <mistria@redhat.com>
> Prevent NPE - InitializeParams.processId can be null

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ContentProviderManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/IPreferencesChangeListener.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
> Add preferences change listener

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
> Close compilation unit's buffer on save

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> Use not deprecated constructor for FormattingOptions

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
> Java Model Exception when changing class name

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
> Restore InitializeParams.rootPath support

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BundleUtils.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/BundleUtilsTest.java
Delays the bundle start to after bundle install so that
all the dependencies for a bundle are properly installed
> Change bundle start behaviour

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/BuildWorkspaceStatus.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaProtocolExtensions.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/projects/singlefile/Single.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
This is a rebased version of PR #326
It adds a workspace refresh before the build.
> Add command to build workspace

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/maven/archetyped/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/archetyped/src/main/resources/META-INF/maven/archetype.xml
- org.eclipse.jdt.ls.tests/projects/maven/archetyped/src/main/resources/archetype-resources/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/archetyped/src/main/resources/archetype-resources/src/main/java/App.java
- org.eclipse.jdt.ls.tests/projects/maven/archetyped/src/main/resources/archetype-resources/src/test/java/AppTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupportTest.java
See https://github.com/redhat-developer/vscode-java/issues/331
> Ignore inner pom.xml changes

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/RunnableTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/343
I have also added references code lens for .class.
> Show implementations code lens for .class

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
> SymbolKind.Function returned for Method

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
Fix NPE issue when resolve the binding. 
See the related issue: 
https://github.com/Microsoft/vscode-java-debug/issues/150
@fbricon
> Fix NPE when resolving binding.

- pom.xml
> Skip source ref generation when not building under git repo

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/nopackage/Test.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
> NPE when resolving binding

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
- unused local variables
- unused private methods
- unused private constructor
- unused local types
- unused parameters
Fixes #448
> Enable code actions for more unused code

- .vscode/settings.json
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/ReturnTypeSubProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/MissingReturnTypeCorrectionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/MissingReturnTypeInLambdaCorrectionProposal.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ReturnTypeQuickFixTest.java
Adds the quick fixes that covers return type problems. fixes #435
> Adds return type quickfixes

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/nopackage/Test2.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
> Errors reported for java files belonging to a non default project

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
> Delay symbol and other features after the server is ready

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
> Fix NPE in CodeActionHandler.getCodeActionCommands()

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/RefactoringCoreMessages.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/refactoring.properties
> Add missing NLS messages for refactoring

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactoryTest.java
> Remove DualSocketStream support and deprecate named pipe support

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandlerTest.java
Tests for ReferencesHandler and a small cleanup. fixes #228
> ReferencesHandlerTest

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
> Refactor WorkspaceDiagnosticsHandler

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update Buildship to latest official release 2.2.0.v20171211-1404

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/383
> Failure to install Gradle distribution behind proxy

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/BundleUtilsTest.java
> BundleUtilsTest tests sometimes fail

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/eclipse/eclipsegradle/.classpath
- org.eclipse.jdt.ls.tests/projects/eclipse/eclipsegradle/.project
- org.eclipse.jdt.ls.tests/projects/eclipse/eclipsegradle/build.gradle
- org.eclipse.jdt.ls.tests/projects/eclipse/eclipsemaven/.classpath
- org.eclipse.jdt.ls.tests/projects/eclipse/eclipsemaven/.project
- org.eclipse.jdt.ls.tests/projects/eclipse/eclipsemaven/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixes #257 
Requires https://github.com/redhat-developer/vscode-java/pull/388
> Provide mechanism to disable buildship

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update TP to latest Oxygen.2 bits

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
> ProjectsManager#updateProject should return Job

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/403
> Starts never completes on an Ionic2 project

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/AbstractSerialVersionOperation.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/PotentialProgrammingProblemsFix.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/SerialVersionDefaultOperation.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/SerialVersionHashOperation.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SerialVersionSubProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/FixCorrectionProposal.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/SerialVersionQuickFixTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/401
> Add quickfix for serial version ID

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
See https://github.com/eclipse/eclipse.jdt.ls/pull/392#pullrequestreview-70112362
> Use a more specifically typed exception

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/TestJavadoc.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes #509 
The issue happens when completion is called during document/didChange.
> Documentation not included in completion resolve since PR 425

- README.md
- org.eclipse.jdt.ls.core/.classpath
- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/build.properties
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactoryTest.java
> Remove named pipes support.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/SharedASTProvider.java
> Flaky reporting of test imports in main code

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/test1/A.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/test1/B.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedMethodsQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedVariablesQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/368
Requires https://github.com/redhat-developer/vscode-java/pull/422
> Favorite imports

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/SharedASTProvider.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/426
> 'Implement missing methods' is not available anymore

- README.md
Adds ycmd, the server component of [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) and a number of other client implementations. jdt.ls support landed publicly this weekend with some additional features planned over the next few weeks.
> Add ycmd to list of clients

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core.internal.corrections
- org.eclipse.jdt.ls.core.internal.corrections.proposals
It is needed for https://github.com/eclipse/che-ls-jdt/pull/35
> Add some export packages

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.tests/projects/maven/attached-javadoc/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/attached-javadoc/src/main/java/org/sample/Bar.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/DependencyUtil.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/ImportOrganizeTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
> Return attached javadoc on hover

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/SourceRangeFactory.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/StubUtility.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/JdtASTMatcher.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/fragments/ASTFragment.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/fragments/ASTFragmentFactory.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/fragments/ASTMatchingFragmentFinder.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/fragments/AssociativeInfixExpressionFragment.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/fragments/IASTFragment.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/fragments/IExpressionFragment.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/fragments/SimpleExpressionFragment.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/fragments/SimpleFragment.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/fragments/Util.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/Checks.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/base/JavaStringStatusContext.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/base/RefactoringStatusCodes.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/CodeRefactoringUtil.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ConstantChecks.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractConstantRefactoring.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractTempRefactoring.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RefactoringAnalyzeUtil.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/util/NoCommentSourceRangeComputer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/JavadocQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractConstantTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractVariableTest.java
> Add extract variable code action.

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update m2e to 1.9 M6

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
> test failures in CompletionHandlerTest.testCompletion_javadoc

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
> Random test failure in testOrganizeImportsModuleInfo

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/CancellableProgressMonitor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/IConstants.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProgressReport.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManagerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
> Progress report support

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTest.java
> JDTUtilsTest failure

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SimilarElementsRequestor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JavaProjectHelper.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java
> Don't propose to import test classes in main code

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes https://github.com/redhat-developer/vscode-java/issues/483
> Update TP to latest, pre-M7, Photon I-Build

- README.md
log.protocol does not seem to be in use anymore.
> remove reference to unused env variable

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2MarkdownConverter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDocLocations.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaElementLinks.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java
- org.eclipse.jdt.ls.tests/projects/maven/salut/src/main/java/java/Foo.java
- org.eclipse.jdt.ls.tests/projects/maven/salut/src/main/java/java/Foo2.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2MarkdownConverterTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
Part of https://github.com/eclipse/eclipse.jdt.ls/issues/76 but has additional functionality for @see tags etc.
> Added links to location on hover in javadoc tags

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/CodeGeneration.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/StubUtility.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/ModifierRewrite.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/VariableDeclarationRewrite.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ModifierChangeCorrectionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeGenerationTemplate.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractMethodQuickFixTest.java
> Add quickfix for abstract methods

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/TestVMType.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
> Fix javadoc shenanigans. See #611 and #612

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/462
Requires https://github.com/redhat-developer/vscode-java/pull/500
> Second argument is replaced upon completing the first argument

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java
Signed-off-by: Summer Sun <victoriasqq@gmail.com>
> Add quickfix for overriding static method from an instance method

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/test1/TaskMarkerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/457
> TODO comments highlight bug

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java
Signed-off-by: Summer Sun <victoriasqq@gmail.com>
> Add quickfix for overriding final methods

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticHandlerTest.java
> Warnings are now shown with severity info, until file is saved

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
> NullPointerException in ProjectsManager.registerWatchers

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
> Update lsp4j to 0.4.0

- README.md
> Add Oni as Client

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> No completion documentation for source methods with parameters

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update TP to Photon RC1

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/StubUtility.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeTemplateContextType.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaTemplateMessages.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeGenerationTemplate.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Add server side class & interface code snippets

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Ignore unsupported CompletionItemKind during completionItem/resolve. Fixes #675

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/GetterSetterQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java
Signed-off-by: Summer Sun <victoriasqq@gmail.com>
> Add quick fix for accessing invisible references

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update TP against latest Photon build

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Return snippets as plain text if not supported by the client

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
> Return null when no definition is found

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/ParameterGuesser.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/StringMatcher.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes #688 
also see https://github.com/redhat-developer/vscode-java/pull/569
> Completion option - insert best guessed arguments

- README.md
Signed-off-by: Akos Kitta <kittaakos@typefox.io>
> Added Eclipse Theia as a consuming client.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.tests/projects/eclipse/java7/.classpath
- org.eclipse.jdt.ls.tests/projects/eclipse/java7/.project
- org.eclipse.jdt.ls.tests/projects/eclipse/java7/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.jdt.ls.tests/projects/eclipse/java7/src/java/Foo.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
> Enable release flag by default

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodRefactoring.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
Fix issue: https://github.com/eclipse/eclipse.jdt.ls/issues/709
@fbricon
> Fix extract method issues for anonymous class.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Generate links in CompletionItems' Markdown documentation

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Relates to https://github.com/redhat-developer/vscode-java/issues/608
> Should publish diagnostic information for project level

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
> Ensure FormattingOptions.isInsertSpaces is not ignored when set to false

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update m2e to 1.9.1.20180829-1411

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
Fixes https://github.com/redhat-developer/vscode-java/issues/605
> Status message 'Updating Maven projects' shows progress more than 100%

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update m2e to 1.9.1.20180906-0204

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
> Migrate to lsp4j 0.5.x

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
> Wait for lifecycle jobs before returning document symbols

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes https://github.com/redhat-developer/vscode-java/issues/653
> Update buildship to 2.2.2.v20180918-2317-s

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java
- org.eclipse.jdt.ls.tests/projects/maven/multimodule2/module1/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/multimodule2/module2/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/multimodule2/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupportTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/702
> Fix NPE in MavenBuildSupport.java

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
> Server should understand ~/.m2/settings.xml

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
@snjeza @fbricon 
Fix for https://github.com/eclipse/eclipse.jdt.ls/issues/867.
> Reset diagnostics information when closing files.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ReorgQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
> BasicFileDetectorTest tests fail randomly

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticHandlerTest.java
> DiagnosticHandlerTest.testMultipleLineRange fails randomly

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Migrate to lsp4j 0.6.0

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Migrate to Buildship 3.0

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
> Fix NPE for InvisibleProject

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/723
> NullPointerException being reported on extension start up

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
> Don't send empty code actions

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/GenerateGetterSetterOperation.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/GenerateGetterAndSetterTest.java
> Bulk generate accessor should ignore static fields

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandlerTest.java
https://github.com/eclipse/eclipse.jdt.ls/issues/825
@fbricon @mickaelistria
> Enable parallel build for JDT.LS.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
> Ensure workspaceedits with document changes are not ignored

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update m2e target repo.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
Checks if ResourceOperations is missing and returns false.
fixes #912
> Add check for missing ResourceOperations

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/StatusFactory.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/OrganizeImportsCommand.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/SourceAttachmentCommand.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/SerialVersionHashOperation.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractConstantRefactoring.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractTempRefactoring.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ChangeCorrectionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceExecuteCommandHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/BundleUtilsTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/StatusFactoryTest.java
Changes references to JavaLanguageServerPlugin.PLUGIN_ID to
IConstants.PLUGIN_ID
> Remove deprecated PLUGIN_ID use

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java
> File handle leak on Win with Java 11(.0.2)

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java
Fixes https://github.com/redhat-developer/vscode-java/issues/815
> Workaround for corrupted tasklist command

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
> Fix a compile error

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
> Make ParentProcessWatcher optional

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/maven/foldingRange/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/TestFoldingRange.java
- org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/TestUnmatchFoldingRange.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
> Add folding range support.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/RegionFoldingRange.java
- org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/SimpleFoldingRange.java
- org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/StatementFoldingRange.java
- org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/UnmatchFoldingRange.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandlerTest.java
> Add region folding range support.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.properties
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/CodeActionUtil.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/StaticImportQuickAssistTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HashCodeEqualsActionTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HashCodeEqualsHandlerTest.java
Closes redhat-developer/vscode-java#796
> Enable static import proposal in quick assist actions

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
> Optimize validation

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTest.java
> Optimize compilation unit computations

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
Fixed #981 
relates to https://github.com/redhat-developer/vscode-java/pull/869
> Optimize server initialization

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch1/batchchild/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch1/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch10/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch11/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch2/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch3/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch4/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch5/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch6/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch7/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch8/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/batch9/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/batch/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupportTest.java
> Batch Maven project imports to reduce memory consumption

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
> Revert https://github.com/eclipse/eclipse.jdt.ls/pull/984

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java
Fixes https://github.com/redhat-developer/vscode-java/issues/883
> Should show more progress details when Starting Java Language Server

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java
Fixes https://github.com/redhat-developer/vscode-java/issues/896
> Building the workspace job should show more progress details

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java
> Log resource in error in BuildWorkspaceHandler

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
> Signature Help doesn't correctly detect the active signature

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
@fbricon The upstream changes https://git.eclipse.org/r/#/c/140560/ are pending lots of uncertainty. Before upstream gets merged, fix on language server side to minimize the perf penalty specifically for Windows.
> Fix for windows IO perf issue.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/AssignToVariableAssistProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/CodeActionUtil.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AssignToFieldQuickAssistTest.java
> QuickFix: Assign parameter to new field

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ConstructorFromSuperclassProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConstructorQuickFixTest.java
> Add quickfix to handle unimplemented constructors from super class

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
> [WIP] WorkspaceDiagnosticsHandlerTest.testResetPomDiagnostics fails randomly

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/916
>  Fix potential NPE with formatter URL

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
> Error on document close, after renaming a file

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
> Signature help doesn't match active parameter per type

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update buildship to 3.1.0

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
> WorkspaceDiagnosticsHandlerTest tests fail

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/hover/JavaElementLabelComposer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/hover/JavaElementLabels.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaElementLinks.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/IConstantDefault.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Provide more hover info in certain cases

- launch/jdt.ls.remote.launch
- launch/jdt.ls.remote.server.launch
See https://github.com/redhat-developer/vscode-java/issues/949
Related PR - https://github.com/redhat-developer/vscode-java/pull/954
> Add launch configurations for remote debugging

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update target platform to use eclipse 4.13-I-builds

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Upgrade lsp4j to 0.7.2

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/946
> Use the default GRADLE_USER_HOME if possible for Gradle wrappers and modules

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JSONUtility.java
> Fix ClassCastException caused by JSONUtility.toModel method

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/test1/SignatureHelp.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/test1/Varargs.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
> Signature help returns wrong active parameter

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> IllegalArgumentException thrown on completionItem/resolve if there's no javadoc

- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Foo5.java
> CompletionHandlerTest.testCompletion_nojavadoc fails

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> jdt.ls tests fail

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java
- org.eclipse.jdt.ls.tests/projects/maven/salut/src/main/java/java/Foo2.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
> Fixes @apiNote not being rendered from the javadoc when hovered

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/AdvancedQuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InvertVariableTest.java
This is to resolve #1117. 
For the client side change, please refer to https://github.com/redhat-developer/vscode-java/pull/997
Below is the gif for illustration:
> Enable the 'invert local variable' fix

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
> Fix jdt dependency issue

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationCollector.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationsHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Foo2Child.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/FooChild.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/FooService.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/IFoo.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationsHandlerTest.java
Fix redhat-developer/vscode-java#886
> Fix bug: go to implementation doesn't work for method invocation

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
> Secondary same-line error not reported

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ReorgCorrectionsSubProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ReorgQuickFixTest.java
Fixes redhat-developer/vscode-java#1030
> [QuickFix]Create non existing package when package declaration mismatch

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ConvertForLoopTest.java
> Convert for-loop to for-each loop

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
Fix redhat-developer/vscode-java#1056
> Fix bug: the client never received server Ready notification

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/StaticReferenceQuickFixTest.java
Fixes #440
To test, recreate one of the examples in the test file and try to get a code action for inserting static
> Adds quickfix for non-accessible references

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandlerTest.java
> PrepareRename works incorrectly when called over import

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InlineVariableTest.java
Close #771
Add inline variable proposal for issue #656
> Refactoring: inline local variable

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
> Fix target range for quickfix:surround with try/multi-catch

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java
Fixes #1121 
@amisevsk @tsmaeder @tolusha @svor @rbcminghou @l0rd  you can check https://raw.githubusercontent.com/snjeza/vscode-test/master/java-0.50.0.vsix
Recommended VM arguments:
```
"java.jdt.ls.vmargs": "-Daether.connector.requestTimeout=10000 -Daether.connector.connectTimeout=10000 -noverify -Xmx1G -XX:+UseG1GC
-XX:+UseStringDeduplication"
```
> Provide more granularity of progress during Maven import

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java
- org.eclipse.jdt.ls.tests/projects/maven/reactor/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
> Workspace symbols may have records without name

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Only filter types from completion

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
Fixes #1223 
The issue is caused by the following commit - https://github.com/eclipse/eclipse.jdt.ls/commit/dc1670fdb9c91886d9f27941d72941f700440be9
> Test failures

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Close #1227
- Method
- Field
- Anonymous Type
- Type
- Package
> Provide better symbol detail for the completion proposal

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/AdvancedQuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InvertConditionTest.java
> Better expose the 'Invert Condition' code action

- .mvn/wrapper/maven-wrapper.properties
Signed-off-by: Yan Zhang <yanzh@microsoft.com>
> Upgrade wrapper to use Maven 3.6.2

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupportTest.java
> MavenBuildSupportTest.testDownloadSources fails

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes #1228
See tests in https://github.com/jbosstools/m2e-apt/commit/a3fac58cfa18b756adb8db04c2408c17843f2ac0#diff-0229cd3fd647274e3d8e3f442a291b4fR298-R303
> Update m2e-apt to 1.5.3

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/AssignToVariableAssistProposal.java
> Change 'assign constructor parameters' actions to 'quickassist' kind

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
> Change for-loop conversion to 'refactor' kind

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
This is a minor patch for PR #1265.
> Missing brackets to wrap the condition check

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AdvancedExtractTest.java
> Change add-final-modifier action to 'refactor' kind

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fixes #1284 
Related to #1283 
> HoverHandlerTest.testHoverOnPackageWithJavadoc fails

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BundleUtils.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/BundleUtilsTest.java
fix #1286 
This PR is to add the location check back when loading bundles.
> Check the location as well when loading bundles

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
> Incorrect signatures returned assertEquals

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
> FormatterHandlerTest.testFormattingOnTypeNewLine/testRangeFormatting tests fail

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManagerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1230
> Terminal shows duplicate task name for progress

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java
> "Remove 'final' modifier" code actions

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
> eclipse.jdt.ls build fails

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1261
> Format Switch Statement

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/MissingEnumQuickFixTest.java
> Add missing case labels in switch statements

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/MyList.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1258
The PR also fixes the same issue in textDocument/signatureHelp.
> Java Suggestion Details doesn't work right sometimes

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
> Adopt the new lsp4j 0.9.0 bits to fix build errors

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
This PR is an option to fix issue #1348 .
> match filterText with textEdit

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
> jdt-ls-master fails

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1298
> Allow renaming lambda parameters

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
See #1370
This reverts commit 2eb0ab282234822bedd175536dc5c7bebd5171a9.
> Use more stable update sites in TP

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1310
Requires https://github.com/redhat-developer/vscode-java/pull/1323
> Add GRADLE_USER_HOME preference

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattener.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattenerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1319
> j.i.gradle.arguments and j.i.gradle.jvmArguments aren't properly defined

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceFolderChangeHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceFolderChangeHandlerTest.java
> Update the root path on workspace folder change event

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeGenerationTemplate.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.tests/projects/eclipse/java14/src/main/java/org/sample/Test.java
- org.eclipse.jdt.ls.tests/projects/eclipse/records/.classpath
- org.eclipse.jdt.ls.tests/projects/eclipse/records/.project
- org.eclipse.jdt.ls.tests/projects/eclipse/records/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.jdt.ls.tests/projects/eclipse/records/src/main/java/org/sample/Test.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Add record snippet

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/JavadocCompletionProposal.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> No Javadoc completion for records

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FileEventHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ChangeUtilTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FileEventHandlerTest.java
> Compute the rename updates after files renamed

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandlerTest.java
require: https://github.com/redhat-developer/vscode-java/pull/1456
- Notifications will be sent to client for all kinds of projects when classpath get updated.
- Project's root uri is also accepted to query for the project information
> Expand the API usages

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandlerTest.java
Fixes #1450 
The ClasspathUpdateHandlerTest.testClasspathUpdateForMaven test was failing because m2e updates a classpath when downloading a source artifact.
The ClasspathUpdateHandlerTest.testClasspathUpdateForGradle test isn't configured correctly.
The WrapperValidatorTest.testGradleWrapper test was starting more connections than allowed by Jenkins.
> JDT LS tests fail randomly

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java
requires: https://github.com/redhat-developer/vscode-java/pull/1484
> Send started status when light weight server is ready

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
See https://github.com/eclipse/eclipse.jdt.ls/issues/1469#issuecomment-639260181
> Fix NPE in BaseDocumentLifeCycleHandler.publishDiagnostics

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/IConstants.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseInitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxInitHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
> Java runtimes should be configured before projects are imported

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
> Prepare rename breaks if you have edited the symbol just before the call

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/BaseJDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java
See https://github.com/redhat-developer/vscode-java/pull/1501#discussion_r449047437
> Improve Java LS shutdown

- org.eclipse.jdt.ls.core/plugin.xml
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/IConstants.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaCodeActionKind.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/BodyUpdater.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/ChangeMethodSignatureRefactoringContribution.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/ChangeSignatureProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/ExceptionInfo.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/IDefaultValueAdvisor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/ReturnTypeInfo.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/StubTypeContext.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/TypeContextChecker.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/IntroduceParameterRefactoring.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/IntroduceParameterRefactorTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/MissingEnumQuickFixTest.java
Fixes #1420 
Requires https://github.com/redhat-developer/vscode-java/pull/1521
> Add 'Introduce Parameter...' code action

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
... also updates to the latest Buildship snapshot
> Update to Eclipse 2020-09-M3

- org.eclipse.jdt.ls.core/plugin.xml
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javafx/BuildPathSupport.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javafx/FXAccessRuleParticipant.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javafx/FXLibraryLocationResolver.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javafx/FXVersion.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javafx/FXVersionUtil.java
- org.eclipse.jdt.ls.tests/projects/eclipse/java8fx/.classpath
- org.eclipse.jdt.ls.tests/projects/eclipse/java8fx/.project
- org.eclipse.jdt.ls.tests/projects/eclipse/java8fx/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.jdt.ls.tests/projects/eclipse/java8fx/src/foo/Foo.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javafx/JavaFXTest.java
Copies 5 files from [e(fx)clipse](https://github.com/eclipse-efx/efxclipse-eclipse/). See https://github.com/redhat-developer/vscode-java/issues/120#issuecomment-284348935
> Add JavaFX support

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes https://github.com/redhat-developer/vscode-java/issues/1644
> Update 4.17-P-builds to P20201001-0300

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandlerTest.java
Fixes #1548 
See https://github.com/redhat-developer/vscode-java/pull/1646
> Rename includeGetterSetter to includeAccessors

- CHANGELOG.md
> Add changelog for 0.63.0

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/pom.xml
> Update TP to use Eclipse 2020-12 M1.

- CHANGELOG.md
> Add changelog for 0.64.0

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update TP to use Eclipse 2020-12 M3.

- CHANGELOG.md
> Add changelog for 0.66.0

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
> Filter 'sun.*' packages out of completion type results.

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update TP to use Eclipse 2020-12 Release.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
> Filter the source of the diagnostics when resolving refactoring proposals

- CHANGELOG.md
Let me know if there's anything else you're waiting on for the release.
> Add changelog for 0.68.0

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupport.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListener.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
Resolve #1593
See a gif in https://github.com/redhat-developer/vscode-java/pull/1694
> Support to specify output location for invisible project

- CHANGELOG.md
> Add changelog for 0.69.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 0.71.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventHandlerTest.java
> External tool file modifications not registered

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
> Tests fail on Mac

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/RuntimeEnvironment.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JVMConfiguratorTest.java
> Java LS Tests fail randomly

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/formatter/test.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
Fixes #1685 
Fixes https://github.com/redhat-developer/vscode-java/issues/1794
Fixes https://github.com/redhat-developer/vscode-java/issues/1827
> Java formatter is not working

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java
> Fix NPE on Mac

- pom.xml
- https://eclip.se/572043
- Fixes #1707
> Remove pack200 support.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferencesTest.java
Fix https://github.com/microsoft/vscode-java-pack/issues/590, see: https://github.com/redhat-developer/vscode-java/pull/1868
> Fall back to default value when import threashold is non-positive

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupport.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/formatter/settings.prefs
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/TestSerial.java
- org.eclipse.jdt.ls.tests/projects/singlefile/lesson1/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/AbstractSourceTestCase.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JavaSettingsTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1657
Requires https://github.com/redhat-developer/vscode-java/pull/1847
> Link .settings directory to 'invisible project'

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.1.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewCUProposal.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
> NPE in NewCUProposal.createChange()

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JavaSettingsTest.java
> java.settings.url does not override default java settings

- CHANGELOG.md
> Add Changelog for 1.1.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.2.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/FormatterManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
- org.eclipse.jdt.ls.tests/formatter/test.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JavaSettingsTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1917
> Formatter doesn't load format config after update

- CHANGELOG.md
- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Change to 1.1.1-SNAPSHOT for service release.

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.1.2-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/FormatterManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
> Invalid formatter profile name setting causes errors

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java
Fixes redhat-developer/vscode-java#1929
> Fix parameter compatibility issue in buildWorkspace request

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/BaseJDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/DiagnosticsCommandTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/AbstractCompilationUnitBasedTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JavaSettingsTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
> InvisibleProjectImporterTest.automaticJarDetectionLibUnderSource fails

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListener.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListenerTest.java
fix #1764 more details, see: https://github.com/eclipse/eclipse.jdt.ls/pull/1766#issuecomment-840411678
> Fix package name not recognized when opening standalone java files

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
- org.eclipse.jdt.ls.tests/formatter/settings2.prefs
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JavaSettingsTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1939
> java.settings.url is not working

- CHANGELOG.md
> Add Changelog for 1.1.2

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JavaSettingsTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1944
> Fix backslashes (\) in java.format.settings.url

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameTypeProcessor.java
- org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/src/main/java/org/sample/Test.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
Fixes #1775, https://github.com/redhat-developer/vscode-java/issues/1951 and https://github.com/redhat-developer/vscode-java/issues/878
> Fix renaming java file with lombok

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodRefactoring.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1956
> extract method does not seem to like var nor method references

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandler.java
- org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/StaticBlockFoldingRange.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandlerTest.java
- Use method folding logic to also compute static block folding
- Fixes #1777
> Allow folding of static blocks

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests.syntaxserver/projects/maven/salut4/src/main/java/pack/TestSyntax.java
- org.eclipse.jdt.ls.tests.syntaxserver/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxServerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1931
> Update list of excluded errors-Add ParameterMismatch

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/HelloWorld.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticHandlerTest.java
Fixes #1781 
Related Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=572873
> Update target platform to 2021-06 RC2

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes  https://github.com/eclipse/eclipse.jdt.ls/issues/1800
Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=574215
> Update target platform to 4.21 build I20210617-1800

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- Related #1800
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=574338
> Update target platform to 4.21 build I20210621-1800

- CHANGELOG.md
> Add Changelog for 1.2.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.3.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenSourceDownloader.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes #1706 
Fixes https://github.com/redhat-developer/vscode-java/issues/1989
> Update m2e to 1.18.1;buildship to 3.1.5.v20210616-0346-s

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.properties
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
- Fixes #1464
- This change adopts code from https://eclip.se/516504
> Adopt "Create method" code actions for method references & lambdas

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- Fixes redhat-developer/vscode-java#1811
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=553097
> Update target platform to 4.21 build I20210719-1800

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2034
> Update target platform to 4.21 build I20210726-1800

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
See https://github.com/eclipse/eclipse.jdt.ls/issues/1831#issuecomment-895807782
> avoid repeated calculation of URI string

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/App.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/1813
Related Eclipse bug - https://bugs.eclipse.org/bugs/show_bug.cgi?id=574697
> Go to definition doesn't find result on method inside anonymous class

- CHANGELOG.md
We may have some remaining changes, but that I'd start this.
> Add Changelog for 1.3.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.4.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeTemplatePreferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- References redhat-developer/vscode-java#2052
> Add shortmonth variable to type comment templates

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseInitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxInitHandler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2071
a regression of https://github.com/eclipse/eclipse.jdt.ls/issues/451
> [regression] Fix gradle startup performance

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/GenerateGetterSetterOperation.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateAccessorsActionTest.java
See https://github.com/eclipse/eclipse.jdt.ls/issues/1392#issuecomment-915337454
> use getRecordComponents() to fetch record fields since jdt-core 3.26

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update Target Platform to 2021-09 (4.21) Release.

- CHANGELOG.md
Still a few changes to consider..
> Add Changelog for 1.4.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.5.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
fix https://github.com/redhat-developer/vscode-java/issues/2127
> Report the diagnostic range correctly on save

- org.eclipse.jdt.ls.tests/projects/maven/archetyped/src/main/resources/archetype-resources/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/classpathtest/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/quickstart/pom.xml
> Bump JUnit dependencies to 4.13 in some test projects.

- org.eclipse.jdt.ls.tests/projects/maven/archetyped/src/main/resources/archetype-resources/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/classpathtest/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/quickstart/pom.xml
> Bump JUnit dependencies to 4.13.1 in some test projects.

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes #1915 
Related Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=576778
> Update TP to 4.22-I-builds/I20211101-1800

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fixes #1920  https://github.com/redhat-developer/vscode-java/issues/1633
> Race condition between AutoBuildJob and the publish diagnostics job

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ShowAllQuickFixTest.java
> Regression: duplicate implement method quick fixes

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/1855
> Update JDT to I20211116-1800

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OverrideMethodsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/OverrideMethodsActionTest.java
Part of https://github.com/redhat-developer/vscode-java/issues/2057
> Add Override/Implement methods to Show Fixes for type declaration

- CHANGELOG.md
> Add Changelog for 1.6.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.7.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
> Diagnostics from changes to build configuration not reflected in open source files

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
> DocumentLifeCycleHandlerTest.testFixInDependencyScenario fails randomly

- CHANGELOG.md
> Add Changelog for 1.7.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.8.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
Fixes #1980 
Related Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=575149
> 1.7.0 regression on signature help

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ServiceStatus.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
- org.eclipse.jdt.ls.tests/projects/gradle/invalid/build.gradle
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ProjectUtilsTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/filesystem/MavenProjectMetadataFileTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
fix https://github.com/redhat-developer/vscode-java/issues/2243
requires https://github.com/redhat-developer/vscode-java/pull/2244
> Show the error status when imported projects having errors

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Support to complete lambda expression

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.9.0-SNAPSHOT

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update m2e-apt to 1.5.4 (new repo)

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/projects/maven/typemismatch/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/typemismatch/src/test/IndexType.java
- org.eclipse.jdt.ls.tests/projects/maven/typemismatch/src/test/Test.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenClasspathTest.java
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/1971
> Update target platform to I20220203-0300

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/test1/SignatureHelp2097.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2097
> Signature Help sometimes doesn't work

- CHANGELOG.md
> Add Changelog for 1.9.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.10.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/test1/SignatureHelp2097.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2341
> The number of method signatures cannot be displayed in some cases

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
> Update TP to I20220314-1800

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManagerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
> Tests fail randomly

- org.eclipse.jdt.ls.product/scripts/jdtls.py
Use subprocess.run() in jdtls.py. Doesn't reinterpret strings, etc.
Only tested on Windows.
Signed-off-by: Joel Reicher <joel.reicher@gmail.com>
> Change os.system to subprocess.run

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionInsertReplaceCapabilityTest.java
Could be related with https://github.com/redhat-developer/vscode-java/pull/2343
> Support insert replace completion capability

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractFieldRefactoring.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2370
> Cannot refactor in static block

- CHANGELOG.md
> Add Changelog for 1.10.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.11.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
> Add the default FILECOMMENT template to the preference initialization.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
more informations: https://github.com/redhat-developer/vscode-java/pull/2426
> Trigger signature help on completion item selected

- org.eclipse.jdt.ls.tests/pom.xml
> Enable lombok agent

- org.eclipse.jdt.ls.product/scripts/jdtls.py
> Fix java version detection

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
- org.eclipse.jdt.ls.tests/projects/eclipse/projectwithrootsource/.classpath
- org.eclipse.jdt.ls.tests/projects/eclipse/projectwithrootsource/.project
- org.eclipse.jdt.ls.tests/projects/eclipse/projectwithrootsource/MyTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2436
> Error during importing an Eclipse project whose sources are at root

- CHANGELOG.md
> Add Changelog for 1.11.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.12.0-SNAPSHOT

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
> Update to buildship 3.1.6 release

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintFilter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintFilterManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintVisitor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintsPreferenceChangeListener.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintFilterManagerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintHandlerTest.java
requires https://github.com/redhat-developer/vscode-java/pull/2468
> Support the exclusion list for inlay hints

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
Requires https://github.com/redhat-developer/vscode-java/pull/2489
> Fix java.completion.importOrder

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintHandlerTest.java
> Fix 'InlayHintHandlerTest.testVarargs2'

- launch/jdt.ls.remote.server.launch
- launch/jdt.ls.socket-stream.launch
> Remove o.e.m2e.archetype.common

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
> Fix NPE when triggering signature help in class file

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/RefactoringAvailabilityTester.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/GenericRefactoringHandleTransplanter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/IRefactoringProcessorIds.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/JavaRenameProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/MethodChecks.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/MethodOccurenceCollector.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RefactoringHandleTransplanter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RefactoringScanner.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameCompilationUnitProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameEnumConstProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameFieldProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameLocalVariableProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameMethodProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameModifications.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameModuleProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameNonVirtualMethodProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenamePackageProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameTypeParameterProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameTypeProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameVirtualMethodProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RippleMethodFinder.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RippleMethodFinder2.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/TextMatchUpdater.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/TypeOccurrenceCollector.java
- org.eclipse.jdt.ls.tests/projects/eclipse/java17/src/main/java/test1/Main.java
- org.eclipse.jdt.ls.tests/projects/eclipse/java17/src/main/java/test1/Test.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2433
> Renaming record attributes

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionResolveHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ResponseStore.java
Fixes #2111 
Test vsix: https://github.com/snjeza/vscode-test/raw/master/java-1.7.4.vsix
> Sometimes AST will not be updated after applying and undoing code action

- CHANGELOG.md
> Add Changelog for 1.13.0

- CHANGELOG.md
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/DependencyUtil.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenSourceDownloader.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
- org.apache.maven.artifact.Artifact has become a record
> React to API changes in M2E.

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.14.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java
> Compile error in MavenBuildSupport.update(...)

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update target platform to I20220713-1800

- CHANGELOG.md
> Add Changelog for 1.14.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.15.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintVisitor.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/projects/eclipse/java16/src/main/java/foo/bar/Bar.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintHandlerTest.java
fix https://github.com/redhat-developer/vscode-java/issues/2414
> Fix the inlay hints for record class

- org.eclipse.jdt.ls.core/plugin.xml
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/UnmanagedFolderNature.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
- nature: 'org.eclipse.jdt.ls.unmanagedFolderNature' will be added to
unmanaged folders.
> Add unmanaged folder nature id

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
> Non-JDT errors are not reported in Java files

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/2186
Requires https://github.com/redhat-developer/vscode-java/pull/2617
> Add support for Maven offline mode (java.import.maven.offline.enabled)

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/framework/protobuf/ProtobufSupport.java
> Rename the action name from 'Yes' to 'Generate'

- CHANGELOG.md
> Add Changelog for 1.15.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.16.0-SNAPSHOT

- org.eclipse.jdt.ls.product/pom.xml
- pom.xml
- Tycho 2.7.5
- maven-resources-plugin 3.3.0
- maven-clean-plugin 3.2.0
- maven-assembly-plugin 3.4.2
> Update Maven plugin versions

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
Continuation of https://github.com/eclipse/eclipse.jdt.ls/pull/2140
> make use of GitHub functions for library update and security analysis

- org.eclipse.jdt.ls.product/scripts/jdtls.py
This PR should take care of https://github.com/eclipse/eclipse.jdt.ls/issues/2191 and improve the interaction with Eglot (see https://github.com/joaotavora/eglot/issues/1008). Or at least, it's a start. :)
If I am missing something, please do let me know. I'm not a Python expert, so I may be setting `-data` in the wrong way here.
> Pass data directory to jdtls (#2191)

- org.eclipse.jdt.ls.core/gradle/protobuf/init.gradle
fix https://github.com/redhat-developer/vscode-java/issues/2700
> Fix NPE in the protobuf init script

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.17.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandler.java
- org.eclipse.jdt.ls.tests/projects/eclipse/reference/src/org/reference/Main.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandlerTest.java
> Support includeDeclaration in textDocument/references

- launch/jdt.ls.remote.server.launch
- launch/jdt.ls.socket-stream.launch
- launch/jdt.ls.socket-stream.syntaxserver.launch
> jdt.ls.socket-stream.launch&jdt.ls.remote.server.launch are not running cleanly

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2133
> Provide folding import regions for .class files

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaPostfixContext.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
> Fix the NPE in JavaPostfixContext#canEvaluate()

- CHANGELOG.md
> Add Changelog for 1.17.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.18.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/MemberAccessUsesThisCleanUp.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/StringConcatToTextBlockCleanUp.java
> Add clean up to convert string concatenation to text block

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fixes #2331 
A related PR - https://github.com/eclipse/eclipse.jdt.ls/pull/2328
> WorkspaceDiagnosticsHandlerTest.testMissingNatures fails sometimes

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameFieldProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandler.java
- org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/src/main/java/org/sample/Main.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2805
> Better support of lombok

- CHANGELOG.md
> Changelog for 1.18.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.19.0-SNAPSHOT

- launch/jdt.ls.remote.server.launch
- launch/jdt.ls.socket-stream.launch
- org.eclipse.jdt.ls.product/languageServer.product
- org.eclipse.jdt.ls.product/syntaxServer.product
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
- pom.xml
Fixes https://github.com/redhat-developer/vscode-java/issues/2826
> Update m2e to m2e latest

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaPostfixContext.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixCompletionProposalComputer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
> Stop showing post fix completion in JavaDoc

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
fix https://github.com/eclipse/eclipse.jdt.ls/issues/2376
> Fix the NPE when selecting snippet completion item

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/surround/SurroundWithTryCatchRefactoring.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
- See redhat-developer/vscode-java#2711
> Fix scope calculation for "Surround with try/catch" refactoring.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> Critical completion issue for completions on a object inside block

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OrganizeImportsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/maven/salut4/src/test/java/org/sample/Test1.java
- org.eclipse.jdt.ls.tests/projects/maven/salut4/src/test/java/org/sample/Test2.java
- org.eclipse.jdt.ls.tests/projects/maven/salut5/proj/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/AdvancedOrganizeImportsHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2861
> organize imports remove static imports

- CHANGELOG.md
> Changelog for 1.19.0

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.filesystem/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.filesystem/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
> Upversion to 1.20.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2569
Requires https://github.com/redhat-developer/vscode-java/pull/2878
> Add java.import.maven.disableTestClasspathFlag

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/TryWithResourceCleanUp.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
> Add try-with-resource clean up

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandlerTest.java
> reference search doesn't work for fields in JDK classes

- launch/jdt.ls.socket-stream.syntaxserver.launch
this PR is a following fix of #2363, fix `jdt.ls.socket-stream.syntaxserver.launch` file as well.
> Fix syntaxserver launch file

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
Check if the request to upgrade gradle is cancelled, right before making any changes to the gradle build files.
See #2415
Signed-off-by: David Thompson <davthomp@redhat.com>
> Check if gradle upgrade is cancelled

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
fix https://github.com/redhat-developer/vscode-java/issues/2942
For some imcompatible Gradle projects buildship can't create corresponding `GradleBuild`. (for other imcompatible projects it can), in these cases, we will also try to update the version for them. More details can be found in the method javadoc.
> Enable upgrading the Gradle version in projects without GradleBuild

- CHANGELOG.md
- Push release date to Feb 20
Although there's an additional commit, it's addressing a fix to a feature that is also new, so we don't really need to mention it.
> Update Changelog for 1.20.0

- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
> Update Maven wrapper to Maven 3.9.0

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenCentralIdentifier.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java
Fixes #2464 
I have added -Djava.lsp.mavensearch.timeout=60 to https://ci.eclipse.org/ls/job/jdt-ls-pr/ (the default timeout is 10). See https://github.com/eclipse/eclipse.jdt.ls/pull/2466/commits/01eaec87ba6926f929d3248cff553d61049cfb37#diff-53b3c61d016260d338b175aa83d8fecf6fbc1bd1e4dc6152f1b722089ac5fc0dR89
> InvisibleProjectBuildSupportTest.testDynamicSourceLookups fails randomly

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentHighlightHandler.java
fix https://github.com/redhat-developer/vscode-java/issues/2952
> Fix NPE in textDocument/documentHighlight requests

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
Fixes https://github.com/eclipse/eclipse.jdt.ls/pull/2486#discussion_r1116462755
> Fix Null Analysis for Eclipse/invisible project

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintsPreferenceChangeListener.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferencesTest.java
fix https://github.com/eclipse/eclipse.jdt.ls/issues/2365
> Check the client capability for inlay hints

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/CodeActionUtility.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateAccessorsActionTest.java
> Respect `java.quickfix.showAt` in generate accessors quick fix

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionResolveHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsActionTest.java
added function to not show generate constructor if field is static Bug #2142
signed off by: Jason Wang <jaswan@redhat.com>
> Do not show "Generate Constructors" quick assist for static fields

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
> Implement itemDefaults for CompletionList

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommand.java
improve functionality of the cancelling of the type hierachy command
see: #2415 
Signed-off By: <jaswan@redhat.com>
> Investigate cancelling delegate commands

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/GradleCompatibilityProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
require https://github.com/redhat-developer/vscode-java/pull/3014
fix https://github.com/redhat-developer/vscode-java/issues/3001
> Separate java.project.upgradeGradle client and server command

- org.eclipse.jdt.ls.core/schema/org.eclipse.jdt.ls.core.contentProvider.exsd
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ContentProviderManager.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3012
> Use contributed decompiler when opening class files

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/TelemetryManager.java
- Fix #2565 
- Use the Java model manager (instead of the Index manager) to collect dependencies since it more easily allows us to exclude unwanted resources (eg. JVM libraries, source entries)
- Only report compiler target levels when they exist
> Improve project dependency reporting.

- CHANGELOG.md
- It would be good if I can review https://github.com/eclipse/eclipse.jdt.ls/pull/2556 and get it merged for this release.
> Changelog for 1.22.0

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/2603
> Enable and use debugTrace messages

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixCompletionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
> Support lazy-resolving for postfix completion

- CHANGELOG.md
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/BuildPathCommandTest.java
> Changelog for 1.23.0

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/2626
> Fix ranges for snippet completion

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/CompletionUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/JavadocCompletionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerLazyResolveTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
> Add CompletionItem InsertTextMode Support

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java
It's deprecated due to a typo and is now
CleanUpConstants.CONTROL_STATEMENTS_CONVERT_FOR_LOOP_TO_ENHANCED
> Stop using CleanUpConstants.CONTROL_STATMENTS_CONVERT_FOR_LOOP_TO_ENHANCED

- org.eclipse.jdt.ls.product/scripts/jdtls.py
Related to https://github.com/eclipse/eclipse.jdt.ls/issues/2615 and  https://github.com/eclipse/eclipse.jdt.ls/pull/2654
> Update jdtls script to check for os.name

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
https://github.com/eclipse-m2e/m2e-core/releases/tag/2.3.0
> Update target platform to use m2e 2.3.0 release.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.tests/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
Fixes #2669 
No completions on field initializer with @Default and @Builder Lombok annotations
> [lombok] No completions on field initializer

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
- org.eclipse.jdt.ls.tests/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
This reverts commit d6c1453952bcda9b6809003053ff1bbe3b91f71b.
> Re-apply "[lombok] No completions on field initializer"

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
> Consider variable outside of selection to guess better extracted method name

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java
> Initiate progress reporting with window/workDoneProgress/create

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDeclarationHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/eclipse/declaration-test/.classpath
- org.eclipse.jdt.ls.tests/projects/eclipse/declaration-test/.project
- org.eclipse.jdt.ls.tests/projects/eclipse/declaration-test/src/Car.java
- org.eclipse.jdt.ls.tests/projects/eclipse/declaration-test/src/MovingObject.java
- org.eclipse.jdt.ls.tests/projects/eclipse/declaration-test/src/PackageOne/Foo.java
- org.eclipse.jdt.ls.tests/projects/eclipse/declaration-test/src/PackageTwo/Foo2.java
- org.eclipse.jdt.ls.tests/projects/eclipse/declaration-test/src/TestSame.java
- org.eclipse.jdt.ls.tests/projects/eclipse/declaration-test/src/Vehicle.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDeclarationHandlerTest.java
> Implement go to declaration

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/LogHandler.java
Send a trace event to the client if the server encounters an error or an exception.
> Track errors & exceptions on server side for reliability analysis

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServerApplication.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Reverts eclipse/eclipse.jdt.ls#2719
> Revert "Set progressManager in application"

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
fix https://github.com/eclipse/eclipse.jdt.ls/issues/2617
fix https://github.com/redhat-developer/vscode-java/issues/3074
> #2617 Return package name for IClassFile to populate Outline view

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
> Fix NPE in DocumentMonitor

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
> Java LS freezes

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
> Syntax server appears to freeze

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BundleUtils.java
> Don't start fragments

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes https://github.com/redhat-developer/vscode-java/issues/2758
> Update target platform to I20230726-1800

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes https://github.com/redhat-developer/vscode-java/issues/3233
> Update target platform to I20230801-1800

- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.product/publish-assembly.xml
- pom.xml
Add build config for arm aarch64 and copy configs into repository
> Add support for aarch64

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
Easier to copy/paste test code and play with it that way.
> Convert CleanUpTest to use text blocks

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandler.java
- org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/SimpleFoldingRange.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandlerTest.java
Fixes redhat-developer/vscode-java#860
> Add folding range for multiple single-line comments

- org.eclipse.jdt.ls.logback.appender/src/org/eclipse/jdt/ls/logback/appender/JavaLsConfigurator.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
https://github.com/eclipse-m2e/m2e-core/blob/master/RELEASE_NOTES.md#24
> Update m2e to 2.4.0

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaContextType.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaContextTypeRegistry.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes #2800
Adds the following snippets:
switch
try_catch
try_resources
main / psvm
ctor
method
new
field
> Introduce new snippet templates with appropriate context

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerTestPlugin.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javafx/JavaFXTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtilsTest.java
Trying to fix Java LS tests.
- https://ci.eclipse.org/ls/job/jdt-ls-master/1800/testReport/junit/org.eclipse.jdt.ls.core.internal.correction/AnnotationMissingAttributeQuickFixTest/testMultipleRequiredAttributes/
- https://ci.eclipse.org/ls/job/jdt-ls-master/1800/testReport/junit/org.eclipse.jdt.ls.core.internal.correction/AnnotationMissingAttributeQuickFixTest/testMultipleRequiredAttributes/
- https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2737
- https://ci.eclipse.org/ls/job/jdt-ls-pr/4527/
> Fix Java LS tests

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javafx/JavaFXTest.java
> Intermittent failure of testSignatureHelpForSelectedCompletionProposal

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandlerTest.java
- Fix bug introduced by https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2867
- test cases line ranges are sensitive to new lines
> Adjust FoldingRangeHandlerTest testcase.

- org.eclipse.jdt.ls.tests/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ResourceUtilsTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java
> Fix tests on Windows

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
Fixes the regression identified in https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2874#issuecomment-1747229116
> Avoid attempts to sort by parameter count for members that do not support it

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OrganizeImportsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2633
> Add extended client capability for workspace/executeClientCommand

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
Do not interrupt processing if there is no resource found; following steps can still be performed normally.
> Publish diagnostic for external files

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporter.java
this is used to help understand the invalid project description issue at https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2845.
> Log the specific failure message when importing eclipse project

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Implements solution suggested in https://github.com/redhat-developer/vscode-java/issues/3041#issuecomment-1772992095.
> Add 'print' alias for sysout snippet

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaLanguageServerTemplateStoreTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes redhat-developer/vscode-java#2105
It can improve main method discovery and also mitigate the issue at redhat-developer/vscode-java#2105
> Add new alias 'public static void main(String[] args)' for public main method

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
> Error when parsing resource filter

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3282
- Access the named pipe from --pipe flag, as per specification
- On Windows, pipes are implemented via. named pipes
- On Linux & MacOS pipes are implementated via. unix sockets
If we agree it's correct, we could merge as-is since the code path is only activated when `--pipe` is detected and let clients decide whether to use it or not.
> Support named pipes for client/server communication.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3358.
> Fix constructor completion when guessMethodArguments is off

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
> Add null check for isWorkDoneProgressSupported()

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
> Handle resolving completion items with improper declaration signature

- .github/workflows/licensecheck.yml
A fix as explained in
https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2966#issuecomment-1821881109
> Fix licensecheck running

- CHANGELOG.md
- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.filesystem/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.filesystem/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
- Bump down from 1.31.0 to 1.30.1 for a service release
> Changelog for 1.30.1

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
One variable assignment is duplicated
> The assignment to variable workingCopy has no effect

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
> Update target platform to I20231220-0750

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/projects/gradle/null-analysis/src/main/java/org/sample/Test.java
- org.eclipse.jdt.ls.tests/projects/gradle/null-analysis/src/main/java/org/sample/package-info.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/NullAnalysisTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3431
Requires https://github.com/redhat-developer/vscode-java/pull/3436
> Add java.compile.nullAnalysis.nonnullbydefault property

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/StringConcatenationQuickFixTest.java
Add support for following conventions
- String To MessageFormat
- String To Buffer|Builder
- String To String.format
> Add support for new headless quick fixes upstream for string concatenation

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3444
> Avoid returning DocumentPasteEdit when no edits are made

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
> Add static registration for textDocument/declaration

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java
> Avoid string concatenation with Runtime.getRuntime().exec(..).

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ImportNewProjectsTest.java
Fixes redhat-developer/vscode-java#3464
When using the command `java.project.changeImportedProjects` to import a maven submodule directly, it fails to detect the parent pom and won't import it as a new project. The fix will search for the parent pom from the project info and maven model,  which can handle this case better.
> Allow to import the newly created maven submodule within a multi-module project

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/UnInitializedFinalFieldSubProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnInitializedFinalFieldQuickFixTest.java
> Add Quickfix 'UninitializedBlankFinalField'

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SuppressWarningsSubProcessor.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/MissingEnumQuickFixTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
Fixes #2698 
Requires https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1077
> Add suppress warnings to quickfix

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandlerTest.java
Language server support to address https://github.com/redhat-developer/vscode-java/issues/3424.
> Add support for manual cleanup actions command

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java
fix https://github.com/redhat-developer/vscode-java/issues/3470
> Add Gradle 8.5 to the compatibility check

- org.eclipse.jdt.ls.core/about.html
- org.eclipse.jdt.ls.core/build.properties
- org.eclipse.jdt.ls.filesystem/about.html
- org.eclipse.jdt.ls.filesystem/build.properties
- org.eclipse.jdt.ls.logback.appender/about.html
- org.eclipse.jdt.ls.logback.appender/build.properties
- org.eclipse.jdt.ls.tests.syntaxserver/about.html
- org.eclipse.jdt.ls.tests.syntaxserver/build.properties
- org.eclipse.jdt.ls.tests/about.html
- org.eclipse.jdt.ls.tests/build.properties
- Fix some warnings in build.properties files
> Add missing About files to bundles.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- I20240227-1800 is approximately 4.31 RC1
> Update target platform to latest Eclipse 4.31-I-builds.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/102
> Use proper Unnamed Class API.

- CODE_OF_CONDUCT.md
- SECURITY.md
- See https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/703
> Add missing files to the root of the project.

- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3141
> Update target platform to newer 4.32-I-builds (I20240422-1800).

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3396
Before:
After:
> Fix indentation for newline preceded by comma

- org.eclipse.jdt.ls.core/gradle/init/init.gradle
- org.eclipse.jdt.ls.tests/projects/gradle/nameconflict2/complete/build.gradle
- org.eclipse.jdt.ls.tests/projects/gradle/nameconflict2/complete/settings.gradle
- org.eclipse.jdt.ls.tests/projects/gradle/nameconflict2/initial/build.gradle
- org.eclipse.jdt.ls.tests/projects/gradle/nameconflict2/initial/settings.gradle
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
> Failed to import a folder with multi gradle projects

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
- org.eclipse.jdt.ls.tests/projects/maven/invalid2/module1/pom.xml
- org.eclipse.jdt.ls.tests/projects/maven/invalid2/pom.xml
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3639
Test vsix - [VS Code 1.34.0](https://github.com/snjeza/vscode-test/raw/master/java-1.34.0.vsix)
> Clean up invalid projects during the initialized phase

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandler.java
- Fixes #3206 
- When classFileContentsSupport set to false, call hierarchy item's URI will be null, so we should handle this for clients
> Fix NPE occuring when a call hierarchy item may not support class files.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
- Fixes https://github.com/redhat-developer/vscode-java/issues/3735
> isExcludedFile(..) to return false immediately when no patterns.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerTestPlugin.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javafx/JavaFXTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
See https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3238#issuecomment-2287213206
m2e toolchains can be disabled by JVM argument `-DlookupJVMInToolchains=false`
> Enable m2e toolchains.xml

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java
- Assume such expressions are always true as a lower compliance is no longer supported
> React to removal of 'is70orHigher' from JDT.

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
> CompletionHandlerTest.testCompletion_Lambda fails randomly

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BundleUtils.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3926
> Fix a potential deadlock in SearchEngine

- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
The related PR - https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3373
> Update gradle version to 8.5 in GradleProjectImporterTest

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/PatternInstanceofToSwitchCleanup.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AssistQuickFixTest21.java
- https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1919
- https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1978
- Add test cases
> New quick assist & cleanup for pattern instanceof if chain to switch.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/decompiler/FernFlowerDecompiler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3949
Test vsix: https://github.com/snjeza/vscode-test/raw/refs/heads/master/java-1.41.1.vsix
> Characters not showing correctly in decompiled file

- .github/workflows/updateTarget.yml
- pom.xml
The goal here is to automate, and have better awareness over updates to our dependencies.
> Add GitHub workflow to automatically update target platform.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/MakeStaticTest.java
- See https://eclipse.dev/eclipse/news/4.31/jdt.html#new-make-static-refactoring
- https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/689 for reference
- Convert instance methods into static methods when possible
> Add 'Make static' refactoring.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionResolveHandler.java
- Fixes https://github.com/redhat-developer/vscode-java/issues/3978
> Ensure resulting workspace edit is not null.

- .github/workflows/codeql-analysis.yml
- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.filesystem/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.filesystem/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
- Undo bump of JDK (continue on JDK 23)
> Upversion to 1.47.0-SNAPSHOT.

- .github/workflows/licensecheck.yml
- .github/workflows/updateTarget.yml
- README.md
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/PartialSortMembersOperation.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaContext.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/MultiVariableGuess.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java
- Based on review on https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/719
- https://github.com/eclipse-jdtls/.eclipsefdn/pull/8
- Rename other existing references to better comply with project guidelines
> Rename default branch to main.

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java
- org.eclipse.jdt.ls.product/languageServer.product
- org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
- Update jakarta.servlet-api
- See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2200
> Code action for "The left-hand side of an assginment must be a variable"

- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
- mvn wrapper:wrapper -Dmaven=3.9.9
- Fixes https://github.com/redhat-developer/vscode-java/issues/4056
> Update Maven wrapper script to use Maven 3.9.9.

- org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.core/pom.xml
- org.eclipse.jdt.ls.filesystem/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.filesystem/pom.xml
- org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.logback.appender/pom.xml
- org.eclipse.jdt.ls.product/pom.xml
- org.eclipse.jdt.ls.repository/pom.xml
- org.eclipse.jdt.ls.target/pom.xml
- org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests.syntaxserver/pom.xml
- org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
- org.eclipse.jdt.ls.tests/pom.xml
- pom.xml
Can't be merged just yet as I'm still waiting to get a JDT-LS build out. Infra is either down or very flaky : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6341 .
> Upversion to 1.49.0-SNAPSHOT

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtilsTest.java
> Fix Gradle/Java Compatibility Matrix

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java
- When 'MethodMustOverride' problem is reported (or not)
- Add test case
- Fixes https://github.com/redhat-developer/vscode-java/issues/4064
> Add code actions for creating method in base type.

- .vscode/extensions.json
Including the java extensions pack and the pde extension.
Fixes #3501
> Add extensions.json

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
> Delay VS Code Java listeners

- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java
- org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/4163
Requires https://github.com/redhat-developer/vscode-java/pull/4181 
cc @rgrunber @fbricon @maxandersen @mickaelistria
> Enable formatting java in jupyter notebook

- org.eclipse.jdt.ls.product/scripts/jdtls.py
- Add workaround for JAXP limits on JDK24
- Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3516
I put something quick together. Let me know if this is good enough @mfussenegger .
> JDT-LS script should try to store workspace folders under common cache.
