org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/javadoc/JavaDoc2HTMLTextReader.java
When hovering over HashMap type, the javadoc shown at the end for the Parameters is wrong. It starts with '>' .....
It should prints <K> in bold followed by the parameter description. Some code has been commented out and this is wrong as it doesn't convert the < into &lt;.
The proposed fix prints the right documentation.
=> Fix for parameter with generic types (HashMap type hover).

.vscode/tasks.json, org.jboss.tools.vscode.product/pom.xml, pom.xml
Adds a build plugin to pom.xml that can be used to watch the source code
changes and build the server and copy it to vscode/server folder.
tasks.json has an example usage.
=> adds watch target for builds

org.jboss.tools.vscode.java/META-INF/MANIFEST.MF, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/JDTUtils.java, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/JavaClientConnection.java, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/JavaLanguageServerPlugin.java, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/DiagnosticsHandler.java, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/DocumentLifeCycleHandler.java, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/HoverHandler.java, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/WorkspaceDiagnosticsHandler.java, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/managers/EclipseProjectImporter.java, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/managers/ProjectsManager.java, org.jboss.tools.vscode.tests/projects/eclipse/hello/src/NoPackage.java, org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/AbstractWorkspaceTest.java, org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/JDTUtilsTest.java, org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/JobHelpers.java, org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/WorkspaceHelper.java, org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/managers/AbstractProjectsManagerBasedTest.java, org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/managers/EclipseProjectImporterTest.java, org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/managers/ProjectsManagerTest.java
Standalone Java files are linked to a default Java project providing a default classpath allowing for content assist for Base JDK classes
For now the main problem is we lose Java support when a Java file opened in memory (i.e not backed by an existing file on disk) is saved. 
Signed-off-by: Fred Bricon fbricon@gmail.com
=> Support standalone java files (#60)

org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/contentassist/CompletionProposalReplacementProvider.java, org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/CompletionResolveHandler.java, org.jboss.tools.vscode.tests/src/org/jboss/tools/vscode/java/internal/handlers/CompletionHandlerTest.java
Merge proposal `()` and required proposal `constructor` in 1 text edit
Fixes https://github.com/redhat-developer/vscode-java/issues/143
Requires https://github.com/gorkem/java-language-server/pull/129 to be applied.
=> Fix completions for constructors

README.md
Interested to see the feedback on this. I think I might be missing some deeper features/configs that would be worth highlighting
=> Add instructions on starting server to README

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/SharedASTProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/TextEditConverter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/DiagnosticsHelper.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/UnusedCodeCorrections.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentHighlightHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
Implements “insert quotes” and remove import
code actions. Lays the groundwork for more
code actions.
=> Initial implementation for code actions

README.md, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java
Falls back to using standard streams of the process for
transport. Closes #130
=> Support for standard streams as transport

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/TextEditConverter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/DiagnosticsHelper.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/UnusedCodeCorrections.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
Implements a quick fix for SuperfluousSemicolon. Improves
DiagnosticsHelper and TextEditConverter.
=> Empty statement quick fix

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/Environment.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactoryTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/EnvironmentTests.java
Removes the static instance for connection creation since
the connection is created only once. Adds tests for
connection selection. Adds a helper for reading environment
and System properties.
=> Reorganize connection creation

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
=> Don't call System.exit on exit, might cause workspace corruption

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
See https://github.com/redhat-developer/vscode-java/issues/166
=> Ensure default package classes don't break completion. Fixes redhat-developer/vscode-java#166

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
This allows opening a help page on the client side, see https://github.com/redhat-developer/vscode-java/issues/193
=> Add More Info command in case of incomplete classpath

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
#212 DocumentSymbolHandler should not exclude attributes via regexp pattern matching
I have used the code from org.eclipse.jdt.internal.ui.javaeditor.JavaOutlinePage.JavaOutlineViewer and  org.eclipse.jdt.internal.ui.filters.SyntheticMembersFilter
=> DocumentSymbolHandler should not exclude attributes via regexp

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
https://github.com/eclipse/eclipse.jdt.ls/issues/214
=> DocumentSymbolHandler should return unambiguous results

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ClassfileContentHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JsonRpcHelpers.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/IFoo.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ClassFileUtil.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ClassfileContentHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/204
This fix also includes generating stub class body for source-less classes.
=> Expand workspace symbol search to all classes from classpath.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/CancellableProgressMonitor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/CancellableProgressMonitorTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/213
=> Catch CancellationException when checking if monitor is cancelled

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.product/languageServer.product, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/AbstractCompletionBasedTest.java
The PR does the following:
- updates the target platform to Oxygen 4.7RC1, buildship 2.0.2
- fixes https://github.com/redhat-developer/vscode-java/issues/212
- fixes the issue with the tests described at https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java#L67
The issue happens when a completion starts before Java Core is initialized. It is more often reproduced in Oxygen >=M7 than in earlier versions of Eclipse.
- fixes https://github.com/redhat-developer/vscode-java/issues/211
You can set a proxy as described in https://github.com/redhat-developer/vscode-java/wiki/Using-a-Proxy
I haven't succeeded to set a proxy in Eclipse without using the Eclipse UI preferences. There are two issues:
- …
=> Gradle import fails behind corporate proxy with auth

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ClassFileUtil.java
This fixes NavigateToDefinitionHandlerTest.testDisassembledSource's failure, when multiple JDKs have been detected.
=> Restrict navigation to classes from current project's classpath

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Baz.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Current package relevance is boosted but unrelevant packages are still proposed.
Partially fixes https://github.com/redhat-developer/vscode-java/issues/234 until
https://bugs.eclipse.org/518140 is fixed in JDT core.
=> Boost relevance of current package during completion

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/SharedASTProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/OverrideCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/CodeGenerationSettings.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/ContextSensitiveImportRewriteContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/ImportReferencesCollector.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/RedundantNullnessTypeAnnotationsFilter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/StubUtility.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/StubUtility2.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/ASTNodeFactory.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2HTMLTextReader.java, org.eclipse.jdt.ls.tests/projects/eclipse/java4/.classpath, org.eclipse.jdt.ls.tests/projects/eclipse/java4/.project, org.eclipse.jdt.ls.tests/projects/eclipse/java4/.settings/org.eclipse.jdt.core.prefs, org.eclipse.jdt.ls.tests/projects/eclipse/java4/src/java/Foo.java, org.eclipse.jdt.ls.tests/projects/eclipse/java5/.classpath, org.eclipse.jdt.ls.tests/projects/eclipse/java5/.project, org.eclipse.jdt.ls.tests/projects/eclipse/java5/.settings/org.eclipse.jdt.core.prefs, org.eclipse.jdt.ls.tests/projects/eclipse/java5/src/java/Foo.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/AbstractCompletionBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
A poor man’s fix for method override code
completion. It improves the current situation but
needs further fixing when we get APIs from JDT
This partially addresses #72 (method body is still missing)
=> Fix for method overrides completion

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporter.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/244
The issue happens because Eclipse LS creates a path with lower case device id on Windows (c: instead of C:, for instance).
Eclipse returns the following errors: "Invalid project description" and "XXX/Test overlaps the location of another project: 'Test'".
The PR fixes the issue by converting the device id to upper case.
=> 'Invalid project description' thrown when opening Eclipse projects

README.md, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactoryTest.java
Adds a duplex pipe connection for https://github.com/redhat-developer/vscode-java/pull/250.
I'm not sure why the existing connection uses two separate pipes for input and output. If not needed it probably can be removed.
=> Add single socket connection

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
See follow up: https://github.com/redhat-developer/vscode-java/pull/245
=> Disable the keybinding of formatting document

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
SignatureHelp UI: 
(Example for TypeScript)
Current provide active parameter and active signature based on parameter number without type context information yet. 
Fixes #12
=> Add SignatureHelp support.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/AbstractJavaDocConverter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/HtmlToPlainText.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2PlainTextConverter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Baz.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/internal/InternalBar.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/internal/package-info.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javadoc/AbstractJavadocConverterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2MarkdownConverterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2PlainTextConverterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/215
=> Return completionItem documentation as plain text

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/StubUtility2.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/AddUnimplementedMethodsOperation.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/UnimplementedCodeFix.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/utils/MethodsSourcePositionComparator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
@fbricon @gorkem 
Fix for https://github.com/redhat-developer/vscode-java/issues/270
=> Add unimplemented methods code action.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/RenameProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameTypeProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RippleMethodFinder.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
@fbricon @gorkem @aeschli 
The basic rename support for java: supports methods/variable/parameter/classname. Not support package rename.  
1. For the main type, since VSCode protocol don't support rename file, it is not the same as eclipse implementation which will rename file also. 
2. Package rename is not supported since it should also rename lots of files/folders. 
3. Currently, rename only failed silently for not supported scenarios. 
https://github.com/redhat-developer/vscode-java/issues/71
=> Add support for renaming.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BundleUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/BundleUtilsTest.java
When the bundle is installed the first time, it is not automatically resolved the bundle. Calling the lazy activation according to this link: https://www.osgi.org/developer/design/lazy-start/
@aeschli @gorkem @fbricon
=> Fix bundle resolve issue when installing

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/CompletionUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/StubUtility2.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Foo$Bar.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/301
The issue happens because the $ sign is in a conflict with snippet support.
=> Autocompletion fails if Class name contains $

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/312
=> IllegalArgumentException in JDTUtils.getPackageName

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/274
When opening and saving a Java file, the PR recreates its compilation unit if necessary.
=> The declared package does not match the expected package

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
Fixes #388
This fixes the issue described in https://github.com/eclipse/eclipse.jdt.ls/pull/356#issuecomment-332025615
~~However, with these changes, DocumentLifeCycleHandlerTest.testNotExpectedPackage() and 
DocumentLifeCycleHandlerTest.testNotExpectedPackage2() fail on Mac, need to let the CI build this PR so we can see how Linux behaves.~~ fixed
=> Use *real* URI to find resources

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
=> Hover not working when browsing source code from .class files

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
Fixes #408 & https://github.com/redhat-developer/vscode-java/issues/232
=> Old version of gradle is used in VS Code

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
Also, avoid importing already existing Maven projects and trigger "Update project
configuration" asynchronously to reduce server startup response time.
When opening https://github.com/google/guava a 2nd time the server is ready in ~2-3 sec,
instead of 1min.
Fixes https://github.com/redhat-developer/vscode-java/issues/336
=> Don't force a workspace build on startup, since autobuild is on

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ImportTextEditConverter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/TextEditConverter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/OrganizeImportsOperation.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandlerTest.java
@fbricon @gorkem @aeschli 
This is the proposed changes for "Organize Imports". However, the change is still buggy. And there is another import related bug: https://github.com/redhat-developer/vscode-java/issues/253
It's hard to track the root cause for the issue of misalignment of change between JDT'textedit and vscode's workspace edit. Any insight on this issue?
=> Add organize imports

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Fixes https://github.com/redhat-developer/vscode-java/issues/352
=> Autocompletion overwrites following characters

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceExecuteCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
=> Initialize ExecuteCommandProvider for the server's capabilities

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java
when building the workspace, diagnositics of errors from default project will be ignored. Add these errors to logs for trouble shooting,
=> add logs for build workspace errors[default project]

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Removes the parent process check from LanguageServer. Changes the way main thread is stopped. Adjusts the shutdown and exit behaviour to match the protocol definition. fixes #378, #349
=> Remove parent process checks

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes #451 
Buildship creates project's preferences and saves them in Eclipse. It uses those preferences when opening a project in Eclipse which doesn't work in Java LS because buildship, for some reason, saves the preferences in the o.e.buildship.ui plugin that isn't used in Java LS. This PR fixes the issue. 
It also works the following:
- disables autorefresh (it is off, by default, in Eclipse)
- saves the workspace properly when stopping Java LS so that the workspace isn't refreshed unless necessary
Opening the sagan project (https://github.com/spring-io/sagan) takes 40+ seconds on my machine. After applying the PR, it takes a few seconds to open it when doing that the second time.
=> improve startup performance for gradle projects in workspace

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
=> Add quickfix for unreachable ctach

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Fixes #483 
You can use the following:
```
JavaClientConnection clientConnection = JavaLanguageServerPlugin.getInstance().getClientConnection();
```
=> Make JavaClientConnection available to plugins

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/380
=> Renaming or creating a java file requires restart

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/394
The issue can be reproduced on Windows.
=> Cannot save file in UTF-8 correctly

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/TestVMType.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/392
There are two issues:
1) Eclipse JDT will always use a default VM Runtime if it exists.
If you start VS Code with JDK 8, Java LS will set JDK8 as a default VM and use it although you, after that, start Java LSP with JDK 9.
A workaround is to remove a workspace before starting VS Code - https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory
I have fixed this issue by setting a default VM based on the "java.home" property.
Maybe we would need to remove other JDKs defined in the workspace or add a JRE view. See https://github.com/redhat-developer/vscode-java/issues/237.
2) Intellisense (code assist) won't work if it takes more …
=> vscode intellisense failing when 2 jdks are on system

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Foo4.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandlerTest.java
Personally, I like 'Save Actions' very much in Eclipse, especially `Organize Imports` when save file. So I try to add this function to this language server. 
I think the best choice is to use LanguageClient's `willSaveWaitUntil` feature. I tried to register this feature dynamically, but failed. So, for now, I enabled `willSaveWaitUntil`  feature if the client support this feature during init stage.
I also submitted a pull request to `vscode-java`, in which an option `java.saveAction.autoOrganizeImports` is added.
=> Add auto organize imports function to save action.

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
temporary link to CI build of m2e 1.9.0, in order to check https://github.com/redhat-developer/vscode-java/issues/391
Will switch to m2e 1.9.0 M5 once it's released.
=> Update m2e to 1.9.0.20180124-2208

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/projects/eclipse/hello/.classpath, org.eclipse.jdt.ls.tests/projects/eclipse/hello/test/foo/bar/AbstractTest.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/test/foo/bar/BaseTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
- Fixes slow performance when compiling/runnning against Java 9 (https://github.com/redhat-developer/vscode-java/issues/398)
- Fixes broken navigation in module-info.java (#501)
- Fixes broken hover in module-info.java (#397)
Perhaps more importantly, brings test classpath isolation to Maven and Eclipse projects \o/
=> Update TP to latest, pre-M5, Photon bits

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/406
Requires https://github.com/redhat-developer/vscode-java/pull/414
=> Provide an option to disable the 'auto build'

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/JavadocQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedMethodsQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedVariablesQuickFixTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/424
=> Sort the quick fix menu for imports in a order that makes sense

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/maven/unzipped-sources/META-INF/maven/unzipped-sources/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixes #539
It turns out exclusion patterns without the `**` suffix are not enough to actually exclude projects in case of Maven import 
=> Exclude **/META-INF/maven/** folders from import

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>
This PR proposes not to avoid all options from `FormattingOptions` to format the code.
It is needed for https://github.com/eclipse/che/issues/8572
=> Make it possible to apply all formatter options

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/schema/org.eclipse.jdt.ls.core.contentProvider.exsd, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ContentProviderManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ContentProviderManagerTest.java
Fixes #557
It's now each IContentProvider's responsibility to implement their own caching mechanism, if needed.
=> Remove problematic cache in ContentProviderManager

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
Adds a fix for the URI during workspace symbols. Previously what was happening is the response would be "file:/" with only one slash.
Fixes #561 
Signed-off-by: jpinkney <josh.pinkney@mail.utoronto.ca>
=> Fix the URI during workspace symbols

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/TextEditConverter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/AdvancedQuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
Fix for https://github.com/eclipse/eclipse.jdt.ls/issues/437
However, there is a bug from the VSCode side: https://github.com/Microsoft/vscode/issues/43878
@fbricon
=> Add quick fix for dead code.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
Fix the issue mentioned here: https://github.com/Microsoft/vscode/issues/43878
The end range is always be the same line as the start, which should not be the correct behavior. As this issue will cause multiple lines problems cannot be detected in the VSCode. 
@fbricon @gorkem
=> Fix the end range of the diagnostics.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/OrganizeImportsCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/OrganizeImportsCommandTest.java
If the client support workspace/applyEdit with this
change jdt.ls applies the imports directly
fixes #518
=> Apply TextEdits directly on organize imports

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
...else trigger an incremental build (if incremental build enabled).
See https://github.com/redhat-developer/vscode-java/issues/451
=> On workspace/didChangeConfiguration, only trigger a clean build if JVM changed

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/DidChangeWatchedFilesRegistrationOptions.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/FileSystemWatcher.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
Fixes https://github.com/eclipse/eclipse.jdt.ls/issues/583
We can remove the following lines in vscode-java:
workspace.createFileSystemWatcher('**/*.java'),
workspace.createFileSystemWatcher('**/src/**')
Maybe we could also add the remaining file watchers as a property.
=> Process non-java files

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/ExecuteCommandProposedClient.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ExecuteClientCommandTest.java
This is one half of a proposed protocol extension that allows language server to execute commands on the server. 
It requires another PR to implement support for handling the new `workspace/executeCommand` message on the client side.
This fits in with in the discussion at https://github.com/eclipse/eclipse.jdt.ls/issues/595
=> Experimental client-side command executions

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java
=> CodeLensHandlerTest.testGetCodeLensSymbolsForClass fails on Windows

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
fix `completionItem.data.uri`, adding missing `//` to `file:/` prefix
Signed-off-by: Pixy Yuan <pixy.bupt@gmail.com>
=> Fix completionItem URI

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/DocumentAdapter.java
Not sure how we can reach a state where the document is null while not being already closed.
I've added a couple null-checks, but no idea on how to test the fix.
Fixes #642
=> Prevent NPE in DocumentAdapter.close(). Fixes #642

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/FormatterManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/build.properties, org.eclipse.jdt.ls.tests/formatter resources/eclipse-java-google-style.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
Fixes #623 
Requires https://github.com/redhat-developer/vscode-java/pull/517
The PR imports the Eclipse formatter xml.
You can test it using attached eclipse-java-google-style.xml
It is necessary to add the following property:
```
"java.formatter.url": "<path_to_eclipse-java-google-style.xml>",
```
Since Java LS still uses the VS Code formatting options, you can also add:
```
"editor.tabSize": 2,
"editor.detectIndentation": false,
"editor.insertSpaces": true,
```
=> Expose formatter options

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
Fixes #569
Formatting is triggered when typing `}`, `;` or on new line.
Formats the current line or, in case a `}`  was typed, the previous
block.
=> Add on-type formatting support.

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/projects/maven/autovalued/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/autovalued/src/main/java/foo/bar/Foo.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
- adds m2e-apt to the server distro (requires CQ approval)
- ignores derived resources from didOpen/didChange/didSave calls, effectively removing diagnostics for those, as, after the server generates those files, the client detects changes, so sends textedits to the server to re-modify them, causing weird errors.
Fixes #128 
=> Adding annotation processing support

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixes #667 by 
1. Handle preexisting projects that can't be imported by m2e and delete the eclipse project before importing
2. Lock workspace when updating the workspace folders
=> Fix project initialization problems

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>
Adds new package to Export-Package group
- org.eclipse.jdt.ls.core.internal.corext.refactoring.reorg
It is needed for https://github.com/eclipse/che/issues/6748
=> Add some export packages

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/TestJavadoc.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentTest.java
JDT LS extension may require this package to construct the signature of a Java element.
=> Make javadoc and signature methods `public static` to call from JDT LS extensions

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/TextEditConverter.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
@fbricon 
This fixes the additional indentation issue for lambda conversion and other code action. Text cases are fixed.
=> Fix indentation issue when convert text edit.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/TypeParametersFix.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/ProblemLocation.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/TypeChangeCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertVarQuickFixTest.java
Fixes #696 and #697 
The #696 and #697 issues use the same code. That is the reason I have fixed them in the same PR.
=> Convert from type to 'var';Convert from 'var' to the appropriate type

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/LogHandler.java
=> logs always show the same timestamp

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/JavadocCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/228
=> Completing /** should generate Javadoc with params

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/projects/maven/salut-java10/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/salut-java10/src/main/java/org/sample/Bar.java, org.eclipse.jdt.ls.tests/projects/maven/salut-java110/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/salut-java110/src/main/java/org/sample/Bar.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
=> Update m2e to 1.9.1

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationCollector.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationToLocationMapper.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Foo.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Foo2.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Foo3.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/IFoo.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
java.lang.Object is treated as a special case. Because of its large type
hierarchy, implementation location is not computed from reading all
files. Instead a default location at 0,0 will always be returned.
Fixes #556
=> Add textdocument/implementation support.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>
'Remove unused local variable and all assignments' was added.
Related issue: https://github.com/eclipse/eclipse.jdt.ls/issues/769
@fbricon take a look please
=> Add quickfix 'Remove unused local variable and all assignments'

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/WorkspaceHelper.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
=> Lower severity of m2e's 'Project configuration is not up-to-date...' diagnostics

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
@gorkem @fbricon 
The force build on initialized will block the LSP protocol to wait for its response. And this action is not necessary to triggered every time when the auto build is true. 
Restore the auto building value will make building as a worker thread and response to the client quickly. 
With this change, eclipse.jdt.ls will match the performance of eclipse on import/reopen scenario.
=> Fix perf issue by preventing unnecessary building when open workspace.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/AbstractCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/AbstractMultiFix.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/CleanUpContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/CleanUpRequirements.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/ICleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/IMultiFix.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/LambdaExpressionsCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/LambdaExpressionsFix.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/MapCleanUpOptions.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/MultiFixMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/MultiFixMessages.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/PotentialProgrammingProblemsCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SerialVersionSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/FixCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/GetterSetterQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AnonymousClassCreationToLambdaTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
Fixes #658
Signed-off-by: Summer Sun <victoriasqq@gmail.com>
=> Port convert anonymous class creation to lambda expression from JDT.UI

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/ExecuteCommandProposedClient.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/SendNotificationTest.java
This PR adds the possibility to send notifications analog to executing client commands. Executing client commands can lead to deadlock between the client and jdt.ls because it requires to send a result back. A scenario is described in #719
=> Allow to send custom notifications

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
Provide dynamic registration for completion. 
With this change, we can avoid introduce this interface: https://github.com/eclipse/eclipse.jdt.ls/issues/613 and also make https://github.com/eclipse/eclipse.jdt.ls/issues/60 possible without conflict in an extensible way.
=> Add enable/disable completion option

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/hover/JavaElementLabels.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferencesTest.java
Closes: #780.
Signed-off-by: Akos Kitta <kittaakos@typefox.io>
=> GH-780: Added support for the hierarchical document symbols.

launch/jdt.ls.socket-stream.launch, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTEnvironmentUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
This PR includes an Eclipse launch configuration to start the JDT LS in debug mode. I found this approach useful when I had to develop JDT LS in Eclipse.
It also includes a tiny [`startConnection`](https://github.com/eclipse/eclipse.jdt.ls/compare/master...kittaakos:jdt-ls-launch-config?expand=1#diff-55f26b9037b6c92ad4701f61028ae2cdL251) modification, that is used only if the JDT LS was started from Eclipse in debug mode. Otherwise, we fall back to the well known original start logic.
Finally, a utility class to access the `CLIENT_HOST` and the `CLIENT_PORT` environment variables.
Signed-off-by: Akos Kitta <kittaakos@typefox.io>
=> Added a launch configuration for the JDT LS.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule/module1/childmodule/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule/module1/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule/module2/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule/module3/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupportTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/638
=> Cascade project configuration changes to child projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
=> Ensure out-of-date messages have warning severity

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule/module1/childmodule/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule/module1/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule/module2/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule/module3/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
=> Ensure project and pom.xml diagnostics are properly reset

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JsonRpcHelpers.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/HighlightedPosition.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticHighlighting.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticHighlightingDiffCalculator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticHighlightingPresenter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticHighlightingReconciler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticHighlightingService.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticHighlightings.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticToken.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticHighlightingTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
This PR contains the following change:
- Enables the semantic highlighting for the JDT LS.
- Switches from LSP4J `0.4.0` to `0.5.0`.
Static:
Member vs. Parameter:
Deprecated:
Auto (un)boxing:
Closes #715.
Signed-off-by: Akos Kitta <kittaakos@typefox.io>
=> GH-715: Implemented the semantic highlighting support.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
Fixes redhat-developer/vscode-java#669
=> [regression] Maven diagnostics show up and disappear on save

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/CUCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/JavadocTagsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/RenameNodeCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/JavadocQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/OrganizeImportsActionTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractVariableTest.java
@fbricon  The original organize imports delegate commands is not deleted yet since it is used by other client and provide organize in folders/workspaces functionalities. 
Fixes #845
=> Add source CodeAction support for organize imports.

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/GenerateGetterSetterOperation.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/codemanipulation/GenerateGetterSetterOperation.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/IProposalRelevance.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ActionMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ActionMessages.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/AbstractSourceTestCase.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/GenerateGetterAndSetterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
Add a Source Action to bulk generate Getters and Setters for all possible fields.
Issues: https://github.com/eclipse/eclipse.jdt.ls/issues/163, https://github.com/redhat-developer/vscode-java/issues/597
=> Bulk generate getter and setter

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/BuildPathCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/BuildPathCommandTest.java
This is for feature https://github.com/redhat-developer/vscode-java/issues/619, marking a folder as source root is helpful for the standalone java file support and simple eclipse project. Currently i disabled the operation on maven/gradle project because the user could manage this kind of source path through pom.xml and build.gradle.
Below is the basic feature:
- Add Folder to Java Source Path (context menu)
- Remove Folder from Java Source Path (context menu)
- List all Java source paths (command palette)
See the peer PR https://github.com/redhat-developer/vscode-java/pull/724
=> Add commands to add/remove/list the project's source path

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaCodeActionKind.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractMethodQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertVarQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedMethodsQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedVariablesQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractVariableTest.java
Refactoring testing code to check refactoring kinds revealed some regressions that were hidden by some faulty tests. See #907 and #908
=> map extract refactorings to code action kinds

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetector.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetectorTest.java
Signed-off-by: Poytr1 <pengcheng.xu@elastic.co>
This PR is related to https://github.com/eclipse/eclipse.jdt.ls/pull/836
When I was trying to import a project which has a circular link to parent dir or current dir, the whole project failed to be initialized with an Exception threw by language server. Here is the log snippet:
```
!ENTRY org.eclipse.jdt.ls.core 4 0 2018-12-26 19:11:45.517
!MESSAGE Initialization failed 
!STACK 1
Java Model Exception: Core Exception [code 0] Failed to scan /Volumes/android/WORKING_DIRECTORY
....
!MESSAGE Failed to scan /Volumes/android/WORKING_DIRECTORY
!STACK 0
java.nio.file.FileSystemLoopException: /Volumes/android/WORKING_DIRECTORY/external/autotest/venv/autotest_lib
at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:294)
at …
```
=> Fix bug: fail to import project containing file tree with a circular link

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/DefaultProjectBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/UpdateClasspathJob.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JavaProjectHelper.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractInvisibleProjectBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
... in the root directory of  standalone files / invisible projects
- a file watcher on lib/** is added for invisible projects
- source for foo.jar is automatically detected if there's a
foo-sources.jar in the lib/ folder
- multiple file events are handled so that classpath modifications are
minimized
=> Automatically detect jars in lib/ folder

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java
Fixes https://github.com/redhat-developer/vscode-java/issues/789
Java doesn't call the finalize method when terminating a process. Because of that, when Java LS isn't used, it creates a lot of zombie processes on Windows.
See https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java#L64
Steps to reproduce:
- start VS Code and Java LS, but don't use it
- download https://download.sysinternals.com/files/Handle.zip and unpack it
- call the following command several times:
```
handle64 -s -p <Java_LS_pid> | grep Process
```
You will see that the number of processes is constantly increasing.
The solution is to call System.gc(). We can also call it on Linux and Mac because it runs when Java LS isn't active. …
=> Consumes lots of memory over time

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaCodeActionKind.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/OverrideMethodsOperation.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OverrideMethodsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ActionMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ActionMessages.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/OverrideMethodsTestCase.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
It implements the source action `Override/Implement Methods` with prompt ui.
Closes #900
=> Source Action: Override/Implement Methods with prompt

README.md
=> Remove duplicate feature (Javadoc hovers) from README.md

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.tests/projects/singlefile/lesson1/samples/Foo.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
Fixes redhat-developer/vscode-java#750
Follow the priority below to infer the package name for an empty java file.
1. Try to search whether a nearby non-empty java file exists in the same directory. If so, use the nearby non-empty file to compute the package name.
2. Try to find whether the java file is under `src` folder. If so, compute the package name beginning from the `src` path.
3. Compute the relative path with the workspaceRoot and use that as the package name.
=> Improve the mechanism to resolve the package name for empty java file

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java
Signed-off-by: Poytr1 pengcheng.xu@elastic.co
This PR fixes: https://github.com/eclipse/eclipse.jdt.ls/issues/963
=> Fix bug: check null for location in fixLocation method

CHANGELOG.md, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JVMConfiguratorTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
Fixes regression where invisible projects always compile with Java 12 when the 
preview-feature flag is enabled. See redhat-developer/vscode-java#801
=> Only enable preview flag if JVM supports it

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ResourceUtilsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractInvisibleProjectBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
- don't create filewatcher with devices (prefix with ** instead of
device)
- fixed filewatcher on .settings/
- avoid generating overlapping filewatchers
=> Fix jar detection on windows

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationsHandler.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Foo4.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationsHandlerTest.java
=> An exception occur when peek implementation

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java, org.eclipse.jdt.ls.tests/projects/maven/salut/src/main/java/org/sample/Bar.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
One noticeable change is that, for methods, we no longer return
CompletionItemKind.Function but CompletionItemKind.Method instead.
Fixes #1012
=> Use proper symbols for interfaces, enums, enum values and constants

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
=> Typing () returns wrong set of signatures (textDocument/signatureHelp)

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
Fixes #982 
Projects: 
- https://github.com/spring-projects/spring-boot
- https://github.com/apache/incubator-dubbo
- https://github.com/apache/incubator-druid
- https://github.com/eclipse/che
Test cases:
- import the 1st time (no existing workspace, empty maven repository, 1GB)
- import the 1st time (no existing workspace, empty maven repository, 2GB)
- import the 1st time (no existing workspace, full maven repository, 1GB)
- import the 1st time (no existing workspace, full maven repository, 2GB)
- reopen the same folder (existing workspace, full maven repository, 1GB)
- reopen the same folder (existing workspace, full maven repository, 2GB)
vsix: https://raw.githubusercontent.com/snjeza/vscode-test/master/java-0.43.2.vsix
=> Batch Maven project imports to reduce memory consumption

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/GenerateGetterSetterOperation.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/GetterSetterCorrectionSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateAccessorsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/GenerateGetterAndSetterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateAccessorsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
In the quick fix and source action for getter and setter, reuse the global user settings to control whether generating JavaDoc.
Relates to #872
=> Use user settings to control generating comments for getter and setter

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
=> Signature help does not work for constructors

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/875
Requires https://github.com/redhat-developer/vscode-java/pull/917
=> Optionally disable loading gradle from gradle wrapper

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
=> Disabling the gradle wrapper doesn't work in some cases

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HashCodeEqualsHandlerTest.java
=> HashCodeEqualsHandlerTest.testGenerateHashCodeEquals_useInstanceof() fails

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
Signed-off-by: Poytr1 <pengcheng.xu@elastic.co>
When we call `java/didChangeWorkspaceFolders`, we may remove some workspaces. However, when the removed workspace is still in the initialization phase, the initialize/update workspace job is still at WAITING status or RUNNING status. We have not canceled these jobs, and they will still execute in the background, occupying resources. The potential problem is that if I delete this workspace, I might get an exception from these jobs.
This PR is used to add a new family(rootpaths) for the initialize and update jobs, so that you can find these background workspace jobs for initializing the workspace based on removed rootpaths and try to cancel them.
@fbricon How do you think about this?
=> Cancel init or update workspace job of removed rootPaths

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractConstantRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractTempRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/structure/CompilationUnitRewrite.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/RefactoringCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/CUCorrectionCommandProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ExtractProposalUtility.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/CodeActionUtil.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/AbstractSourceTestCase.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AdvancedExtractTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/GetRefactorEditHandlerTest.java
Fix redhat-developer/vscode-java#333
The jdt.ls will return the rename position for the new extracted node, and it requires the client side to consume it to pop up the rename box.
=> Auto rename the extracted node generated by the refactoring 'extract to variable/constant/method'

org.eclipse.jdt.ls.core/schema/org.eclipse.jdt.ls.core.delegateCommandHandler.exsd, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceExecuteCommandHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceExecuteCommandHandlerTest.java
Signed-off-by: BoykoAlex <aboyko@pivotal.io>
Fixes #1084 
Commands registered via `org.eclipse.jdt.ls.core.delegetaeCommandHandler`can have an optional `static` boolean attribute. If the attribute is `true` command is considered as "static" command registration of which is independent of configuration settings, i.e. the command is registered always.
"Static" commands are therefore always registered at the JDT LS initialization stage. While other commands that depend on configuration settings will be registered via dynamic capability registration if it is supported by the client (just like they were registered before).
=> Register static commands at initialization

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java
It seems that here the `Arrays.equals()` is intended to be used, since the original condition in the if-block will always return true.
=> Prevent aggressive classpath updates when jars don't change

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java
Signed-off-by: Yan Zhang <yanzh@microsoft.com>
When I was passing a simple `InsertEdit`, this method failed to process the edit as it had no children.
- For `MultiTextEdit`, process its children; otherwise process the edit itself.
- Remove the zero-length check as it's already guarded by the for-loop. There's also no NPE risk as `TextEdit.getChildren()` always returns a non-null array.
=> Fix ChangeUtil for non-MultiTextEdit conversion

.gitignore, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Signed-off-by: Nicholas Gates <ngates@palantir.com>
=> Add additional Gradle preferences

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SelectionRangeHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/projects/maven/salut/src/main/java/java/Foo4.java, org.eclipse.jdt.ls.tests/projects/maven/salut/src/main/java/org/sample/Foo4.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SelectionRangeHandlerTest.java
=> Support textDocument/selectionRange

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ChangeUtilTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractFieldTest.java
Currently for each type of `Change`, there's a corresponding public method located in `ChangeUtil`, which is not elegant or consistent. E.g.
* void convert**CompositeChange**(**Change** change, WorkspaceEdit edit) 
* void convertResourceChange(ResourceChange resourceChange, WorkspaceEdit edit) 
* void convertTextChange(WorkspaceEdit root, **IJavaElement** element, TextChange textChange)
* etc.
Anytime you want to convert a `Change` to a `WorkspaceEdit`, you have to explicitly call the corresponding utility based on the type of Change. 
This PR refactors the utility and use `ChangeUtil.convertToWorkspaceEdit(Change change)` as the **only** entry to convert `Change` to `WorkspaceEdit`.
=> Refactor ChangeUtil: universal API converting Change to WorkspaceEdit

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/OrganizeImportsActionTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AdvancedExtractTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractConstantTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractFieldTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractVariableTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/GetRefactorEditHandlerTest.java
See https://github.com/redhat-developer/vscode-java/issues/986
=> Properly filter code actions according to context.only values

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/AdvancedQuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InvertConditionTest.java
Signed-off-by: sheche@microsoft.com <sheche@microsoft.com>
This PR is to enable the fix: `invert conditions`. Some of the GIF for illustration:
Invert operators:
Invert method calling
Invert variable
=> Enable the 'Invert conditions' fix

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/AbstractFoo.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/FooService.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationsHandlerTest.java
Fix #1098
If the find implementation happens at the position of method or type declaration, keeps old behavior.
If it happens at the position of method/type invocation, then follows the rules below to determine whether to include the definition to the result.
- If the hovered element is an unimplemented member (abstract or interface) and no implementations are found in the workspace, then include the element definition to the result. 
- If the hovered element is non abstract or interface, then always include the element definition as the first result.
=> Find implementation intelligently fall back to find definition

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JSONUtility.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JdtDomModels.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MoveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/MoveHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AdvancedExtractTest.java
It covers two move scenarios mentioned in issue https://github.com/eclipse/eclipse.jdt.ls/issues/1089.
- Move Instance Method - The possible destinations are the object fields and method parameter objects which the instance method is able to access, and these objects must be source classes defined by your project.
- Move static member - The destination is probably any source class.
=> Support move instance method and static member

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
When testing an instance of the server running locally in VSCode, I noticed quite a few error messages like the following from the node client:
I tracked it down to this handler. Making this update to return an empty list instead, which makes the VSCode client happy. I've updated the tests.
=> NavigateToDefinitionHandler should not return null

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
Fixes #1062
Eclipse Preference: Window -> Preferences -> Java -> Compiler -> Errors/Warnings -> Annotations -> 'Unhandled token in @SuppressWarnings' = 'Ignore'
This PR simply sets the preference to 'Ignore', in the case that someone wants the option to
turn it back on another PR will be needed to create a preference
=> Ignore Unsupported SuppressWarning message

org.eclipse.jdt.ls.core/.classpath, org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/build.properties, org.eclipse.jdt.ls.core/pom.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2MarkdownConverter.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javadoc/AbstractJavadocConverterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2MarkdownConverterTest.java
This PR uses the next version of Remark which fixes issues with tables converted to markdown.
Some issues this fixes are:
1) Tables without a header
2) Tables with an improperly defined header (no THEAD tag)
3) Some table indentation issues (fixed in JDT.ls)
=> Updated Remark 1.0.0 -> 1.2.0 for Markdown Tables

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/TypeFilter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SimilarElementsRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/OrganizeImportsCommandTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/710
Requires https://github.com/redhat-developer/vscode-java/pull/1059
=> Exclude certain packages from autocomplete/autoimport

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/AdvancedQuickAssistProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactoringCorrectionCommandProposal.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AnonymousClassToNestedTest.java
Apologize that I forgot to create a new issue for this feature in advance. I just filed one here: #1177 
Simple case:
A more complicated one:
client side PR: https://github.com/redhat-developer/vscode-java/pull/1060
=> Support refactoring: Convert anonymous class to nested

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.tests/projects/eclipse/classpath/.project, org.eclipse.jdt.ls.tests/projects/eclipse/classpath2/.classpath, org.eclipse.jdt.ls.tests/projects/eclipse/classpath2/.project, org.eclipse.jdt.ls.tests/projects/gradle/simple-gradle/build.gradle, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerTestPlugin.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/634
The issue can be reproduced in Eclipse. The reason for the issue is that JDT uses the project's path as a source folder when the project doesn't contain .classpath.
The PR works in the following way:
1) if a user deletes .classpath, Java LS will delete the Java nature and builder from the project
2) EclipseProjectImporter doesn't import those directories that don't have .classpath
=> Stop creating files in bin directory

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/VisibilityQuickFixTest.java
=> Quick fix implementation for method invisibility

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java
Resolve #1180 
- extractVariable
- extractVariableAllOccurrence
- extractConstant
- extractMethod
- extractField
- convertVariableToField
- invertVariable
=> Use sequence rank to get the first element in position group

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fix #1162
And it looks like this when it's running:
=> Support Diagnostic Tag

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JVMConfiguratorTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
See  https://github.com/redhat-developer/vscode-java/issues/1086
=> Only enable preview features for the latest available JDK

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTest.java
=> Refresh with one depth when calling JDTUtils.getFileOrFolder()

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetector.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetectorTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1084
=> Include folders to import

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
I find there's inconsistency of definition and call. 
All the other references can be seen below:
=> Make PreferenceManager.initialize() non-static

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetUtilsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Mitigate #1220 
In [jdt.ui](https://github.com/eclipse/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui/templates/default-templates.xml), `for_array`, `while`, `do_while` and `if` have the `selection` placeholder.
Besides these snippets, I also add the `$TM_SELECTED_TEXT` into `ifnull` and `ifnotnull`
=> Add text selection support in code snippet

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticHandlerTest.java
Fix #1219 
Adds faded effect to unused code and looks like this when running:
=> Report unused code as unnecessary

README.md
MS Paint IDE is a less-than-conventional IDE that allows you to program in Paint via an OCR. The IDE has LSP support and uses Eclipse's Java language server for the Java language.
=> Added MS Paint IDE to README

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnnecessaryCastQuickFixTest.java
Fixes issue #165
To test you need to add the preference "org.eclipse.jdt.core.compiler.problem.unnecessaryTypeCheck=warning" to the org.eclipse.jdt.core.prefs settings file.
This will enable the warning to be shown in the ide.
And then refer to the test in this PR to use to re-create it.
=> Adds quick fix for unnecessary cast

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToTypeDefinitionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
This brings in Maven 3.6.2, which might help with https://github.com/redhat-developer/vscode-java/issues/1103
=> Update m2e to 1.14

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
Part of workitem #1136 .
Code actions `Convert to static import` and `Convert to static import (replace all occurrences)` should be of `refactor` kind. See https://github.com/eclipse/eclipse.jdt.ls/pull/1239#issuecomment-549672202
=> Change code action 'Convert to static import' to refactor kind

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/FixCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
Part of workitem #1136 
Although it's implemented via `FixCorrectionProposal`, the conversion bewteen lambda and anonymous class should be of `refactor` kind, instead of `quickfix`.
This PR adds a constructor for `FixCorrectionProposal` allowing to specify CodeActionKind, and sets correct kind for the conversion actions.
=> Change lambda-anonymous class convertion code actions to 'refactor' kind

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ChangeCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
Part of workitem #1136 
According to LSP, the conversion between resolved type and `var` should be of kind `refactor`, instead of `quickfix`. 
This PR 
* adds a setter for CodeActionKind in the base class.
* corrects the CodeActionKind of the action.
=> Change var conversion actions to 'refactor' kind

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/774
One thing that can be improved is the message "Add final", but that relies on
a change from jdt code.
=> Add final modifier where possible

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
=> Delete unrelated gradle projects during initialization

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
If client advertises `CodeActionLiteralSupport`, using that for
`java.apply.workspaceEdit` would allow clients to use a generic
algorithm, instead of being forced to provide a special case for jdt.ls.
Fixes #376
This actually tries to revive #1059. Differences compared to #1059:
- Rebased onto latest master
- Checking `isSupportedCodeActionLiteral()` instead of `isWorkspaceApplyEditSupported()`.
- This made me add `isSupportedCodeActionLiteral()` and I took the chance to fix the docstring from a previous faulty copy/paste.
=> Take advantage of CodeActionLiteral client capability

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
Fix redhat-developer/vscode-java#1142
=> Call corresponding code action processor according to base kind

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
=> Sort each kind of actions by relevance

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fix redhat-developer/vscode-java#1152
When rename or delete a package (or folder), the **didChangedWatchedFiles** event only reports the folder is deleted, so **WorkspaceEventsHandler** won't clean up the children's diagnostics.  **WorkspaceDiagnosticsHandler** has the ability to recursively visit the all deleted resources, it needs make sure to clean up all stale diagnostics state.
=> Should update the diagnostics for the deleted resource and it's children

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java, org.eclipse.jdt.ls.tests/projects/maven/salut/src/main/java/org/sample/TestBreakContinue.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1145
=> jump to definition on break/continue

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/StaticAccessQuickFixTest.java
Fixes #439
Could not re-create IndirectAccessToStaticField and IndirectAccessToStaticMethod on Eclipse or JDT.ls
=> Adds quickfix to correct access to static elements

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManagerTest.java
=> Use ProgressReporter to monitor initialization jobs

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
**WorkspaceDiagnosticsHandler.java** is listening to resource change event, any time the build job changes (add or remove) the problem markers of the resources under the target project, the handler will sync diagnostics to the client. So it's unnecessary for the BuildWorkspaceHandler to clean up the project level diagnostics before building.
=> No need to publish diagnostics in BuildWorkspaceHandler

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetUtilsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ReorgQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetectorTest.java
Fixes #1262 
The PR introduces the following changes:
- javaImportExclusions uses LinkedList
- the SnippetUtilsTest, ReorgQuickFixTest, AbstractProjectsManagerBasedTest tests restore the preferenceManager property
=> BasicFileDetectorTest.testInclusions* fail randomly

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/UpdateClasspathJob.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java
=> Refactor UpdateClassPathJob to provide a more general interface 

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ReorgQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateAccessorsActionTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsActionTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringActionTest.java
Another attempt at solving #376. Github seems confused about the state of #1256, so I decided to open a new one.
Changes compared to #1256:
- The error reported by @fbricon should be fixed now.
- There's no more `isSupportedCodeActionLiteral()` because we should always be checking the code action kind.
- In both places where `isSupportedCodeActionLiteral()` was used in #1256, the `isSupportedCodeActionKind(kind)` was checked a few lines above, so the actual functional changes of the PR could be slightly simplified (compared to #1256).
- Correctly handling code action literals meant that there's a lot of places where the code basically does:
- Pull `Command` out of `Either<Command, CodeAction>`.
- If that `Command` is not `null` to thing A.
- Else do thing B.
Fixes #376
=> Take advantage of CodeActionLiteral client capability - Second attempt

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/maven/salut3/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupportTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1102
Requires https://github.com/redhat-developer/vscode-java/pull/1109
=> Add preference to update snapshots for Maven projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
Above is profiled by JProfiler when I complete for letter 'S'. According to the result, `getRawLocationURI()` is not cheap. This PR should improve the perf a little bit.
=> Remove dup call of getRawLocationURI()

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SortTextHelper.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
TextEdits need to be computed during the `completion` call, but this can be extremely slow when a large number of results is returned. This PR tries to mitigate the issue by returning partial result lists and marking the results as incomplete. Smaller payload means computing Textedits is now more affordable. Hopefully the UX should be improved as well since completion queries will return faster too.
The number of completion results is configurable with the `java.completion.maxResults` preference (defaults to 50). Setting 0 will disable the limit and return all results. Be aware the performance will be very negatively impacted as textEdits for all results will be computed eagerly (can be thousands of results).
Fixes #465
=> Limit completion results

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/UpdateClasspathJob.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
This PR implements the referenced libraries support in server side, as described in https://github.com/eclipse/eclipse.jdt.ls/issues/1257#issuecomment-552237461.
It contains following modifications:
* Add a preference `java.project.referencedLibraries`.
* Implement a glob-based binary searching with basic optimizations.
* UpdateClasspathJob now fully adopts `include-exclude-sources` pattern.
* Use `didChangeWorkspaceFiles` to watch include globs, along with watcher listening to preference change. 
Pitfalls of moving to the server:
* Java does not has a glob library that can rival `node-glob`. There's even not a library that supports searching based on either absolute or relative path. This PR implements basic optimizations from `node-glob`: group the globs by prefix, and use prefix base …
=> Implement referenced libraries support in language server

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java
According to the Java 8 Stream specification:
> A Stream should be operated on (invoking an intermediate or terminal stream operation) only once. A Stream implementation may throw IllegalStateException if it detects that the Stream is being reused.
So multiple use of `excludeResolved` may cause following exception:
> IllegalStateException: stream has already been operated upon or closed.
Sorry for my fault of being not familiar with this Java feature...
=> Fix exception caused by misuse of java.util.stream.Stream

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1157
Requires https://github.com/redhat-developer/vscode-java/pull/1199
=> Add buildship offline mode preference

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/hover/JavaElementLabelComposer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java, org.eclipse.jdt.ls.tests/projects/maven/aspose/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/aspose/src/main/java/org/sample/TestJavadoc.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1217
=> Intellisense not work on close source jar

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/RuntimeEnvironment.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/fakejdk2/11a/release, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JVMConfiguratorTest.java
Fixes #1307 
Requires https://github.com/redhat-developer/vscode-java/pull/1207
=> Provide preference mapping for Java Execution Environments -> Runtimes

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java
This PR fixes a bug reproduced by following setting:
```json
"java.project.referencedLibraries": {
"include": [
"....",
"...."
]
}
```
where there's no `exclude` field set in the setting. This will cause the language server to use the fallback default setting (`lib/**`). This bug does not affect the shortcut array pattern (`"Libraries": [...]`).
The absence of `sources` field does not introduce bug since it won't raise NPE problem, but we also add a default value to it to make sure all the fields in `ReferencedLibraries` is initialized.
`include` field is not gotten with a default empty value, since `include` field is required, and if not provided, just use the default `lib/**`.
=> Add default value to reference libraries' exclude and sources when importing

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/RedundantInterfaceQuickFixTest.java
=> Add quickfix for redundant interface

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/JavaApplicationLaunchConfiguration.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/JavaLaunchConfigurationInfo.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/projects/gradle/multi-module/build.gradle, org.eclipse.jdt.ls.tests/projects/gradle/multi-module/client/src/main/java/Client.java, org.eclipse.jdt.ls.tests/projects/gradle/multi-module/server/build.gradle, org.eclipse.jdt.ls.tests/projects/gradle/multi-module/server/src/main/java/Server.java, org.eclipse.jdt.ls.tests/projects/gradle/multi-module/settings.gradle, org.eclipse.jdt.ls.tests/projects/maven/modular-project/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/modular-project/src/main/java/modular/Main.java, org.eclipse.jdt.ls.tests/projects/maven/modular-project/src/main/java/module-info.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupportTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupportTest.java
This PR is to enable the SonarLint Java support in VS Code.
The context background can be found here: https://github.com/SonarSource/sonarlint-vscode/pull/28
Related PR for VS Code client: https://github.com/redhat-developer/vscode-java/pull/1212
There is one issue that the classpath resolved for Gradle project will always contains test entries no matter the `excludingTests` is set to `true` or `false`. 🤔
> Note: Please do not merge it until the design is tested and verified. The discussion is [here](https://github.com/SonarSource/sonarlint-vscode/pull/28).
=> Add APIs to get classpaths and settings

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
It's a first step for https://github.com/redhat-developer/vscode-java/issues/1257
This PR enables IntelliCode to fetch the whole completion item list, it 
1 ) adds the getter of `proposals`.
2) moves calculation of replacement texts into method `toCompletionItem`.
=> Expose proposals for 3rd-party extensions

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes #1354 and https://github.com/eclipse/che/issues/16051
This PR can be tested in the following way:
```
git clone https://github.com/che-samples/console-java-simple
cd console-java-simple
rm -rf .classpath .settings/ .project bin/  ~/.gradle/ .gradle/
code .
```
=> Update buildship to 3.1.4.v20200211-2258-s

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Change `computeAsync` to `computeAsyncWithClientProgress` when executing `build workspace`.
Given the building task may take some time to execute, this could make the client print the trace if the server trace is turned on.
> _Also fix a type reference in JavaDoc_
=> Build workspace action can report progress to client

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
enabled by updating m2e to 1.15.0.20200226-2003
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=560544
and https://github.com/takari/aether-connector-okhttp/pull/26
=> Parallel downloads of jars, for Maven projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
=> BadLocationException and diagnostic with negative line number send to client

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Uses https://download.eclipse.org/lsp4j/updates/releases/0.9.0/
Reapplies #1373
Fixes #1382
Also-by: Fred Bricon <fbricon@gmail.com>
=> Use stable lsp4j 0.9.0 release

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractInvisibleProjectBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
Fix redhat-developer/vscode-java#1275
When opening a partial folder from a maven/gradle project, because the classpath is incomplete, will report syntax errors only.
=> enable syntax mode when importing a partial folder of maven/gradle project

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java, org.eclipse.jdt.ls.tests.syntaxserver/projects/maven/salut4/src/main/java/java/Bar.java, org.eclipse.jdt.ls.tests.syntaxserver/projects/maven/salut4/src/main/java/java/Foo.java, org.eclipse.jdt.ls.tests.syntaxserver/projects/maven/salut4/src/main/java/pack/IFoo.java, org.eclipse.jdt.ls.tests.syntaxserver/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxServerTest.java
Currently hovering at a type doesn't work at syntax server, see https://github.com/eclipse/eclipse.jdt.ls/pull/1386#issuecomment-600872477. The reason is the hover handler uses search engine to validate whether the type is resolved. However, the syntax server disabled search engine so that no result is returned. 
Given syntax server is for speeding up responsiveness, IMO, returning a non 100% accurate result is acceptable. I would prefer to skip the validation step for syntax server.
=> Make syntax server support hovering over a type

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/TypeProposalUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/OrganizeImportsCommandTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/OrganizeImportsActionTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
See https://github.com/redhat-developer/vscode-java/issues/964
Requires https://github.com/redhat-developer/vscode-java/pull/1374
=> organize imports with the asterisk (*) wildcard character

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/ITokenModifier.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokenManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokens.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensLegend.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/TokenModifiers.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/TokenType.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommandTest.java
This PR is about [Semantic Highlighting](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview). VS Code has already support to register providers via its APIs, LSP proposal is in progress, but it's not yet part of LSP for the moment. 
In this PR, a delegate command to respond to the semantic token request, before it's merged into LSP in the coming version. 
Basically the LS tells clients a list of encoded tokens and the legend, and then client is reponsible for  applying the tokens with proper textmate scopes and related styles. 
Two token types `variable` and `method` are supported.
Token modifiers include `public`, `private`, `protected`, `abstract`, `final`, `static`, `deprecated`
Below is how it looks in vscode after applying styles for some modifiers:
* **static**: …
=> Support semantic tokens

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AssignToVariableRefactorTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/MissingEnumQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/RedundantInterfaceQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsActionTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1358
=> Add 'Generate constructor' option to 'Show Fixes' options for fields

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommand.java
Fix https://github.com/microsoft/vscode-java-dependency/issues/253
This PR ensures that the java model is up-to-date when calculation semantic tokens.
=> wait for lifecycle jobs before calc semantic tokens

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
When active java element changed( e.g. did open a new file), the cached `fAST` was out-of-date, thus  `SharedASTProvider.getAST(...)` would return an wrong ComplilationUnit.
=> clean out-of-date fAST before updating new fActiveJavaElement

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
=> CompletionHandlerTest.testStarImports fails randomly

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/TokenModifiers.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/TokenType.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommandTest.java
References:
[Semantic-Highlighting-Overview#token-classification](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#token-classification)
[specs for Semantic Highlighting ](https://github.com/microsoft/vscode-languageserver-node/blob/e5d7ad881b1a51b486e3f0e4aa0fbc25dad2be58/protocol/src/protocol.semanticTokens.proposed.ts#L18-L56)proposed in LSP 3.16
- wrong range for multiple tokens in one line
- semantic highlight for more token types
- types (highlighted as `type`)
- packages (highlighted as `namespace`)
- member variables (highlighted as `property`)
- following LSP proposal to use standard modifier `readonly` instead of `final`
=> refine semantic highlighting

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OrganizeImportsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/AdvancedOrganizeImportsHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1386
=> Organize Imports should resolve static imports as well

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandler.java, org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/InvalidInputRange.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandlerTest.java
Fixes #1419 
You can reproduce the issue using the following file:
```
public class Test {
void foo() {
char c = '';
}
}
```
=> Code folding is buggy

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/BuildPathCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenamePackageProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FileEventHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FileEventHandlerTest.java
=> Support refactoring package name

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommandTest.java
A fix for #1434 
Instead of highlighting each segment (SimpleName), the full qualified name of a package is highlighted together, e.g "java.util". 
import **java**(namespace).**util**(namespace).**List**(type);
3 tokens. So the dot between "java" and "util" is not highlighted as namespace.
import **java.util**(namespace).**List**(type);
2 tokens. dots within the full qualified name are also highlighted.
=> highlight QualifiedName together in packages

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java
=> jdt.ls shouldn't modify disk file when handling newly created or renamed files

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventHandlerTest.java
=> Discard the stale workingcopies that belonged to the deleted folder

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1426
You can test the following project: 
[gradle-test.zip](https://github.com/eclipse/eclipse.jdt.ls/files/4565942/gradle-test.zip)
VS Code settings: https://github.com/redhat-developer/vscode-java/issues/1426#issue-610003342
=> Use default JVM when importing gradle project

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/module1/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/module1/src/main/java/org/eclipse/App.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/module1/src/test/java/org/eclipse/AppTest.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/module2/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/module2/src/main/java/org/eclipse/App.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/module2/src/test/java/org/eclipse/AppTest.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventHandlerTest.java
Fix redhat-developer/vscode-java#1446
Root Cause:
The language server didn't watch on the project root folder, so it never receives the delete notification. Reload window will restore the existing project.
=> Delete project root folder should clean up the project

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/OrganizeImportsCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OrganizeImportsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Foo6.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandlerTest.java
=> Favorite static imports are ignored if server launched without advancedOrganizeImportsSupport:true

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ProjectUtilsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
See https://github.com/redhat-developer/vscode-java/pull/1457
=> Add a new command to get all Java projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
See: https://github.com/redhat-developer/vscode-java/pull/1464
Added a customized key in ProjectCommand.getProjectSettings() to get the VM installation path.
=> Can get VM installation path through ProjectCommand.getProjectSettings()

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/WrapperValidator.java
Fix a typo here. The value of `queueLength` was not assigned actually.
=> Correctly assign the queueLength in WrapperValidator

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/EventNotification.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/EventType.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ImportNewProjectsTest.java
require: https://github.com/redhat-developer/vscode-java/pull/1476
=> Send notification to the clients after importing projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/CompletionResultRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/ModelBasedCompletionEngine.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/ModelBasedSearchableEnvironment.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxInitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java, org.eclipse.jdt.ls.tests.syntaxserver/projects/maven/salut4/src/main/java/java/Completion.java, org.eclipse.jdt.ls.tests.syntaxserver/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxServerTest.java
=> Enable code completion for syntax server

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractConstantRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractFieldRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractTempRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/reorg/ReorgPolicyFactory.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/sef/SelfEncapsulateFieldRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/surround/SurroundWithTryCatchRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticHighlightings.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/pom.xml
Eclipse 4.16 bits are available from stable URLs. We can get rid of the java 14 patch dependency.
Some small changes in org.eclipse.jdt.internal.corext.refactoring.Checks require a few adjustments on the jdt.ls side.
=> Update to Eclipse 4.16

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/TokenType.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommandTest.java
part of https://github.com/redhat-developer/vscode-java/issues/1488
=> Support annotations in semantic highlighting

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
When I'm working for this PR: https://github.com/redhat-developer/vscode-java/pull/1484, I found that the test case `getClasspath` will randomly fail, see: https://travis-ci.org/github/redhat-developer/vscode-java/jobs/697117335
It's because if we try to get the classpath when the m2e is updating the projects, the return results might only contain the source classes without dependency jars. so I add a wait here.
=> Wait for jobs to complete when resolving the classpaths

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FindLinksHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java
=> Performance issue on large project

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseInitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.tests.syntaxserver/.settings/org.eclipse.core.resources.prefs, org.eclipse.jdt.ls.tests.syntaxserver/.settings/org.eclipse.jdt.core.prefs, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JVMConfiguratorTest.java
With the previous code, the java.home was initially prepared to be used as default VM, even though there was a default runtime set, potentially triggering unnecessary full builds
=> Optimize default VM management to avoid unnecessary project updates

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/AnonymousTypeCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
The goal is to improve performance of completion. Previously all text edits (including addtional ones which cost much time for imports) are caclulated in `CompletionProposalReplacementProvider#updateReplacement`. Now we decouple them,
`TextEdits` is calculated in "completion" stage, and `AdditionalTextEdits` in "resolve" stage
~Currenly it's not ready for review, just to show you how far it would improve.~
In the initial commit, I defer the calculation of imports (only for `TYPE_REF` candidates) to resolving stage. In spring-petclinic project, when I type "S" to complete, it takes:
* ~110ms for 50 items 
* ~330ms for all 3000+ items
(macOS, 2.9 GHz Dual-Core Intel Core i5, 8G RAM)
VS Code has already supported the so-called [Relaxed …
=> fill additionalTextEdits during completionItem/resolve 

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
brings dependency resolution markers to build.gradle files (See https://github.com/eclipse/buildship/issues/263)
=> Update Buildship to 3.1.5

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1532
=> Keep typing after the 1st tab when completing imports

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradlePreferenceChangeListener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1536
Requires https://github.com/redhat-developer/vscode-java/pull/1541
=> Expose the 'java.import.gradle.java.home' preference

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommand.java
This is a very simple change, code-wise. But it allows the client of the language server to request semantic tokens not only for source files, but also for class files in libraries. This is done by using the preexisting `JDTUtils.resolveTypeRoot(String uri)` method, which either resolves a source file or a class file into an `ITypeRoot` based on the request protocol (`file://...` or `jdt://...`).
=> Provide semantic tokens for class files

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java
This is what other servers(e. g. Rust Analyzer) do.
=> Use `,` as signature trigger char

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.tests/projects/eclipse/semantic-tokens/src/foo/Packages.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommandTest.java
Fixes redhat-developer/vscode-java#1545
I also added some more assertions to the test case for packages, to prevent future regressions.
=> Fix wildcard import semantic tokens

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/OverrideMethodsOperation.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateDelegateMethodsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/HashCodeEqualsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OrganizeImportsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OverrideMethodsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java
ASTProvider will cache the AST node for the active editor, should use it whenever possible.
Below is the profiling comparison on editing a Java file with 200 LOC.
- **Before**:  
The source action handlers will parse a new AST every time in the source action handler.  Most of time of getSourceActionCommands is on parsing AST node. And the time ratio between getSourceActionCommands and getCodeActionCommands is about 64%.
- **After**: 
Use ASTProvider to get AST node, and the time ratio reduces to 40%.
=> Use ASTProvider to getAST for source action handlers

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AnonymousClassToNestedTest.java
This PR is to make the refactoring **convert anonymous class to nested** more widely.
Before, the refactor will only show on the simple name `Foo` in the example below
```java
public class E {
public void test() {
Foo foo = new /**/Foo/**/() {};
}
}
```
Now we expand the its appearance to the whole class instance creation, which is the same behavior as the **anonymous to lamda** refactoring we have. (This refactor in IntelliJ also has a wider visibility)
```java
public class E {
public void test() {
Foo foo = new Foo(/*work as well*/) /*work as well*/{/*work as well*/};
}
}
```
=> Expose the anonymousToNest refactor more widely

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertVarQuickFixTest.java
Expand the exposure of the code actions: `convert var to resolved type` & `convert resolved type to var`.
Fix: https://github.com/redhat-developer/vscode-java/issues/1573
=> Can trigger 'convert var' and 'convert resolved type' on types

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java
Fixes part of redhat-developer/vscode-java#1597.
See redhat-developer/vscode-java#1632 for the second part of the fix.
This is done by getting the token line and column number directly from its compilation unit, rather than the document, which for whatever reason gets out-of-sync during frequent updates.
=> Fix semantic tokens offset due to document updates

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java
- Add support for code actions to generate sealed/un-sealed/final
modifiers on class with sealed direct super-class/super-interface
- Fixes #1555
=> Add code actions to support new Java 15 modifiers on permitted class.

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
m2e 1.17 now lazy loads a bunch of services, making its startup faster.
This helps jdt.ls shave a couple seconds off of its startup time as well.
﻿Signed-off-by: Fred Bricon <fbricon@gmail.com>
=> Embed m2e 1.17

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/ref/Apple.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/ref/Test.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandlerTest.java
Fixes #1548 
Requires https://github.com/redhat-developer/vscode-java/pull/1646
=> Find references to fields via getters/setters

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewCUProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java
- Add quick fix to generate proper type declaration for sealed type
- Fixed #1553
- Add testcase
A few notes :
- The type being created that is being permitted is given 'non-sealed' modifier as that seems the most permissive. Seemed reasonable given we use 'public' when creating the type already.
- Currently I haven't found a way to add the methods (if any) needing to be implemented. The issue is that to use the ASTRewrite API, the type must already exist and in this case it doesn't. I can have another look at how JDT UI does this but this is basically why all of 'constructNewCUChange(..)' deals with java language tokens as Strings, completely avoiding the AST.
=> Created type doesn't implement sealed interface.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InlineVariableTest.java
Just hide meanless refactor commands when a variable has no reference. The following gifs show the effect of this PR.
Before:
After:
=> Hide inline variable commands when no reference found

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes redhat-developer/vscode-java#1661
=> Fix method ref CompletionItemKind

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InlineConstantTest.java
hide meaningless refactor commands when a constant has no reference. The following gifs show the effect of this PR.
Before:
After:
=> Hide inline constant commands when no reference found

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertMethodReferenceToLambaTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1448
=> Convert a lambda expression to method reference

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1365
Requires https://github.com/redhat-developer/vscode-java/pull/1683
=> Add the java.configuration.maven.globalSettings property

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JdtSourceLookUpProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ResolveSourceMappingHandler.java, org.eclipse.jdt.ls.tests/projects/maven/quickstart2/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/quickstart2/src/main/java/quickstart/App.java, org.eclipse.jdt.ls.tests/projects/maven/quickstart2/src/test/java/quickstart/AppTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ResolveSourceMappingHandlerTest.java
To resolve #1202 
Other extensions can leverage the delegate command to get the source uri.
=> Support resolving stacktrace to uri

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/CompletionResultRequestor.java
=> Fix the compilation warning about 'Unlikely argument type for equals()'

launch/jdt.ls.remote.server.launch, launch/jdt.ls.socket-stream.launch, org.eclipse.jdt.ls.core/build.properties, org.eclipse.jdt.ls.core/logback.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.product/languageServer.product, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- Add 'org.eclipse.m2e.logback.feature' to target platform
- Add 'org.eclipse.m2e.logback' plugin to language server product
- This exposes the 'logback.configurationFile' system property through
which one can provide a logback configuration
A few notes on how this could work :
Suppose we want to log using standard out/err :
In : `/path/to/logback.xml`
```
<configuration scan="true">
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
<encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
<pattern>%date [%thread] %-5level %logger{35} - %msg%n</pattern>
</encoder>
</appender>
<root level="DEBUG">
<appender-ref ref="STDOUT" />
</root>
</configuration>
```
Now when launching JDT-LS, we need to set …
=> Improve tracing capability of m2e through m2e.logback.configuration.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InferSelectionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InferSelectionHandlerTest.java
Relates to redhat-developer/vscode-java#1680
=> Infer expressions if there is no selection range when extracting method

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Includes a fix to allow a project to resolve itself: https://bugs.eclipse.org/bugs/show_bug.cgi?id=568385
See https://github.com/redhat-developer/vscode-java/issues/1675
=> Update m2e to 1.17.0.20201112-0751

CHANGELOG.md
Note : The extra line between the title and the entries was always there, but accidentally removed by me 2 releases back, so re-introducing.
@fbricon
=> Add changelog for 0.65.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/dom/TypeAnnotationRewrite.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/RefactoringAvailabilityTester.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodAnalyzer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameLocalVariableProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewMethodCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDocLocations.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- https://eclip.se/568036 JavaModelUtil is1[678]OrHigher ->
is1d[678]OrHigher to avoid future conflicts
- https://eclip.se/567770 Remove upstreamed logic in
ASTResolving.getPossibleTypeKinds().
=> Update TP to use Eclipse 2020-12 M2.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
- Fixes #1611
- TokenScanner.readNext(..) throws CoreException with appropriate code
when EOF is reached instead of returning TokenNameEOF so the
exception logging should be suppressed in this case
=> Suppress CoreException thrown by TokenScanner when EOF reached.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1711
=> Java LS crashes on WSL Alpine

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java
When the language server is just finding valid expression, `ExtractMethodRefactoring.checkInitialConditions()` has no need to do some initialize methods, in some corner cases such as working on a large Java file with many duplicate methods, this may affect the performance of `inferSelection`. 
This PR is to remove the unnecessary processes.
=> Improve the performance of inferSelection

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InferSelectionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InferSelectionHandlerTest.java
Relates to redhat-developer/vscode-java#1717
Add support to `extractVariable` In `inferSelectionSupport` capability, making it possible to infer selections if there is no selection range when extract to variable.
Signed-off-by: Shi Chen chenshi@microsoft.com
=> Support inferSelection when extract to variable

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InferSelectionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InferSelectionHandlerTest.java
Relates to redhat-developer/vscode-java#1721
Add support to `extractField` In `inferSelectionSupport` capability, making it possible to infer selections if there is no selection range when extract to field.
Also add a field `params` in `SelectionInfo` to support send scope information from the server to the client.
To keep the consistency, also rename `isExtractMethodInferSelectionSupport` to `isExtractMethodInferSelectionSupported` and change some invocation about extracting method.
Signed-off-by: Shi Chen chenshi@microsoft.com
=> Support inferSelection when extract to field

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/LogHandler.java
There is no way get INFO logging level messages besides setting the log level to ALL.
This PR allows that. In my case, I need to listen to the ">> build jobs finished" and others.
=> Add support to INFO log level

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
- TimeoutException can be thrown for the same reasons as
UncheckedTimeoutException and should not be logged
- Resolves #1624
=> Treat TimeoutException the same as UncheckedTimeoutException.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
Root cause is that the found container may be an `IFolder`(linked folder for invisible project) instead of an `IJavaElement`, then calling `JavaCore.create()` will get a `null` result
fix https://github.com/redhat-developer/vscode-java/issues/1735
=> Get the project from the linked folder uri

CHANGELOG.md
@fbricon , @testforstephen 
Let me know if there's any additonal changes we're waiting on.
=> Add changelog for 0.67.0

.gitignore, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.tests/projects/maven/salut5/proj/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1698
The issue happens because the LocalProjectScanner class ignores the java.import.exclusions property and always scans the whole directory.
=> Enhance MavenProjectImporter to stop scanning the specified exclusion list

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IMavenArtifactIdentifier.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ISourceDownloader.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenCentralIdentifier.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenPropertiesIdentifier.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenSourceDownloader.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/HashProvider.java, org.eclipse.jdt.ls.tests/projects/singlefile/downloadSources/UsingRemark.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JavaProjectHelper.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractInvisibleProjectBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java
- Fixes redhat-developer/vscode-java#1664
- Download maven-central artifact's sources on-demand
[rgrunber@redhat.com]: Fix testDynamicSourceLookups()
- Move testcase from HoverHandlerTest to InvisibleProjectBuildSupportTest
- Set up the external library after project import to mimic approach
in other invisible projects
@fbricon 
Based on #1580 .
=> Download sources for the masses

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java
=> Should not enable preview compiler options if the tooling doesn't support the early access JDK

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/WrapperValidator.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes #1654 
Java LS and buildship will use $XDG_CACHE_HOME/tooling, ~/.cache/tooling per default
=> Change location of .tooling

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/OverrideMethodsTestCase.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/AbstractCompilationUnitBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2MarkdownConverterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
Fixes #996 
You have to enable creating symbolic links on Windows.
The easiest way is to start the tests as an administrator.
=> Tests fail on Windows

launch/jdt.ls.socket-stream.launch, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/GenerateGetterSetterOperation.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/AnonymousTypeCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/OverrideCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodRefactoring.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/delegates/DelegateCreator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/reorg/DeleteChangeCreator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/AbstractMethodCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ConstructorFromSuperclassProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ModifierChangeCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ConfigurationHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ConfigurationHandlerTest.java
- Enable the capability to fetch indentation settings from the client
[Jinbo Wang]: Adopt the new compilation unit API to consume the client's formatting options.
- Using ICompliationUnit.getOptions(true) to replace the old options project.getOptions(true)
- Fetch the client's formatting options while generating code action proposals
Fixes #1157
Based on #1194
=> Integrate the client's file formatting options with JDT code action handlers

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/FormatterManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Relates to https://github.com/redhat-developer/vscode-java/issues/1572
=> Fetch insertSpaces and tabSize options from the client preferences

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/OverrideMethodsOperation.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/AnonymousTypeCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/OverrideCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/delegates/DelegateCreator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/AbstractMethodCorrectionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ConstructorFromSuperclassProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/JavadocTagsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MoveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
This is a follow-up with the last PR #1657. 
Adopt the new helper methods from the utilities such as Strings, CodeFormatterUtil and JavaPreferencesSettings to deal with the compilation unit's preferences.
=> Adopt the helpers from jdt.core.manipulation to deal with the CU's preferences

CHANGELOG.md
Holding off merging until we know if https://github.com/eclipse/eclipse.jdt.ls/pull/1632 is affecting debug line numbers in a breaking way.
=> Add changelog for 0.70.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/BuildPathCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListenerTest.java
Resolve https://github.com/redhat-developer/vscode-java/issues/1798. Related with https://github.com/redhat-developer/vscode-java/pull/1799
This PR contains 3 major part changes:
- Return the current source paths list when user sends the request `Add/Remove folder to Java Source Path` to the server. The client will use the returned result to update the workspace setting
- Resolve and apply the classpath entries according to the current output path & source path setting when loading the invisible project
- Resolve and apply the classpath entries according to the current output path & source path setting when the related preferences are changed 
=> Support to specify source paths for unmanaged folder

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/RuntimeEnvironment.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JVMConfiguratorTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1813
=> Fix javadoc in 'java.configuration.runtimes' settings

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommandTest.java
Relates to [redhat-developer/vscode-java#1790](https://github.com/redhat-developer/vscode-java/pull/1790), please see that PR for more details.
=> Support Type Hierarchy

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java
Correct a minor typo in the exception message that responds to a failed attempt to add a folder to the Java source path which is already implicitly included by one of its parents.
Fixes redhat-developer/vscode-java#1833
=> Correct minor typo in exception message

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListener.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListenerTest.java
Fix a regression bug introduced in #1658 
When debugging Java Language Server, and the workspace changed, a error message pops as below:
This is because some stale elements remains in the JDT workspace.
=> Fix failed to find root path when workspace changes

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/JavadocCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
=> Update lsp4j to 0.11.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
Add more options in the API `getProjectSettings` for other down-stream dependencies to use.
requires https://github.com/redhat-developer/vscode-java/pull/1828
=> Add more options to query project settings

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.tests/projects/singlefile/simple/test/Test.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListenerTest.java
When setting the source path in `settings.json` but the folder does not exist, an error will be thrown when build the project:
```
MESSAGE Error occured while building workspace. Details: 
message: Project 'invisble-project_7472d942' is missing required source folder: '_/src2'; code: 964;
```
So this PR check the existence of the source folder before add it into the source paths.
=> Check the existence of source folders when setting source paths

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FileEventHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MoveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ResourceUtilsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FileEventHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/MoveHandlerTest.java
=> Support refactoring when renaming or moving files

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InlineConstantTest.java
As @testforstephen mentioned [the corner case](https://github.com/eclipse/eclipse.jdt.ls/pull/1575/files#r507586130) in #1575 , it's better to have `getReferences()` in `InlineConstantRefactoring`. Since it has been available in JDT, we can apply it now.
=> Enhance the condition of inline constant

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/FormatterManager.java, org.eclipse.jdt.ls.tests/formatter resources/version13.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
Will update formatter options to the newest version before applying them. This could work for many scenarios where deprecated formatter settings (in previous profile version) are ignored.
Fixes redhat-developer/vscode-java#1640
=> Update formatter profile options before applying

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
When developing the Java formatter Setting Page, a preview part is needed. However, existing format methods have the following limitation:
- Based on file. If we have a temporary file containing the preview content background, the writing or modifying on the file will trigger VS Code (maybe other clients as well) to open an editor on the temporary file. This behavior can only be avoided by calling `document.save()` after applying `WorkspaceEdit` in VS Code by now, see https://github.com/microsoft/vscode/issues/96920. but saving the content to disk will cost more time than just keeping them in the memory.
- The current mechanism of formatting in Language Server is to monitor the modifying of the formatter profile. As a preview, the frequency of changing the settings would be frequent, …
=> Support String formatting via delegate command

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.tests/formatter/settings.prefs, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JavaSettingsTest.java
=> Ignore o.e.jdt.core.compiler.problem.missingSerialVersion by default.

.project, org.eclipse.jdt.ls.core/.project, org.eclipse.jdt.ls.core/.settings/org.eclipse.jdt.core.prefs, org.eclipse.jdt.ls.product/.project, org.eclipse.jdt.ls.repository/.project, org.eclipse.jdt.ls.tests.syntaxserver/.project, org.eclipse.jdt.ls.tests.syntaxserver/.settings/org.eclipse.jdt.core.prefs, org.eclipse.jdt.ls.tests/.project, org.eclipse.jdt.ls.tests/.settings/org.eclipse.jdt.core.prefs
When opening the eclipse.jdt.ls project in VS Code, it reports 6k+ warnings, most of which are about discouraged access. I tend to suppress discouraged access rules to reduce noise.
=> Engineering: Tune the project settings

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
=> fix: Changes on Formatter profiles have no effect before reloading

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectBuildSupportTest.java
Fixes #1735 
- replaces paths leading with ~ with the user.home system property 
- replaces ${} with their matching values from the environment variables and system properties
- resolves java.project.referencedLibraries, java.import.gradle.home, java.import.gradle.java.home, java.import.gradle.user.home, java.configuration.maven.userSettings, java.configuration.maven.globalSettings, java.project.outputPath, java.project.sourcePaths, java.format.settings.url, java.settings.url,  java.configuration.runtimes
=> java.project.referencedLibraries should resolve paths leading with ~

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java
- A TextDocumentEdit's 'textDocument' field is an
OptionalVersionedTextDocumentIdentifier whose version can be null to
indicate that the version is not known
- Fixes #1695
=> When version is unknown, text document identifier version should be null

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Bar.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Foo.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
- Surround javadoc @param entry with a block tag entry.
- Fixes #1732
- Adjust existing testcase to handle @param description
=> Javadoc @param description lost when retrieved from inheriting class.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
I think the term "symbol" can include more than just type declarations. Pretty much any member should be included. With that said, including declarations from non-sources could bring up too many matches, so I've included just method declarations from source files.
=> Add source method declaration lookups to the workspace symbol search.

launch/jdt.ls.remote.server.launch, launch/jdt.ls.socket-stream.syntaxserver.launch
Fixes #1754.
Even though I only needed to remove the version constraint for `com.google.gson` to fix the issue, I also removed the one for `org.apache.commons.io`. Unless I've missed something these version constraints are unnecessary and will just lead to future problems when libraries/target platforms are updated.
=> Remove version constraints from .launch files

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.tests/projects/maven/semantic-tokens/src/main/java/foo/ClassLiterals.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommandTest.java
Fixes redhat-developer/vscode-java#1921
The cause of the issue is that some expressions with a period after them are recovered as `TypeLiteral`s, which causes the semantic token visitor to put a `keyword` semantic token there. To fix this, I added a check to avoid adding the `keyword` token for recovered `TypeLiteral`s.
=> Fix class literal keyword semantic token

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
The previous implementation of waitForInitializeJobs() will just wait for 5 minutes, which is not enough for first-time import of a large project.
I change it to 1 hour, which should cover the most cases.
=> Add a timeout to waitForInitializeJobs()

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListener.java, org.eclipse.jdt.ls.tests/projects/singlefile/wrong-packagename/src/mypackage/Bar.java, org.eclipse.jdt.ls.tests/projects/singlefile/wrong-packagename/src/mypackage/Foo.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListenerTest.java
=> java.project.sourcePaths doesn't refresh diagnostics

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java
- In languageclient 7.x, the client fails to send the necessary exit()
once a shutdown() response is received from the language server
- When client defines syntaxServerExitsOnShutdown as true, the language
server will exit immediately after the shutdown request
=> Introduce syntaxServerExitsOnShutdown as an extended capability.

org.eclipse.jdt.ls.tests/pom.xml, pom.xml
Fixes #1782 
You can disable lombok with:
```
./mvnw clean verify -Djdt.ls.lombok.disabled=true
```
=> Run test without setting lombok agent

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1947
You can use the following property:
```
"java.jdt.ls.vmargs": "-Djdt.ls.disableProxies=true <your_vmargs>"
```
and check
~/.config/Code<variant>/User/globalStorage/redhat.java/<java.ls.version>/config_<your_os>/.settings/org.eclipse.core.net.prefs
=> Add option to ignore all proxies

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
If the client does not define this preference, the server will use the default value of "ignore". This ensures that existing clients are not broken.
=> Add a preference to control the severity of not covered maven plugin execution

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java, org.eclipse.jdt.ls.tests/projects/maven/salut/src/main/java/org/sample/Bar.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferencesTest.java
Fixes #695
Fixes #1301
This PR replaces #1152, and uses tags instead of the `deprecated` property, since it has been deprecated in LSP 3.15 and 3.16. I also added a helper method for `CompletionHandlerTest` to reduce some code duplication. I do have a few questions about how I should implement this:
1. Do we still need to support the `deprecated` property on document symbols? They were deprecated in favor of using tags in LSP 3.16, [so I switched to using tags instead](https://github.com/0dinD/eclipse.jdt.ls/commit/b9f5f0311296b8bf6d577afe136e3a6992bfbf22#diff-820919a8fb15f7287a49d35ff449241622cb4ac6bb83580d5b214b014bea2951L165-R171). I could also check if the client supports using tags, and fall back to the `deprecated` property if tags are not supported. 
3. In #1152, [the required …
=> Add 'Deprecated' tag to completion items and symbols

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandler.java
- A method should call Submonitor.convert(..) upon receiving its monitor
in order to correctly allocate its share of the work to be done
- Fixes #1722
=> Use the progress monitoring API appropriately.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java
The standard language server has the same issue the syntax server did. It doesn't exit immediately on shutdown request. It relies on the parent process watcher, but I believe that can take up to 30s in the worst case.
- "syntaxServerExitsOnShutdown" -> "shouldLanguageServerExitOnShutdown"
- Shut down the standard language server on shutdown() similar to the
syntax server, when "shouldLanguageServerExitOnShutdown" extended
capability is enabled
- Unlike the syntax server shutdown, the standard server has no issues
if shutdown() returns to the client, before exit() completes
=> Standard language server should also be able to exit on shutdown.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionResolveHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/1992
=> quickfix not available where cursor lands by default on annotations

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OrganizeImportsHandler.java, org.eclipse.jdt.ls.tests/projects/maven/salut6/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/salut6/src/test/java/org/sample/MyTest.java, org.eclipse.jdt.ls.tests/projects/maven/salut6/src/test/java/org/sample/MyTest2.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/AdvancedOrganizeImportsHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2012
=> Organize imports generates duplicate static import statement

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2020
Related Eclipse bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=573595
=> jdtls freezes when importing maven project

pom.xml
See https://ci.eclipse.org/ls/job/jdt-ls-master/1136/consoleFull. We started failing due to https://www.eclipse.org/lists/cross-project-issues-dev/msg18545.html.
- Update to >= 1.3.0 as required by Eclipse infrastructure
- Version not required to be listed if specified in pluginManagement
=> Update eclipse-jarsigner-plugin to 1.3.2.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes #1835. The approach we used to resolve the field constant needs create ASTTree and resolve binding, which is quite expensive for some large file. This PR will defer the calculation to the completionResolve request.
=> Defer constant/default value calculation to completionResolve request instead of completion request

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeTemplatePreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
- Fixes redhat-developer/vscode-java#2052
I don't mind leaving this for after the release.
=> Add support for month, day, hour, minute variables in typeComment.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetector.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetectorTest.java
fix https://github.com/redhat-developer/vscode-java/issues/2075
This makes the following exclusion setting works:
```
"**",
"!**/module1/**"
```
For multi-module maven project, if user wants to ignore part of the sub-modules, he has to ignore the parent pom. Otherwise, the Maven Importer will collect all the sub modules if the parent pom is contained in the scanning result. More details can be seen in https://github.com/redhat-developer/vscode-java/issues/2075.
=> fix: Cannot exclude maven sub-module

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
See #1838 , perf issue about evaluating generic snippets.
There are two groups of Snippets:
- Generic snippets (e.g. foreach, fori, ifelse, etc.)
- Type definition snippets (e.g. class, interface, etc.)
Currently at `completion` stage, we evaluate template patterns in given context to provide `insertText` and `documentation`. At `resolve` stage we do nothing.
Evaluation is relatively expensive. This PR does below things:
- For generic snippets, delay resolving evaluation, providing corresponding `TextEdit` and `documentation` at resolve stage. In `insertText`, placeholders are directly from template patterns.
- For type definition snippets, remove unused `data` field as they are not processed in at resolve stage.
=> evaluate generic server-side snippets in resolve stage

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/IProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseInitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/multi-buildtools/build.gradle, org.eclipse.jdt.ls.tests/projects/multi-buildtools/pom.xml, org.eclipse.jdt.ls.tests/projects/multi-buildtools/settings.gradle, org.eclipse.jdt.ls.tests/projects/multi-buildtools/src/main/java/com/example/Application.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
requires https://github.com/redhat-developer/vscode-java/pull/2060.
Detailed information can be found in https://github.com/redhat-developer/vscode-java/pull/2060.
=> Support import from configuration files

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JDTUtilsTestParametrized.java
Add functionality to exclude files that will not be tracked for changes.
(close https://github.com/eclipse/eclipse.jdt.ls/issues/1847)
=> Add functionality to exclude files that will not be tracked for changes.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporterTest.java
follow up work of #1840 
Support filtering nested folders in `applies()`.:
- For Gradle, the nested folders are ignored to align with the current logic.
- For Maven, the nested folders are included, this is because m2e will skip scanned folders.
=> Support excluding nested configurations

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/module3/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/module3/src/main/java/org/eclipse/App.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/module3/src/test/java/org/eclipse/AppTest.java, org.eclipse.jdt.ls.tests/projects/maven/multimodule3/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
This PR fixes a bug that reported in the stack trace in #2093.
> Note: #2093 is about GTD not working. While this fix could not solve that problem but fix another one that we found in #2093 accidentally.
Here is the root cause:
When user opens a Java file, the status bar will show information like Language Level and VM installation path. Given a URI of a project, calling `findContainersForLocationURI()` will returns an array, for example:
Here we need the second one to get the `JavaProject` via `javaCore.create()`. but the previous sorting logic didn't handle the case correctly.
The new change will get all the project instance and sort them according to the fs path to get the most inner containing project.
=> fix: Get correct Java project in multi-module case

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandler.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Call.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2044
=> 'Open Call Hierarchy' does not jump to reference where it is invoked at

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2088
The issue happens when BuildSupportManager.obtainBuildSupports starts the m2e and buildship plugins that sometimes freezes the workspace.
A stack trace: https://github.com/redhat-developer/vscode-java/issues/2088#issuecomment-918589591 and https://gist.github.com/snjeza/b02b8461499cf025a9b664442dd51ede
A solution is to start these plugins separately before initializing Java LS.
=> Java LS sometimes hangs while loading a gradle project

org.eclipse.jdt.ls.core/.classpath, org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/build.properties, org.eclipse.jdt.ls.core/pom.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/HtmlToPlainText.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2MarkdownConverter.java
- StringUtil moved from helper to inernal package
- Changes in NodeTraversor API
- Changes to internal field of Cleanup
This addresses https://nvd.nist.gov/vuln/detail/CVE-2021-37714 & we'll need a CQ.
=> Update org.jsoup 1.9.2 to 1.14.2

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/projects/eclipse/java11/src/main/java/org/sample/App2.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
Fixes #1813 
Eclipse bugs:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=575149
https://bugs.eclipse.org/bugs/show_bug.cgi?id=576121
=> Go to definition doesn't find results on methods inside an anonymous class

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- Fixes #1885
I tried writing a test for this on the JDT side and for some reason couldn't trigger the NPE as the type binding resolved directly above was always null in the test environment, which is checked. `getFunctionalInterfaceMethod` clearly states that it may return null though.
=> Guard against null binding of unresolved method reference.

README.md
The README was rather developer focused (and only targeting eclipse
users at that)
This puts the focus more on end-user usage.
The main motivation for this is to enable other editors or plugins to
point users to the installation instructions within this repository to
focus their own efforts on explaining how to configure the
editor/plugin.
=> Promote end-user usage instruction more in the README

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
The rangeLength property is deprecated in the specification.
=> Don't use deprecated rangeLength property in handleChanged

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ShowAllQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2130
Requires https://github.com/redhat-developer/vscode-java/pull/2166
=> Quickfixes should be available at the line level

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeGenerationUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsActionTest.java
Part of https://github.com/redhat-developer/vscode-java/issues/2057
If the quick fix is triggered in type declaration, the generated code will be after the last field declaration.
=> Add Generate Constructor to Show Fixes for type declaration

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/AbstractSourceTestCase.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JavaSettingsTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2222 and https://github.com/redhat-developer/vscode-java/issues/2208
=> java server refreshing the workspace (cleaning and building) for each restart

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ReorgCorrectionsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateAccessorsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/HashCodeEqualsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OverrideMethodsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
Part of https://github.com/redhat-developer/vscode-java/issues/2057
=> Always show Organize imports in Quick Fixes for import declaration

org.eclipse.jdt.ls.core/pom.xml
See discussion at https://github.com/eclipse/eclipse.jdt.ls/pull/1948#issuecomment-979635839, when developing eclipse.jdt.ls project in VS Code, skipping loading gradleChecksums job can improve import performance a lot.
=> Boost loading performance of eclipse.jdt.ls project itself

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Interestingly, the repo has a folder `202112081000` (December 8th 2021) which would be the GA, so I'm guessing we won't need to update this once again.
=> Update Target Platform to 4.22 (2021-12) release.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
fix https://github.com/redhat-developer/vscode-java/issues/1422.
No need to add import when user is complete on an import statement.
=> Fix the wrong additional text edit when complete import statement

pom.xml
so you can build jdt.ls with a Java 17 JDK. See #1976.
=> Update tycho to 2.5.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/IProposalRelevance.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.product/languageServer.product, org.eclipse.jdt.ls.product/syntaxServer.product, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertSwitchExpressionQuickAssistTest.java
There's a few issues that need to resolved regarding the API.
=> Add "Convert to Switch Expression" code assist proposal

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ShowAllQuickFixTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2236
=> Duplicate quick fixes when shown at line

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradlePreferenceChangeListener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/WrapperValidator.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/WrapperValidatorTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2218
Test project: 
[test.zip](https://github.com/eclipse/eclipse.jdt.ls/files/7883924/test.zip)
=> Fix gradle wrapper security warning

CHANGELOG.md
I think we're just missing https://github.com/eclipse/eclipse.jdt.ls/pull/1965 .
=> Add Changelog for 1.8.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ASTRewriteRemoveImportsCorrectionProposal.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/StaticImportQuickAssistTest.java
- Fixes #1203
- Fixed upstream at https://eclip.se/542653
=> Convert to static import incorrectly removes an import.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- when the expected type can be resolved, always show the completion
result.
- If the expected type is missing, honor the type filter setting.
fix https://github.com/redhat-developer/vscode-java/issues/2279
=> Better handling type filtering on method completion

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/SerialVersionQuickFixTest.java
Fixes #1899 
Related eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=576482
I have had to disable the lombok agent because of failing some tests. See https://github.com/eclipse/eclipse.jdt.ls/issues/1782
You can reproduce it using the following command:
```
./mvnw clean verify -Djdt.ls.lombok.enabled=true
```
I think the issue in lombok is caused by http://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/commit/?id=64a3b5b9cfb663e786ba9a9ad3f8deddc3c85ea2 (https://bugs.eclipse.org/bugs/show_bug.cgi?id=5753300)
I can't reproduce it in VS Code because ClientPreferences.isResolveCodeActionSupported() returns true (it is false in the tests)
=> Update TP to I20220216-0600

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
We received a lot users feedback that they need code snippets like `sout`, `serr`, etc... Actually we have those snippets supported but with different labels.
To help users easily find those features no matter which IDEs they are used to, this PR adds those mentioned alias to the completion list.
The following alias are added: 
- sysout -> sout
- syserr -> serr
- systrace -> soutm
- foreach -> iter
require: https://github.com/redhat-developer/vscode-java/pull/2314
=> Provide more alias for code snippets

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentHighlightHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxInitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Highlight.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentHighlightHandlerTest.java
Fixes redhat-developer/vscode-java#2211
Fixes redhat-developer/vscode-java#2212
Fixes redhat-developer/vscode-java#2213
Fixes redhat-developer/vscode-java#972
---
This PR improves on the occurrence highlighting by porting the following occurrence finders from `jdt.ui`:
- `MethodExitsFinder`
- `ExceptionOccurrencesFinder`
- `BreakContinueTargetFinder`
- `ImplementOccurrencesFinder`
It also registers the document highlight capability in the syntax server.
Lastly, I fixed a bug which could cause the wrong `DocumentHighlightKind` to be set. The bug was caused by [incorrect logic when checking the bit flags set on an `OccurrenceLocation`](https://github.com/0dinD/eclipse.jdt.ls/blob/cf6358ba4c166fa7d4c45aba5b7b22ea08516524/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/Do …
=> Improve occurrences highlighting

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
This PR adds ability to trigger completion when user types "new |".
This can be a handy feature especially when the expected type is an object.
If the expected type is interface, currently JDT will only propose an anonymous class creation, which is not ideal and needs improve from upstream. For such case I've filed an issue there: https://bugs.eclipse.org/bugs/show_bug.cgi?id=578815
fix https://github.com/redhat-developer/vscode-java/issues/1666
=> Auto complete after new keyword

README.md, org.eclipse.jdt.ls.product/pom.xml, org.eclipse.jdt.ls.product/publish-assembly.xml, org.eclipse.jdt.ls.product/scripts/jdtls, org.eclipse.jdt.ls.product/scripts/jdtls.py
Introducing a package manager friendly start up script to make the handling of jdt.ls easier (fixes #1823 and fixes #1934).
Why did I choose Python and not bash? Basically to address the [following concern](https://github.com/eclipse/eclipse.jdt.ls/issues/1823#issuecomment-899779358):
>  The tricky part is getting and testing something for Windows, Mac, Linux.
The script has been written to be platform agnostic so that it can be used on Window, Linux, and Mac. So there is no need to write separate scripts for each platform.
It also adds some logic to bootstrap Lombok out of the box. This feature could be hidden behind a command line option.
=> Add Package Manager Friendly Start Up Script

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ShowAllQuickFixTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2339
=> Duplicate quick fixes

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServerTest.java
This PR postpone the capability registration until the service is ready.
If we do the registration before LS is ready, the client will start sending request to server, while the server won't be able to handle them in time. A side effect for that is: the client snippet become unusable because VS Code will wait the result from server and render the list together for once.
Also see: https://github.com/redhat-developer/vscode-java/pull/2240#issuecomment-992293711
=> Postpone the capability registration until the service is ready

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
This is a follow-up of https://github.com/eclipse/eclipse.jdt.ls/pull/2022#issuecomment-1067465448. 
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=578817 for performance data.
=> Adopt CompletionProposal new API to ignored types before creating certain proposals

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintVisitor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintsParameterMode.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintsPreferenceChangeListener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHint.java, org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHintKind.java, org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHintLabelPart.java, org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHintParams.java, org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHintProvider.java, org.eclipse.jdt.ls.tests/projects/eclipse/java16/src/main/java/foo/bar/Bar.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintHandlerTest.java
fix https://github.com/redhat-developer/vscode-java/issues/2099
requires https://github.com/redhat-developer/vscode-java/pull/2354
=> Support inlay hints for parameter names

README.md
=> Advertise "friendly" Python startup wrapper a bit more prominently

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintVisitor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintHandlerTest.java
- When a method is a varargs method like: 'foo(Integer i, String... s)',
and be invoked by 'foo(1)'. We should show inlay hint for this case.
=> Fix the inlay hint for varargs methods

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewCUProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeGenerationTemplate.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeTemplatePreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
This works from the client side when creating a new file, but it never did when creating a compilation unit from a code action.
- Use the file & type comments (java.templates.typeComment &
java.templates.fileHeader) settings from the client to construct new
compilation units
- Initialize the "newtype" template which will use the file & type
comment template values
=> Provide file & type comments for newly created compilation units

org.eclipse.jdt.ls.product/scripts/jdtls.py
Make jdtls a "direct" child of the invoking process by replacing the Python script process.
=> Change subprocess to exec in jdtls.py

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProjectEncodingMode.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2416
Requires https://github.com/redhat-developer/vscode-java/pull/2418
=> Unexpected 'Project xxx has no explicit encoding set' warnings

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
fix #2025
The PR works in the following steps:
1. Check if we can find a method-like node with the trigger offset, which might be: `ClassInstanceCreation`, `ConstructorInvocation`, `SuperConstructorInvocation`, `MethodInvocation`, `SuperMethodInvocation` and `MethodRef`.
- If no method-like node is found, fallback to the [previous implementation](https://github.com/eclipse/eclipse.jdt.ls/blob/4dd3f74d3883586bbf10d29b218633efe9bee7a2/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java#L80).
- If a method-like node, we leverage that node to provide more context, especially range information to provide signature help (newly added code in `SignatureHelpUtils.java`)
It fixes the following cases:
=> Improve the signature help

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionInsertReplaceCapabilityTest.java
requires https://github.com/redhat-developer/vscode-java/pull/2427
=> Support completion insert replace capability

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
If the capability is missing there was a NullPointerException
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.eclipse.lsp4j.CompletionItemCapabilities.getInsertReplaceSupport()" is null
at org.eclipse.jdt.ls.core.internal.preferences.ClientPreferences.isCompletionInsertReplaceSupport(ClientPreferences.java:390)
at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalReplacementProvider.updateReplacement(CompletionProposalReplacementProvider.java:198)
at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalReplacementProvider.updateReplacement(CompletionProposalReplacementProvider.java:120)
=> Fix NPE in isCompletionInsertReplaceSupport check

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
- JavaLanguageServerPlugin.start() -> StandardPreferenceManager() ->
StandardPreferenceManager.initializeMavenPreferences() triggered M2E
before JavaLanguageServerPlugin.start() could set
"logback.configurationFile"
=> Fix issue where JDT-LS's logback configuration was being ignored

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.tests/projects/gradle/invalid-subproject/invalid/build.gradle, org.eclipse.jdt.ls.tests/projects/gradle/invalid-subproject/settings.gradle, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ProjectUtilsTest.java
fix #2058 
In some cases when importing is failed, the buildship will not create the corresponding IProject so that `ProjectUtils.getAllProjects()` will not list all the projects in the workspace, even though some build file in those projects has markers created.
=> Show error status when the project is not created

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
for example, when it's `foo()`, we should not show the signature help.
=> Do not show signature help at the end of an invocation

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
As reported in #2087 when searching for workspace symbols
which doesn't have attached source, trying to open them result
in a NPE in logs. This is due to the location ending up null.
The fix fallback in this situation to find the location by using the
class file.
Signed-off-by: Gayan Perera <gayanper@gmail.com>
=> Add support for opening binary symbols with no source

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/codemanipulation/GenerateGetterSetterOperation.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateAccessorsHandlerTest.java
related to https://github.com/redhat-developer/vscode-java/pull/2459
=> Show field type when generating accessors

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/EventType.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java
related to https://github.com/redhat-developer/vscode-java/pull/2442, more details can be found in that PR.
=> Support Gradle invalid type code error check

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
- Fixes #2084
- Intepret everything prior to the last '.' as a package qualifier and
everything after as the type name
=> Symbol search should support qualified names.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2429
Requires https://github.com/redhat-developer/vscode-java/pull/2451
Test vsix: https://github.com/snjeza/vscode-test/raw/master/java-1.6.1.vsix
=> Should explicitly report the fatal settings error

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ActionMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ActionMessages.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ShowAllQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateAccessorsActionTest.java
https://user-images.githubusercontent.com/45906942/168972140-70eceb97-cac4-408f-a94a-2f4ce390bdac.mp4
The quick fixes can be found at 
- variable itself
- at line level
- at modifier
=> Show quick fixes for generating accessors in field declarations

CHANGELOG.md
=> Add Changelog for 1.12.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java
- Fixes https://github.com/redhat-developer/vscode-java/issues/2488
- Avoid usage of java.lang.Runtime#exec(..) along with the 'kill'
command to determine the status of the parent process
- Fall back to previous behaviour in case of error
=> Use ProcessHandle.of(long) to determine state of the parent process.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
part of https://github.com/redhat-developer/vscode-java/issues/2473
Before, the highlighted option is `Never`. This PR changes the order of the options so that `Yes` will be highlighted.
Note: I changed the word `Now` to `Yes` to make it sounds more straight-forward. @rgrunber Is this word change makes sense to you? (Since you are native speaker 😄  )
=> Change the order for configuration updating options

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProjectConfigurationUpdateHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/extended/ProjectConfigurationsUpdateParam.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ProjectConfigurationUpdateHandlerTest.java
- Multiple project can be updated at the same time via 'java/projectConfigurationsUpdate'
request.
- Argument of this request is 'ProjectConfigurationsUpdateParam', which
contains a list of 'TextDocumentIdentifier'.
requires https://github.com/redhat-developer/vscode-java/pull/2513
=> Allow to update multiple projects at the same time

org.eclipse.jdt.ls.product/scripts/jdtls.py
Related to https://github.com/eclipse/eclipse.jdt.ls/pull/2118
Signed-off-by: Wang Lun <me@wanglun.org>
=> Update launch script, Java 17 is required now

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JdtDomModels.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsHandlerTest.java
related to https://github.com/redhat-developer/vscode-java/pull/2508
=> auto-select field when generating constructors

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/CodeActionComparator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistComparator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertMethodReferenceToLambaTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateConstructorsActionTest.java
This PR introduces the sort mechanism in quick assists for different contexts, we can define different priorities for different contexts in `QuickAssistComparator`. e.g., in field declaration, generate accessor > generate constructor
https://user-images.githubusercontent.com/45906942/171313406-3bc7f738-370e-444e-8931-ff73a27a28da.mp4
=> Adjust the order of code actions

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProjectConfigurationUpdateHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/extended/ProjectBuildParams.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandlerTest.java
- Add a new extended LSP request 'java/buildProjects' to support updating
selected projects.
part of https://github.com/redhat-developer/vscode-java/issues/2510, requires https://github.com/redhat-developer/vscode-java/pull/2526
=> Allow build selected projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
Currently, jdtls uses `java.imports.gradle.wrapper.checksums` to configure
allowed/disallowed gradle-wrappers. But the error is misleading as it
says `java.import.gradle.wrapper.checksums`.
It took me an evening to figure out, we need to use `imports` and not  `import` for this config.
refer: https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java#L300
It's quite confusing. The [docs](https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line) are also misleading, as it has quite old info on the config which can be used.
=> correct typo in gradle checksum mismatch error

launch/jdt.ls.remote.server.launch, launch/jdt.ls.socket-stream.launch, launch/jdt.ls.socket-stream.syntaxserver.launch
The existing *.launch files are often broken while updating the target platform. We can mitigate this by adopting a new option to automatically include the required plugins while launching. This new option was introduced from Eclispe 2022-06 
https://www.eclipse.org/eclipse/news/4.24/pde.php#auto-add-requirements-launches.
=> Automatically include the required plug-ins in the launch files

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
=> No completion for FQN constructors

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java
https://github.com/eclipse/eclipse.jdt.ls/pull/2152 added a new parameter to the original constructor, that would break the completion feature of DEBUG CONSOLE in Java Debugger extension. Add a compatible constructor to avoid breaking other extensions.
=> Add a compatible constructor to CompletionProposalDescriptionProvider to avoid breaking Java Debugger

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListener.java, org.eclipse.jdt.ls.tests/projects/singlefile/inferSourceRoot/lesson1/Lesson1.java, org.eclipse.jdt.ls.tests/projects/singlefile/inferSourceRoot/lesson2/Lesson2.java, org.eclipse.jdt.ls.tests/projects/singlefile/inferSourceRoot/lesson3/Lesson3.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
fix https://github.com/redhat-developer/vscode-java/issues/1282
When user opens a source file, we try to infer the source root on demand if:
- it's not the on the classpath
- it has package not matching errors
=> Refresh the invisible project's classpath on demand

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
requires https://github.com/redhat-developer/vscode-java/pull/2575 (with a gif)
- store the build file digest so that the update notification will only
appear when necessary.
- if the build file needs a reload, append a problem marker to it.
=> Provide reload project diagnostics on demand

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
Signed-off-by: Shi Chen chenshi@microsoft.com
This is a workaround about https://github.com/redhat-developer/vscode-java/issues/718, https://github.com/eclipse/buildship/issues/460
We observed a lot of projects (especially Gradle projects) have this error. Actually, we have a workaround to set the severity to `warning` manually: https://github.com/eclipse/buildship/issues/460#issuecomment-297953710
But for VS Code users, there is no existing wizard to config this setting and it's also hard and not recommended to change .prefs file in `.settings` folder. In this way, we can make the default value of config to `warning` to make the users not be blocked by this error at least. 
For example, given a sample project https://github.com/opensearch-project/OpenSearch.git, the redhat.java extension …
=> Set default severity of "Circular classpath" to `warning`

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
- For a query of 'foo.bar.baz', in addition to searching for all types
matching 'baz', whose package matches 'foo.bar', we should also search
for all types whose package matches 'foo.bar.baz'
- Refactor custom TypeNameMatchRequestor & MethodNameMatchRequestor
- Add testcase
This was discussed in https://github.com/redhat-developer/vscode-java/pull/2538#discussion_r915894958
CC : @gayanper
=> Always interpret the full workspace symbol query as a package name.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ProjectUtilsTest.java
- only infer the source root when the opened Java source file belongs
to an unmanaged folder.
=> Infer the source root only when necessary

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.tests/projects/singlefile/inferSourceRoot/Main.java, org.eclipse.jdt.ls.tests/projects/singlefile/inferSourceRoot/a/very/deep/path/Source.java, org.eclipse.jdt.ls.tests/projects/singlefile/invisibleFileDetector/Main.java, org.eclipse.jdt.ls.tests/projects/singlefile/invisibleFileDetector/eclipse/Eclipse.java, org.eclipse.jdt.ls.tests/projects/singlefile/invisibleFileDetector/excluded/Excluded.java, org.eclipse.jdt.ls.tests/projects/singlefile/invisibleFileDetector/other-project/Other.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListenerTest.java
Another enhancement for inferring the source roots of the invisible projects.
- based on the source root inferred from the trigger file, do more search for other potential source roots.
- if the source root is linked folder, search all direct child folders.
- otherwise, search all the sibling folders.
This pre-inference behavior plus the [lazy inference](https://github.com/eclipse/eclipse.jdt.ls/pull/2160), should improve the getting start experience for the unmanaged folders.
=> Search more folders to infer source roots for invisible projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceExecuteCommandHandler.java
- fetch the extension registry again when delegate command handler cannot be found.
- change WorkspaceExecuteCommandHandler to Bill Pugh Singleton (thread safe).
Our extension's BI shows that there are some `no delegateCommandHandler` errors. It's hard to stably reproduce but looking into the code, looks that we have some issues under the concurrent scenarios.
For example, when a command starts to find its delegator before it's added via `public synchronized void added(IExtension[] extensions)`.
This case can be easily reproduced in debug mode:
1. set a break point in the entry of `public synchronized void added(IExtension[] extensions)`
2. Launch JDT.LS and open `https://github.com/spring-projects/spring-petclinic/blob/main/src/main/java/org/springframework/samples/petclinic/PetClinicAppl …
=> Fetch the extension registry again when delegate command handler not found 

org.eclipse.jdt.ls.core/build.properties, org.eclipse.jdt.ls.core/gradle/protobuf/init.gradle, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradlePreferenceChangeListener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/gradle/protobuf/build.gradle, org.eclipse.jdt.ls.tests/projects/gradle/protobuf/settings.gradle, org.eclipse.jdt.ls.tests/projects/gradle/protobuf/src/main/java/Library.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
A Gradle init script is added as a patch to automatically add Protobuf
output source directories to clsspath. The script works for Gradle
'com.google.protobuf' plugin 0.8.4 or higher.
The init script will be extracted as a sibling file of the bundle jars.
As a side effect, the Protobuf output source directories will be created
beforehand, due to an issue of Buildship.
See: https://github.com/eclipse/buildship/issues/1196.
This should mitigate some complains about protobuf support:
- https://github.com/eclipse/eclipse.jdt.ls/issues/1667
- https://github.com/redhat-developer/vscode-java/issues/1482
- https://github.com/redhat-developer/vscode-java/issues/177#issuecomment-530638362
I also raised a PR at the protobuf plugin repo to support Eclipse classpath: …
=> Automatically add Protobuf output source directories to classpath

org.eclipse.jdt.ls.core/build.properties, org.eclipse.jdt.ls.core/gradle/init/init.gradle, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.tests/projects/gradle/nameConflict/nameconflict/build.gradle, org.eclipse.jdt.ls.tests/projects/gradle/nameConflict/settings.gradle, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
related to https://github.com/microsoft/vscode-java-pack/issues/1040
When we open a Gradle project having the same name in the rootfolder and subfolder, the language server will report the following error:
The root cause is that eclipse resource system doesn't allow the duplicate names, so the proposal here is that we can rename the project name with `${rootProject.name}-${project.path}` when conflicts are detected. The new project name looks like this:
TODOs:
=> Rename Gradle project name when conflict

org.eclipse.jdt.ls.core/gradle/protobuf/init.gradle
Synced with Buildship and get confirmed that the attributes `gradle_scope` and `gradle_used_by_scope` are not used anymore.
=> Remove the deprecated Gradle attributes

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProgressReport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManagerTest.java
Along with the specific event language/progressReport eclipse.jdt.ls now sends the standard Language Server Protocol event $/progress. This enables unified handling of eclipse.jdt.ls in all IDEs. For example, the fidget plugin for Neovim can rely on these events without adding code that handles eclipse.jdt.ls' specific event. Here is an example (see bottom right corner):
=> Send $/progress Notifications

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/gradle/protobuf/init.gradle, org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/framework/IFrameworkSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/framework/protobuf/ProtobufSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.tests/projects/gradle/protobuf/build.gradle, org.eclipse.jdt.ls.tests/projects/gradle/protobuf/src/main/proto/simple.proto, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/framework/protobuf/ProtobufSupportTest.java
After projects are imported, check if any of the projects contains the
classpath entry having 'protobuf_generated_source' attribute and is empty.
If we found such projects, ask users to run 'generateProto' and `generateTestProto`
Gradle tasks to generate those Java source files.
1. Import https://github.com/square/retrofit
2. If the protobuf output sources haven't been generated, a notification will be popped up to ask user to generate.
3. If it has been generated, nothing happens.
=> Ask to run generate proto tasks after projects are imported

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradlePreferenceChangeListener.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
When the android support enable preferences changed, we should force update all Gradle project to apply these changes.
=> Listening to changes of Android preferences

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/framework/android/AndroidSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
This PR is a follow-up for https://github.com/eclipse/eclipse.jdt.ls/pull/2197#issuecomment-1229838720
After Android project imported, we can check the environment and manually run "assemble" tasks to generate android source files, including R files, BuildConfig files, DataBinding files, etc.
Please note that since this change works only for Gradle version under 5.4 and jdt.ls is using Java 17 to run tests, which is incompatible with Gradle < 5.4, I'm not able to add a test case for it.
=> Automatically generate Android sources for Gradle < 5.4

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
Today I just found out that the signature help works for record class now.
It was not working several months ago. Maybe this is thanks to @rgrunber's work in the upstream :)
So, I removed those todos and add a test for that.
=> Add tests for signature help on record class

org.eclipse.jdt.ls.product/scripts/jdtls.py
- Option was deprecated in JDK 13
- Fixes #2221 
=> Remove -noverify option from JDT-LS startup script.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JdtDomModels.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HashCodeEqualsHandlerTest.java
fix https://github.com/redhat-developer/vscode-java/issues/2502
Sort IVariableBindings before return to the client/after receiving pick results from the client.
=> Show toString()/hashCode() and equals() fields in definition order 

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/HashCodeEqualsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/CodeActionUtility.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringActionTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HashCodeEqualsActionTest.java
This PR will detect the methods of the current type, and choose which quick fix to show.If the current type has corresponding:
-  toString() method without arguments, we do not show generate toString() in quick fixes
- hashCode() method without arguments **and** equals() method with an object argument, we do not show generate hashCode() and equals() in quick fixes
Please note that this change will not affect "Source Action" in the right click menu, the "Source Action" part will always show them in case of the user wants to override the methods anyway.
=> show generate toString()/hashCode() and equals() quick fixes on demand

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2673
=> Add buildship auto sync preference

org.eclipse.jdt.ls.core/gradle/android/init.gradle, org.eclipse.jdt.ls.core/gradle/protobuf/init.gradle, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
fix #2222, currently we have lots of error logs in JDTLS server log for vscode-insider users since the workspace folder contains a space, which is not supported by URI, so we won't use it for recently changed Gradle supports.
cc: @rgrunber 
cc: @jdneo for protobuf support script.
=> fix: Do not use URI for getting project folder to avoid unsupported spaces

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/AbstractCompilationUnitBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
When type completion are applied where the same simple name already imported in the scope, the second type completion is completed as a fully qualified completion.
=> Fix type completion when type name conflicts

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/JavaLaunchConfigurationInfo.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
use 'org.eclipse.jdt.launching.localJavaApplication' configuration type and use 'excludeTest' attribute to specify whether test classpath should be included.
Since we updated M2E, and the [restriction that previous versions have](https://github.com/eclipse/eclipse.jdt.ls/blob/3d1a42c80abb12357a1152a097ec63b14ea5068c/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/JavaLaunchConfigurationInfo.java#L46-L50) is now removed. So we can just simply use the `localJavaApplication` type configuration to resolve the classpaths.
fix https://github.com/redhat-developer/vscode-java/issues/2628
=> Fix gradle project classpath calculation

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CreateModuleInfoHandler.java, org.eclipse.jdt.ls.tests/projects/maven/modular-project2/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/modular-project2/src/main/java/com/example/A.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CreateModuleInfoHandlerTest.java
requires https://github.com/redhat-developer/vscode-java/pull/2680
Create module-info.java if the Java project's compliance is 9 or higher and does not exist module descriptor file yet.
This could somehow mitigate the error: `The package XXX is accessible from more than one module: ...`
Another idea to resolve this issue is to let JDT Core allow disable the module system on demand, see: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/415
sample project that can be used to verify: [helloworld.zip](https://github.com/eclipse/eclipse.jdt.ls/files/9643870/helloworld.zip)
=> Support creating module-info.java

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
When completing lambda the parenthesis are only added if the lambda
- has multiple parameters
- no parameters
This will suggest 
Runnable r = () ->
Consumer<String>  c = s ->
BiConsumer <Long, Integer> bc = (i,l) ->
The variable names might differ based on the name guesser.
=> Improve lambda completions

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
more details can be found in https://github.com/redhat-developer/vscode-java/issues/2692#issuecomment-1259093782
Signed-off-by: Shi Chen chenshi@microsoft.com
=> Fix Gradle project synchorization error when init script path contains spaces

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
- The temp files will not be deleted on JVM exist, since it will cause buildship fail when get Eclipse project instance after the server restarts.
- Cache the temp files for each session, to make sure there will not be too many temp files generated when reloading projects.
related with https://github.com/redhat-developer/vscode-java/issues/2692
=> Keep the temp init scripts on disk

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2676
=> Deadlock when using JDK17 with maven java project

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
- prevent generating duplicated files, the temp file will only be generated when the content is changed.
- the digest can also be used to guard the integrity of the file.
This is the follow-up of https://github.com/eclipse/eclipse.jdt.ls/pull/2249
=> Check the digest of the init scripts

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Today when importing projects we disable auto build and reset it back to previous value to avoid conflicts between project imports and build jobs. But resetting back auto build to true cause the whole workspace to build again which takes considerable time for large projects which blocks all other operations.
The improvement use workspace scheduling rule to make sure another job cannot be executed at the same time such as a auto build according to how eclipse workspace sensitive jobs are implemented internally.
Must further future improvement would be to apply this rule at each project import iteration if further optimization is needed.
=> Improve project initialization

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
Fixes part of the issue #1960, the reason is that JDT triggers unnecessary update with the default vm change. (See the analysis from the PR https://github.com/eclipse/eclipse.jdt.ls/pull/1961).
See the TODO in the following snippet, we should trigger project update only if the project importer uses the default vm.
https://github.com/eclipse/eclipse.jdt.ls/blob/f8452b422add64f9bbc80d0e22b48ed71797e563/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java#L305-L309
Since the Eclipse and Maven project importer doesn't depend on the default vm, I changed it to only trigger update for gradle projects. Also, see the earliest PR https://github.com/eclipse/eclipse.jdt.ls/pull/1430 that introduced this snippet, where it exactly is used to solve gradle import issue.
=> Avoid unnecessary project updates when the default vm changes

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/maven/null-analysis/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/null-analysis/src/main/java/org/sample/Bar.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2712
Fixes https://github.com/redhat-developer/vscode-java/issues/2721
Fixes https://github.com/redhat-developer/vscode-java/issues/2725
=> The type javax.annotation.Nonnull cannot be resolved

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BundleUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
- Add a command to enable client refresh bundles on demand.
- Before JDT.LS send ready notification to client, ask client to synchronize bundles if necessary.
requires https://github.com/redhat-developer/vscode-java/pull/2729
=> Synchronize the bundles on demand

org.eclipse.jdt.ls.core/gradle/android/init.gradle
- Support Android projects even if they apply kotlin plugin
- Kotlin is not supported by jdt.ls, but it could be supported by an extension to the ls
- Even if Kotlin is not supported, Java code in project can still benefit from the support
FYI @CsCherrYY, @jdneo
=> Add opportunistic support for Java/Kotlin polyglot Android projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
fix #2272, We should construct a map contains null analysis options only and use `IJavaProject.setOptions(map)` to avoid storing the current "snapshot" of all options.
=> Only update affected options to project when updating null analysis options

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
Adopt the new preference to solve the problem 'The package xxx is accessible from more than one module'.
See: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/424
fix https://github.com/redhat-developer/vscode-java/issues/2061
fix https://github.com/redhat-developer/vscode-java/issues/1732
fix https://github.com/redhat-developer/vscode-java/issues/862
fix https://github.com/redhat-developer/vscode-java/issues/1619
=> Ignore unnamed module for split packages

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/IProposalRelevance.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/MoveHandlerTest.java
This takes advantage of the refactorings done in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/288 & https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/294.
=> Add quick-fix for permitting subtype of a sealed class.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/ActualTypeResolver.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/InnerExpressionResolver.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaContextType.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaContextTypeRegistry.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaLanguageServerTemplateStore.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaPostfixContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaPostfixContextType.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/MultiVariableGuess.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixCompletionProposalComputer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplate.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/TypeResolver.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/VariablePosition.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaLanguageServerTemplateStoreTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
- Reuse the headless part of code from jdt.ui.
- The supported templates in this PR are: cast, else, for, fori, forr, if, nnull, null, sysout, throw, var, while.
fix https://github.com/redhat-developer/vscode-java/issues/1455
fix https://github.com/eclipse/eclipse.jdt.ls/issues/863
requires https://github.com/redhat-developer/vscode-java/pull/2746
We will only calculate the postfix completions when:
- The completion is triggered by the trigger character `.`
- The completion is triggered manually
In most cases, it just skips the postfix completion calculation.
Below is the CPU sampling when we trigger the completion for the code `args.|`, where `args` is a `String[]`:
Though it takes 36% of the CPU times, the time for completion after `.` is relatively fast, so the real response time is …
=> Support postfix completion

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaPostfixContext.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
For example, when trigger completion after `System.|`, the postfix completions should not appear.
=> Skip postfix evaluation when the completion token is not a variable

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaPostfixContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
Different from Eclipse just apply the text edits directly after a completion item is committed. In JDT.LS, we have to calculate the additional text edits first and return them to the client. And then wait the client to apply the edits and send the document change event back to the server. So the implementation is different from JDT.Core.
The import statement to be added will be calculated when resolvers are resolving the variables. The result will be cached in a map organized by the template name.
=> Support adding imports for postfix completion

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ReorgCorrectionsSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ReorgQuickFixTest.java
See: https://github.com/redhat-developer/vscode-java/issues/2748
https://user-images.githubusercontent.com/45906942/197139990-8447be28-559a-4358-b5d3-2e8651bcf003.mp4
=> Support "remove all unused imports"

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpContext.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
- Get erased type name for parameterized type binding.
- Try to search for secondary types when primary type search failed when resolving the method document.
fix https://github.com/redhat-developer/vscode-java/issues/2739
=> Fix signature help not working correctly for parameterized type

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/NullAnalysisTest.java
fix https://github.com/redhat-developer/vscode-java/issues/2764
`IJavaProject.setOptions()` will replace existing options with default values if not exist in the map, so the source level information will be lost after we set null analysis options.
```
Sets the project custom options. All and only the options explicitly included in the given table are remembered; all previous option settings are forgotten, including ones not explicitly mentioned.
```
We should merge the non-inherit project options before setting it.
=> Do not forget existing project options when setting null analysis options

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/NullAnalysisTest.java
related to https://github.com/redhat-developer/vscode-java/pull/2747
add new preference `java.compile.nullAnalysis.mode`, which type is `FeatureStatus`. 
- When set to `interactive` (default), a notification will show once null annotation types are detected when project is imported or null analysis related configuration changed.
- When set to `automatic`, the null analysis will be enabled.
- When set to `disabled`, the null analysis will be disabled.
=> Add an option to enable/disable null analysis

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2763
Steps to reproduce:
- set 
```
"java.import.generatesMetadataFilesAtProjectRoot": true,
```
in settings.json
```
$ git clone git@github.com:springframeworkguru/spring-rest-client-examples.git
$ cd spring-rest-client-examples
$ rm -rf ~/.config/Code/User/workspaceStorage/
$ rm -rf .project .classpath .settings/ .factorypath target/ .apt_generated*
$ code .
```
- wait for Java LS to build the workspace
- exit VS Code
```
$ rm -rf .project .classpath .settings/ .factorypath target/ .apt_generated*
$ code .
```
Test vsix: https://github.com/snjeza/vscode-test/raw/master/java-1.12.1.vsix
=> Configuring java project stuck in 69%

org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/AddDeprecatedAnnotationCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/AddOverrideAnnotationCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/ISimpleCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/MemberAccessUsesThisCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/StaticAccessUsesClassNameCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
- Add new setting `java.cleanup.actionsOnSave` to list which clean ups to run
- Add clean up to prefix all member accesses with `this`
- Add clean up to prefix all static member accesses with class name
- Add clean up to insert missing `@Override`
- Add clean up to insert missing `@Deprecated`
See redhat-developer/vscode-java#2144
Signed-off-by: David Thompson <davthomp@redhat.com>
=> Add setting for clean ups to be applied upon document save

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServerApplication.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseInitHandler.java
Remove an execution path that only works if IApplication is running; so JDT-LS can be used in different deployments.
Part of https://github.com/eclipse/eclipse.jdt.ls/issues/2311
=> Do not mandate LanguageServerApplication running

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
related to https://github.com/redhat-developer/vscode-java/pull/2790
Since the deadlock issue has been addressed via https://github.com/eclipse/buildship/commit/2d105739966ef4d07dc12b368d22553f8efcffc4, we can get the new buildship snapshot without deadlock, so we can set `interactive` by default now.
=> set null analysis `interactive` by default

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
Fixes #2326 
The issue can be reproduced in Eclipse.
=> ProjectsManagerTest.testCancelInitJob fails randomly

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProgressReport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManagerTest.java
Clients like neovim show an error message if `end` is received for a
token without having received a corresponding `begin`.
The specification also requires it:
> To start progress reporting a $/progress notification with the following payload must be sent
This ensures `begin` is always sent first and also avoids creating
intermediate `ProgressReport` instances.
`isDone` can be immediately true. In that case the server send immediately a `end` notification without having sent a `begin`.
=> Always send `begin` work done progress before sending `end`

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/OrganizeImportsHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java
fix #2333, for a scenario when multiple unresolved types in an annotation declaration, multiple "add all missing imports" are easily observed. This PR moves the logic of generating the quick fix to the end of quick fixes.
It also check all the existing relevance of `AddImportCorrectionProposal`s and assign the new "add all missing imports" equals the minimum value -1. In case of the wrong order.
=> fix multiple add missing imports at one line

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
- Fixes #2327 
- We define a set of default code action kinds, which seem to be calculated regardless of whether the client even supports them
- If a client supports code action resolve, but has not registered code action support for a particular kind (eg. quickassist), we might return a null command
- Nesting the null within the union (Either) makes the Optional useless so we should return null directly
=> Prevent the code action conversion from producing null code actions.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/InvertEqualsCleanUp.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
See: https://www.eclipse.org/eclipse/news/4.19/jdt.php#invert-equals
=> Add clean up to invert equals calls on null

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaPostfixContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
This PR put the postfix templates to the bottom of the completion list, which is also the default behavior of other popular Java IDEs.
Previously, a text edit is used to replace the expression. To make it work, another filter text has to be set to match the expression. A side effect of this is that it always places the postfix template at the top of the list because the filter text is matched.
In this change, the insert text is directly used, so the filter text is not needed anymore. Besides, another additional text edit will be responsible to remove the code to be replaced.
=> Display the postfix completion at the bottom of the list

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
Modifying a running or just cancelled job is not always a safe operation. This can (does when integrated in Eclipse IDE) lead to IllegalStateException when calling getRule() on some already scheduled job.
To prevent that, just create a new job when rules change.
=> Avoid re-using same job

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/InstanceofPatternMatch.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/LambdaExpressionCleanup.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/SwitchExpressionCleanup.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/VariableDeclarationFixCleanup.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
* Add final modifier where possible
* Convert switch statement to switch expression
* Use pattern matching for instanceof checks
* Convert anonymous function to lambda expression
* Add test cases, and set CleanUpsTest compliance to 19
=> Create cleanup actions for some existing quick assists.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
The result of `executeClientCommand` could be a map in the LSP
`ResponseError` format.
Previously this resulted in a ClassCastException which got logged:
class com.google.gson.internal.LinkedTreeMap cannot be cast to class java.util.ArrayList (com.google.gson.internal.LinkedTreeMap
This gave users the impression that there's a bug.
This changes the logic to instead log the message returned by the
client.
In neovim for example it results in:
Command _java.reloadBundles.command not supported on client
=> Log user friendly error if client does not support _java.reloadBundles.command

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/IProposalRelevance.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AnnotationMissingAttributeQuickFixTest.java
Requires eclipse-jdt/eclipse.jdt.ui#335
Closes #1860
Signed-off-by: David Thompson <davthomp@redhat.com>
=> QuickFix for annotation missing attributes

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionMatchCaseMode.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
requires https://github.com/redhat-developer/vscode-java/pull/2834
This PR adds a new preference 'java.completion.matchCase' to specify the case matching
behavior when doing code completion. Available options are:
- FIRSTLETTER: Match case for the first letter only.
- OFF: Do not match the case.
Some profiling results when doing completion in petclinic:
  | 1 | 2 | 3 | 4 | 5 | Avg.
-- | -- | -- | -- | -- | -- | --
firstLetter | 368 | 58 | 60 | 52 | 107 | 129
off | 421 | 115 | 88 | 85 | 90 | 159.8
  | 1 | 2 | 3 | 4 | 5 | Avg.
-- | -- | -- | -- | -- | -- | --
firstLetter | 278 | 60 | 50 | 47 | 69 | 100.8
off | 405 | 160 | 101 | 135 | 104 | 181
  | 1 | 2 | 3 | 4 | 5 | Avg.
-- | -- | -- | -- | -- | -- | --
firstLetter | 368 | 240 | 84 | 126 | 61 | 175.8
off | 530 | 221 | 166 | 152 | 151 | 244 …
=> Support matching case for code completion

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandlerTest.java
- Add the command `java.edit.handlePasteEvent` to handle modifying paste
events
- Add logic to modify paste events when the user pastes into a
`StringLiteral`
Signed-off-by: David Thompson <davthomp@redhat.com>
=> New delegate command to handle paste events

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/GradleCompatibilityProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java
related to https://github.com/redhat-developer/vscode-java/pull/2773
Gradle provides better JPMS support since 7.0, see: https://github.com/gradle/gradle/issues/890#issuecomment-756213083, which means the Gradle versions under 7.0 might cause some issues, and the user will see errors such as "xxx is not accessible".
See https://github.com/gradle/gradle/issues/16922, Gradle 7.0.1 added an extra fix about JPMS projects, so 7.0.1 is a better recommendation version IMO.
this PR provides a quickfix to help users upgrade the gradle version.
https://user-images.githubusercontent.com/45906942/199211128-69f2d809-992e-4415-a329-674913584b54.mp4
=> Support quickfix for gradle jpms projects

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2857
Steps to reproduce:
- create a simple project via https://start.spring.io, selecting Java 17, Maven, Spring Boot 2.7.6 
- import it in VS Code
- remove the target folder
- right click pom.xml, select Reloads Projects
- check if target/classes/application.properties exists
The issue can be reproduced in Eclipse with the latest m2e [release](https://download.eclipse.org/technology/m2e/releases/latest/) but can't be reproduced with the latest m2e [snapshot](https://download.eclipse.org/technology/m2e/snapshots/latest/)
A related issue: https://github.com/eclipse-m2e/m2e-core/issues/1150
=> Update m2e to use m2e snapshot

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SimilarElementsRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandlerTest.java
related to https://github.com/redhat-developer/vscode-java/pull/2795
=> Add missing import on paste

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.tests/projects/singlefile/simple2/src/App.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
- Remove the classpath checking logic and leverage ClasspathEntry.validateClasspath() to do the checking job.
fix https://github.com/redhat-developer/vscode-java/issues/2786
=> Fix output folder cannot be the same as the source folder

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/IndexUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SharedIndexTest.java
The upstream PR https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/152349/ allows reusing library indexes from a common location if they exist. If the common index is not hit, then it will fallback to create indexes in local workspace instead of writing back to the common location.
This PR attempts to solve the writing problem and support copying local library indexes back to the common location after the projects have been imported.
To avoid conflicts between two processes writing to a shared index, each Java process first copies the local index (e.g. 1977137404.index) to a unique tmp file (e.g. 1977137404.index.\<timestamp\>) on the shared folder, and then renames the tmp file name to the desired index file name. Because renaming is atomic, it does not leave a file with corrupted …
=> Share indexes among workspaces

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommand.java, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/.classpath, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/.project, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/.settings/org.eclipse.core.resources.prefs, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/.settings/org.eclipse.jdt.core.prefs, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/src/org/sample/First.java, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/.classpath, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/.project, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/.settings/org.eclipse.core.resources.prefs, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/.settings/org.eclipse.jdt.core.prefs, org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/src/org/sample/Second.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommandTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2871
Test vsix: https://github.com/snjeza/vscode-test/raw/master/java-1.14.3.vsix
=> vscode does not show type hierarchy on maven multi module

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Update the target platform to include the change https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/379 for `org.eclipse.jdt.junit.runtime`.
This allows to execute junit 5 parallel tests.
=> Update target platform to 4.27-I-builds/I20230114-1800

org.eclipse.jdt.ls.product/scripts/jdtls.py
This addresses #2218 
jdtls would fail to start, exiting early in the python launch script.  FreeBSD was an unenumerated system, when determining which configuration to use.  This commit instructs jdtls to treat FreeBSD in the same manner as it does Linux.
Note, this may not work in all use cases on FreeBSD, but I was able to use it without issue from [Helix](https://helix-editor.com).  It will _probably_ work with neovim and others, but I have not personally tested other text editors.
At any rate, this change could offer a solution to other users of FreeBSD.
Signed-off-by: Loren Schlomer <me@schlomie.com>
=> Use the Linux config on FreeBSD systems

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
From my testing this took the target platform (in `$HOME/.config/Code/User/workspaceStorage/${workspaceHash}/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/`) from ~389MB to ~341MB.
This also eliminates the following error, which occurs, because the xtext.sdk.feature brings in some dependencies that disturb the test runtime. in Eclipse IDE, one can remove the problematic plugin in the Run/Debug configuration plugins, but I don't think VS Code can control the target platform used at runtime.
<details>
<summary>stacktrace</summary>
```
java.lang.NoSuchMethodError: 'org.eclipse.core.resources.IProject org.eclipse.m2e.core.project.configurator.ProjectConfigurationRequest.getProject()'
at org.eclipse.xtext.m2e.BinFolderConfigurator.configure(BinFolderConfigurato …
```
=> Reduce target platform size by making Xtext/Xtend requirements explicit.

org.eclipse.jdt.ls.logback.appender/src/org/eclipse/jdt/ls/logback/appender/JavaLsConfigurator.java
- Some extensions to JDT-LS may introduce 'org.apache.http' bundles which logs excessively with messages of no real value
- When jdt.ls.debug=true is passed as a system property, DEBUG logging is enabled at the root logger
In order to reproduce, let's take the vscode-java client and be sure to set `java.jdt.ls.vmargs` to include the system property `-Djdt.ls.debug=true`. Also make sure to install https://github.com/testforstephen/vscode-pde which should contain the bundle that will initiate this behaviour. Simply open eclipse.jdt.ls in the editor.
When monitoring the contents of `$HOME/.config/Code/User/workspaceStorage/${jdt-ls-workspace-id}/redhat.java/jdt_ws/.metadata/` you should be able to see as part of the import something like :
```
total 9.9M
4.0K .
4.0K ..
1004K .bak_0.log
1004K …
```
=> Reduce the amount of logging from org.apache.http bundles.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/structure/ExtractInterfaceProcessorLS.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaCodeActionKind.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/IProposalRelevance.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ExtractInterfaceHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MoveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeTemplatePreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/JavadocQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HashCodeEqualsHandlerTest.java
related to https://github.com/redhat-developer/vscode-java/pull/2836
~Some jdt.ui files (org.eclipse.jdt.internal.corext.refactoring.*) require PR: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/344, once it gets merged, I will rebase this PR to the new target platform.~ see https://github.com/eclipse/eclipse.jdt.ls/pull/2373#issuecomment-1357113174
=> support "extract interface" refactoring

.project, .vscode/launch.json, org.eclipse.jdt.ls.core/.project, org.eclipse.jdt.ls.filesystem/.project, org.eclipse.jdt.ls.filesystem/.settings/org.eclipse.core.resources.prefs, org.eclipse.jdt.ls.filesystem/.settings/org.eclipse.m2e.core.prefs, org.eclipse.jdt.ls.logback.appender/.project, org.eclipse.jdt.ls.product/.project, org.eclipse.jdt.ls.repository/.project, org.eclipse.jdt.ls.tests.syntaxserver/.project, org.eclipse.jdt.ls.tests/.project
- Add launch.json file for debugging a running JDT-LS instance
Noticed some local modifications occur when importing JDT-LS. Also wanted to add the launch.json I use to connect to a JDT-LS instance run in debug mode.
=> Update .project files from attempting project import with JDT-LS.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Related issues:
- https://github.com/redhat-developer/vscode-java/issues/2889
- https://github.com/eclipse-m2e/m2e-core/issues/1013
Requires https://github.com/redhat-developer/vscode-java/pull/2907
=> Add java.configuration.maven.defaultMojoExecutionAction

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
When auto build is disabled, we should not do a full build for the change of the configurations since it might take a lot of time. This PR fixes that.
When auto build is enabled, we should do that to keep the state of the workspace update.
=> Only do full build for configuration change when auto build enabled

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionRankingProviderTest.java
- when the item has decorators, set the filter text to avoid client takes the decorators into consideration when filtering.
fix https://github.com/redhat-developer/vscode-java/issues/2917
=> Fix the missing filter text for completion items

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
This PR is a follow-up for https://github.com/eclipse/eclipse.jdt.ls/pull/2437. When auto-build is disabled and some configurations changed, which need re-validate and publish diagnostics (e.g., null analysis configuration changed), we can do the publish job for open editors (via BaseDocumentLifeCycleHandler.publishDiagnostics) without triggering a rebuild.
https://user-images.githubusercontent.com/45906942/217752513-969d49a7-51b5-4b63-9e19-d3d1b1896c42.mp4
=> publish diagnostics when auto-build is disabled

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/BaseJDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java, org.eclipse.jdt.ls.filesystem/.classpath, org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.tests.syntaxserver/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxServerTest.java, org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
Formatting support shouldn't impact the performance of the syntax server, so it should be safe to enable.
Clients can still disable it with the java.format.enabled=false preference.
Feature was requested in https://github.com/redhat-developer/vscode-java/issues/2926
=> Enable formatting support in syntax server

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java
Fixes #2446 
We can skip generated methods when calculating the document symbols.
=>  Skip generated methods when calculating the document symbols

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
Now the debounce time of publish diagnostic jobs are adaptive. Ranging from [400, 2000] ms.
1. Add lombok dependency to petclinic project.
2. Toggle on the setting `java.trace.server` to `messages`, which will let the client print all the response time in the output channel.
3. Use this [attached file](https://github.com/eclipse/eclipse.jdt.ls/files/10694403/PetControllerTests.java.txt) to replace `PetControllerTests`.
4. Launch the language server.
> Remember to add the lombok agent to the launch file when debugging.
5. After the projects are imported and no more output can be observed in the output channel, clear the output channel.
> The project import traces are not related with this change, so we filter them out.
6. In the last method …
=> Make the debounce time of publish diagnostic job adaptive

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/IProposalRelevance.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertToTextBlockQuickFixTest.java
=> Add 'Convert String concatenation to Text Block' quick fix

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java
fix #2442, Now the additionalEdit is calculated from a fake ICompilationUnit with applying the incoming paste content, once the paste range is affecting current imports, there might be some overlap among insertText and additionalEdit. 
With this PR we only do add missing imports on paste when the pasted range is within the original primary type's source range, so that we can guarantee that there is no overlap among insertText and additionalEdit.
=> Limit add missing imports on paste for source range

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
This change fixes the performance downgrade introduced by https://github.com/eclipse/eclipse.jdt.ls/pull/2232.
1. Prepare a large java file, for example, the attached file in https://github.com/eclipse/eclipse.jdt.ls/pull/2443.
2. Manually trigger the completion via keyboard shortcut (`ctrl` + `space`) after `S`
3. A very long-time lag can be observed. While if the completion is triggered directly by typing `S`, the time is normal.
The request is the same, but at the server side, state of `SharedASTProviderCore` is different.
- When the completion is triggered directly by typing `S`, the document is changed, `SharedASTProviderCore` is not ready to give a parsed AST tree.
- When it's triggered by `ctrl` + `space`, usually the `SharedASTProviderCore` is ready
This causes the argument passed …
=> Only do context sensitive import rewrite when resolving completion items

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
If types already exist in import declarations, then the completion handler will accept them even if they've been configured in the types filter.
This change should improve the experience for users who develop AWT applications, since the whole AWT package is set in the types filter by default now.
For example, if the compilation unit contains any of the below import declarations, the `java.awt.List` will appear in the completion list:
- import java.awt.*;
- import java.awt.List;
- import static java.awt.List.*;
- import static java.awt.List.ERROR; (or any other static members from `java.awt.List`)
fix https://github.com/redhat-developer/vscode-java/issues/1147
fix https://github.com/redhat-developer/vscode-java/issues/1966
=> Accept types if they are imported when completion

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
In https://github.com/eclipse-jdt/eclipse.jdt.core/pull/679#issuecomment-1430282575 , we encountered test failures in dependent extensions (lsp4mp.jdt & quarkus.jdt). The failures implied some change to how local variable type signatures were being resolved.
While I didn't find any impact in JDT-LS, it would be good to pick up the fixes included in the more recent 4.27-I-builds (from jdt.core) to ensure we don't regress in some kind of local variable type signature logic.
=> Update target platform to latest 4.27-I-builds.

CHANGELOG.md
- Also need to add https://github.com/eclipse/eclipse.jdt.ls/pull/2467 to the list, once merged.
=> Changelog for 1.20.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/StringMatcherEx.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/TypeFilter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SimilarElementsRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
The idea comes from https://github.com/eclipse/eclipse.jdt.ls/pull/2467#issuecomment-1430924232.
This change has several benefits:
1. Quick fixes for unresolved types will also contain the types that are already imported.
2. If the package/type is used in one compilation unit, it is a hint that the package/type is used in other compilation units as well.
fix https://github.com/redhat-developer/vscode-java/issues/2943
=> Update types filter according to import declarations

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventHandlerTest.java
=> WorkspaceEventHandlerTest.testDeleteProjectFolder fails

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServerApplication.java
This block is not relevant when application is not started.
=> Move workspace preparation to application

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServerApplication.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactoryTest.java
So the plugin can be installed in other environments without messing streams
=> Move stream initialization to application

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
=> No completion on generic anonymous class instance objects

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- Only include org.eclipse.lsp4j and not bundles in the lsp4j feature
- Only include required subset of the m2e.feature.group
The real motivation for this change is I suspect some bundles being included through the m2e feature group, are severely slowing down the test runtime in Eclipse. I don't think it affects Maven. It's only Eclipse that will run a test by default, by including all bundles within the target platform.
The target platform is installed to `~/${your-jdt-ls-workspace}/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/` . To test the difference I deleted the folder between changes.
**Before this change**
783 bundles - 342MB
2.5min to run CleanUpsTest
**With this change**
685 bundles - 314MB
25s to run CleanUpsTest
=> Reduce the target platform size by eliminating unnecessary bundles.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
The only workspace operation is a potential refresh; no need to wrap it in a job that may become a blocker.
=> No need to run in workspace for didSave

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
=> Postpone wait for build job

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommand.java, org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Five.java, org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Four.java, org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/One.java, org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Six.java, org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Three.java, org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Two.java, org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Zero.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommandTest.java
- The method hierarchy for a given method of some type is a subset of the type hierarchy where methods not implemented are filtered out
- I should add some test cases for this
=> Implement method hierarchy through existing type hierarchy logic.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/CuCollectingSearchRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/ExceptionInfo.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/ParameterInfo.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/ReturnTypeInfo.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/StubTypeContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/TypeContextChecker.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/changes/CreatePackageChange.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/rename/RippleMethodFinder2.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/structure/BodyUpdater.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/structure/ChangeSignatureProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/structure/IDefaultValueAdvisor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/structure/IntroduceParameterObjectProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/corext/refactoring/structure/ParameterObjectFactory.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/internal/ui/refactoring/contentassist/JavaTypeCompletionProcessorCore.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaCodeActionKind.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/TextEditConverter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/RefactoringAvailabilityTester.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/RefactoringCoreMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/refactoring.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ChangeSignatureHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ChangeSignatureHandlerTest.java
related to https://github.com/redhat-developer/vscode-java/pull/2967, more details and demo videos can be found in that PR.
This PR includes several added files which can be excluded after https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/428 got merged. To be specific, the classes in `org.eclipse.jdt.internal` package.
test cases can be found in `ChangeSignatureHandlerTest`
=> Support change signature refactoring

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/DisassemblerContentProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2679
=> Add command to support decompiling class files

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
fix [#2938](https://github.com/redhat-developer/vscode-java/issues/2938)
=> fix duplicate results when search for *

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
- testcase should not make assumptions about result order
Seems to have started failing more frequently due to https://github.com/eclipse/eclipse.jdt.ls/pull/2547
=> Make WorkspaceSymbolHandlerTest.testProjectSearch more consistent.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java
fix https://github.com/redhat-developer/vscode-java/issues/2940
let's make "create" quick fixes in the same position. Since `rel` will make "create enum ..." at the button of "Change to ..." due to character "r" and "h". 
demo:
=> Increase relevance of "create enum"

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplate.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
This change allows the `sysout` postfix completion to be used on Objects in addition to Strings.
This PR should close https://github.com/eclipse/eclipse.jdt.ls/pull/1468 as it covers a similar use case.
=> Support java.lang.Object for sysout postfix completion

USAGE_DATA.md, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/TelemetryManager.java
- Fixes #2564 
- An accurate view of the total time would be something like (service ready elapsed time + build finished elapsed time), since project initialization is a subset of the service ready time.
=> Measure elapsed time for project initialization checkpoints.

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Maven 3.9.1 is embedded in latest m2e snapshot build, which enables jdtls to resolve dependencies in parallel.
=> Update org.eclipse.jdt.ls.tp.target to use m2e snapshot

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
=> Fix broken snippet completion after itemDefault implementation

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
* This PR also adds tests for completion with `itemDefaults` support enabled
=> Support itemDefaults in CompletionList for snippets

org.eclipse.jdt.ls.product/scripts/jdtls.py
Previously the start up script created to be friendly to package managers used the `BooleanOptionalAction` in its argument parser. This feature is only available in Python 3.9 and later. Since the script shebang in [jdtls](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.product/scripts/jdtls#L1) indicates only Python3, this change updates the script to conform with expected compatibility.
This fix was suggested by @tmmvn in [issue 2153](https://github.com/eclipse/eclipse.jdt.ls/issues/2153). This change implements that fix.
=> Make Start Up Script compatible with older Python

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
A related issue - https://github.com/redhat-developer/vscode-java/issues/2982
Steps to reproduce
```
$ git clone https://github.com/snjeza/jhipster-lite
$ cd jhipster-lite
$ code .
```
- enable lombok
- open AssertTest.java
- 
```
private void test() {
D d = new D| // try CA here
}
```
See https://github.com/redhat-developer/vscode-java/issues/2982#issuecomment-1493402938
=> Cache and re-use type bindings for a completion invocation

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
A related issue - https://github.com/redhat-developer/vscode-java/issues/2982
Steps to reproduce
```
$ rm -rf jhisper-lite
$ git clone https://github.com/snjeza/jhipster-lite
$ cd jhipster-lite
$ code .
```
- enable lombok
- open AssertTest.java
```
private void test() {
D d = new D| // try CA here
// type
Model56 model56 = new Model56();
model56.getWeight()
}
```
- check line `Validated X. Took XXX ms`
[Test vsix 1.17.3](https://github.com/snjeza/vscode-test/raw/master/java-1.17.3.vsix)
=> Avoid retrieving AST root during diagnostic publishing.

org.eclipse.jdt.ls.product/scripts/jdtls.py
Fix `IdentationError` exception thrown by Python startup script due to inconsistent mix of spaces and tabs.
=> Fix IdentationError due to mix of spaces and tabs

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxInitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
=> Implement labelDetails for CompletionItem

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
See https://github.com/eclipse/eclipse.jdt.ls/pull/2586#issuecomment-1510358912, the Java debugger was broken in the I20230405-1800 build, but fixed in the latest I20230416-0550 build.
=> Update tp to 4.28-I-builds I20230416-0550

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.tests.syntaxserver/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxServerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferencesTest.java
Related with the issue: https://github.com/eclipse/eclipse.jdt.ls/issues/2584
Client side PR: https://github.com/redhat-developer/vscode-java/pull/3070
This PR first check the resolve support for `additionalTextEdits` & `documentation`
Check for `testEdit` will come next.
=> Check additionalTextEdits & documentation resolve support via standard LSP

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Currently we use `computeAsync` and `join` the async result to handle `completion` and `resolveCompletionItem` requests synchronously. This is not quite efficient. A better implementation is to run them directly in the main dispatcher thread, which can ensure the completion is handled immediately and without waiting for another async scheduler.
=> No need to run completion handler in async thread pool

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- JDT.LS will only resolve the text edit for the snippets only when
the preference 'java.completion.lazyResolveTextEdit.enabled' is set
to true.
- If not, the 'textEdit' of the snippets will be set during
'textDocument/completion'.
requires https://github.com/redhat-developer/vscode-java/pull/3072
fix https://github.com/eclipse/eclipse.jdt.ls/issues/2584
=> Lazily resolve completion text edit according to the preference

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/JavadocCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResponse.java, org.eclipse.jdt.ls.tests.syntaxserver/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxServerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- instead of storing the uri into the data field of each completion item, now we store the uri into the CompletionResponse, and get it during resolving.
- Triggering completion via 'S' in Spring Petclinic project, the response (textDocument/completion) data size can be reduced from 3.05MB to 2.63MB. (Directly copy the trace to a text file)
=> Store the uri of document into CompletionResponse

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplate.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
Add `.syserr` postfix, to complement the `.sysout` one
https://github.com/eclipse/eclipse.jdt.ls/issues/2288
=> Add syserr postfix completion

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Relating to https://github.com/redhat-developer/vscode-java/pull/2586, the status icon could continue spinning after restarting the language server since the shutdown job is never completed. 
This change ensures that the progress report for the shutdown job is never sent to avoid this issue.
=> Prevent sending shutdown job progress report

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplateEngine.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResponse.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionRankingProviderTest.java
- Now, the server will cache the COMPLETION_EXECUTION_TIME and only set it into the data field when the item is selected in the callback function.
fix #2621 
Triggering completion via 'S' in Spring Petclinic project, the response (textDocument/completion) data size can be reduced from 2.67MB to 2.54MB. (Directly copy the trace to a text file)
=> Get rid of the duplicated COMPLETION_EXECUTION_TIME in completion items

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JsonRpcHelpers.java
As discussed in https://github.com/eclipse/eclipse.jdt.ls/issues/2518 and https://github.com/redhat-developer/vscode-java/issues/3077#issuecomment-1514418268, using scheduling rules in document lifecycle handlers can lead to deadlock and make the language server unresponsive during the build job. I propose to remove the scheduling rules from didOpen/didClose/didChange handlers for these reasons:
-  didOpen/didClose handlers are some trivial tasks, and used to open or discard a workingcopy. It should be fine not to run it with scheduling rule.
- didChange handler has two tasks: syncing the buffer with the text changes, and reconciling the Java Model with the buffer. The second reconcile/validation task was executed in a workspace job and already had a scheduling rule, so the question is …
=> No need to run didOpen/didClose/didChange with scheduling rule

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
This is a follow-up of https://github.com/eclipse/eclipse.jdt.ls/pull/2637#issuecomment-1538482123. When the operation doesn't update the resource tree, don't need a workspace runnable.
When initializing an unmanaged folder or a single external file, we can still wrap it in a workspace runnable since they need to modify the default project or the invisible project. For other operations, don't need to run them in workspace runnable.
=> Avoid running document lifecycle in a workspace runnable unless it is necessary

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandlerTest.java
- The signature information is not needed to store in the completion item data field. It can be retrieved from the proposal that stored in the completion response cache.
fix #2645 
fix #2638 
Complete after a string variable. the response data can be reduced from **83.7KB** to **70.4KB**
=> Remove unnecessary completion item data field

org.eclipse.jdt.ls.product/scripts/jdtls.py
Fixes #2615 
* `subprocess.run` is used in the case when the OS is windows to ensure that the parent process (python script) is alive after starting up the language server
=> Use subprocess.run in jdtls script on Windows

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventHandlerTest.java
See https://github.com/eclipse/eclipse.jdt.ls/issues/2518#issuecomment-1538440813, executing the file event handler in the default dispatch thread may block the jsonrpc reader. To avoid the deadlock, use a separate thread to handle didChangeWatchedFiles events.
=> Use separate thread to handle didChangeWatchedFiles events

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
This is a follow-up on [#2518 (comment)](https://github.com/eclipse/eclipse.jdt.ls/issues/2518#issuecomment-1541414263).
As shown in the callstack below, the default `refreshLocal` implementation uses two locks: a scheduling rule for jobmanager concurrency and a workspace lock for workspace tree modification. The workspace lock is essential to prevent the workspace tree from being corrupted during refresh. We can try setting the scheduling rule to null for `refreshLocal` in documentLifecycleHandler, since it only refreshes the current Java file and has a limited scope. I tested the new refresh approach with use cases such as creating, renaming and saving a Java file, it works fine.
```
- Call Stack:
File.refreshLocal(int,IProgressMonitor) File.class:316 …
```
=> Avoid blocking the pipeline while handling refreshLocal during document lifecycle events

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
The validation/diagnostics job is used to update the Java model structure with the workingcopy buffer contents. Since it does not modify the underlying resource, it should be fine to run in a regular job instead of a workspace job. A workspace job is meant for operations that modify the workspace resource, as per the Eclipse [WorkspaceJob spec](https://help.eclipse.org/latest/nftopic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/resources/WorkspaceJob.html) and [Concurrency and the workspace](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2FresAdv_concurrency.htm). Similarly, the [Java Reconciler job](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/4e0851bc6c1659cd75585422afc53cb317c4ff54/org.eclipse.jdt.ui/ui/org/eclipse/jdt/intern …
=> No need to run the reconcile operation in WorkspaceJob

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/ValidateDocumentParams.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
This PR introduces a workspace setting `java.edit.validateAllOpenBuffersOnChanges` that allows users to choose the diagnostics strategy for unsaved changes when editing a Java file.
- **Strategy 1**: Validate all open Java files (workingcopies) in the editor for errors when you're typing in a Java file. The advantage of this strategy is that it can detect errors quickly if the current changes affect other open Java files. The drawback is that it can be costly to validate all open buffers on every change.
- **Strategy 2**: Validate only the current Java file for errors when you're typing. This strategy can use less CPU resources and respond faster if the changes introduce errors. However, it may not report potential errors in other Java files right away. If the client prefers strategy 2, …
=> Avoid validating all opened workingcopies when didChange a document

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- When the completion is a constructor, we need to get the first char
from the required proposal instead of the main proposal.
fix https://github.com/redhat-developer/vscode-java/issues/3118
=> Fix the constructor completion not working when match case turned on

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
Reverts eclipse/eclipse.jdt.ls#2673
Looking at https://ci.eclipse.org/ls/job/jdt-ls-master/1699/, https://ci.eclipse.org/ls/job/jdt-ls-master/1700/ it seems to be failing so let's revert for now and merge after the release.
=> Revert "[lombok] No completions on field initializer"

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
Fixes [#2011 ](https://github.com/redhat-developer/vscode-java/issues/2011)
=> Make a reasonable guess for the name of the extracted method

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
fix https://github.com/redhat-developer/vscode-java/issues/3127
=> Show signature help according to the last selected completion item

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes https://github.com/redhat-developer/vscode-java/issues/3138
A related issue - https://github.com/eclipse-jdt/eclipse.jdt.core/issues/934
=> Update target platform to 4.28 I20230605-0440

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplate.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
=> Add postfix completion for sysouf, sysoutv, format, par, and not

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
The original implementation might encounter situation that the `pId` mismatching between proposal and completion item.
When the exception happens and caught. In that case, all the completion proposals will be stored into the response cache. While, only successfully resolved items will be stored.
-----
Another part we can consider is that: is the try-catch block needed here. Looks like the invoked methods will not throw Exceptions in their signatures. Maybe @snjeza can provide more information. Related PR: https://github.com/eclipse/eclipse.jdt.ls/pull/1314/files
=> Fix pId mismatch bug in completion

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/PostfixTemplate.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java
Additions:
- Added support for adding an assert statement
- Added support to create Optional.ofNullable(..) call.
Related #2288
=>  Add assert & optional completion support

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionGuessMethodArgumentsMode.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferencesTest.java
- Change the option of 'java.completion.guessMethodArguments' from boolean to three options: "off", "insertParameterNames" and "insertBestGuessedArguments".
- When it's "off", no arguments will be inserted during completion. Moreover, the constructors will be collapsed into one item in the completion list.
requires https://github.com/redhat-developer/vscode-java/pull/3143
fix https://github.com/eclipse/eclipse.jdt.ls/issues/2512
Some pref data about completion with different mode, the completion happens with `List<String> l = new A|`:
  | off | insert parameter names | insert guessed arguments
-- | -- | -- | --
#1 | 3291 | 3922 | 3739
#2 | 1174 | 1158 | 1221
#3 | 880 | 1201 | 1097
#4 | 888 | 1095 | 1038
#5 | 806 | 986 | 1010
#6 | 801 | 1025 | 996
#7 | 791 | 1029 | 993
#8 | 843 | 1062 | …
=> Support 'off' mode when fill the argument during completion

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/LambdaExpressionAndMethodRefCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/IProposalRelevance.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertMethodReferenceToLambdaTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LambdaQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
Fixes #2489
* adds quick fix to convert lambda block to expression when there is exactly one statement within the block
=> Add quickfix to convert lambda block to expression

org.eclipse.jdt.ls.core/.classpath, org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/build.properties, org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/pom.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/DecompilerResult.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/IDecompiler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/decompiler/DecompilerImpl.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/decompiler/DecompilerType.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/decompiler/FernFlowerDecompiler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ContentProviderManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToTypeDefinitionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ReferencesHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ContentProviderManagerTest.java
This PR does the following:
- It replaces the default disassembler `ClassFileBytesDisassembler` with `fernflower` decompiler, which provides better decompilation results.
- It records the line mappings when decompiling class file, which is needed by the debugger to re-map the line numbers when a breakpoint occurs.
=> Use fernflower as the default decompiler

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Fixes #2716
After fixing the two syntax errors, another error was surfaced, which is that we were missing an import for `org.eclipse.m2e.core.internal.Messages`.
Additionally, when I ran the test with the syntax errors fixed, I noticed that `testProjectLevelMarkers` fails. It seems like it just needs to be updated (diagnostics have changed slightly), but no one noticed since the test case assertions never ran, due to the ECJ bug (see #2716). Let me know if the changes I made to update the test assertions seem correct.
=> Fix syntax errors in WorkspaceDiagnosticsHandlerTest

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServerApplication.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
As per API, the progressManager should be set by the owning application only and plugins mustn't modify it.
In Eclipse Workbench, overriding it with the implementation in JDT-LS cause infinite threads consumption since
348252b6fa3d61d02145707d0f6d244c57ddf1fa
=> Set progressManager in application

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServerApplication.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Keep the progressReportManager where it is, but set it only as default one for JobManager in the application.
This reverts and adapt commit 844ef8684925b0b5d2e521db0ce3c2d7b9dfa9c6.
=> Re-Set progressManager in application

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/ChainCompletionProposalComputer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerChainTest.java
Bring chain completions support to JDT.LS which was started by @rgrunber. I clean it up a little bit and add 
- Support for overloaded methods where expected type signatures in the context is more than one.
- Some support suggesting chain completions using static methods in classes like `Collectors` as a POC. The idea is to improve the this to read from a simple model file where either Microsoft IntelliCore (cc: @jdneo @testforstephen) can provide or any other interested extension provider. We need to discuss the best way to provide this as a extension point for providing model information (cc: @rgrunber @mickaelistria @fbricon )
=> Add chain completions support

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/LambdaExpressionCleanup.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AnonymousClassCreationToLambdaTest.java
- Update target platform to I20230615-1800
See https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/230
When the following command request is made :
```json
{
message: "[Trace - 11:25:11] Sending request 'workspace/executeCommand - (9)'.",
level: 'info',
timestamp: '2023-06-27 11:25:11.077'
}
{
message: 'Params: {\n' +
'    "command": "java.project.getSettings",\n' +
'    "arguments": [\n' +
'        "file:///home/rgrunber/sample-projects/null-analysis-app/",\n' +
'        [\n' +
'            "org.eclipse.jdt.core.compiler.source",\n' +
'            "org.eclipse.jdt.ls.core.vm.location"\n' +
'        ]\n' +
'    ]\n' +
'}\n' +
'\n',
level: 'info',
timestamp: '2023-06-27 11:25:11.077'
}
```
The response for `"org.eclipse.jdt.ls.core.vm.location"` is something like : …
=> Attempt automatic JVM detection on startup

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/TelemetryManager.java
Add more trace to understand the language server status:
- Measure the import success rate. The indicator we can use is the error diagnostics. If the project root level has error or the Java file has unresolved import errors, we can count it as an import failure. 
- Detect the cases of jdk mismatch.
=> Add more trace to understand the project import success rate

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
- Early return if the completion proposal is not compatible with the expected type.
=> Check completion proposal is compatible or not.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/VariableQuickFixTest.java
Add support for Split and Join variable quick actions with Unit Tests.
=> Add support for Join and Split variable quick actions.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
Fixes #2711 
Fixes tests with the `Resource '/TestProject/bin' already exists.` message.
=> Java LS tests fail randomly

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
Retrieve the document symbols by visiting the ASTTree of the decompiled source.
=> Support outline view for decompiled source

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IBuildSupport.java, org.eclipse.jdt.ls.tests/projects/eclipse/classpath3/.classpath, org.eclipse.jdt.ls.tests/projects/eclipse/classpath3/.project, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/filesystem/EclipseProjectMetadataFileTest.java
Running JUnit Plugin Tests of `org.eclipse.jdt.ls.tests` in VS Code causes Java extension to delete javanature from `.project` file of `org.eclipse.jdt.ls.tests` project. This is because the test framework removes temporary test projects (e.g. `eclipse.jdt.ls/org.eclipse.jdt.ls.tests/target/workingProjects/maven/salut/.classpath`) after testing, which triggers a .classpath delete event as part of `didChangeWatchedFiles` event. The language server then deletes javanature of the parent project when it detects a .classpath delete event. This is annoying when you dogfood eclipse.jdt.ls development in VS Code.
Here are the reproducing steps:
1. Open the following eclipse-project in VS Code
```
eclipse-project
│   .classpath
│   .project
└───resources
.classpath
```
2. Delete `.classpath` file …
=> Should not delete the project javanature when removing a nested .classpath resource file

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ChangeSignatureHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ChangeSignatureHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3098
=> Fix param and exception addition/deletion in method signature refactoring

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
Fixes 
- https://github.com/redhat-developer/vscode-java/issues/3184
- https://github.com/redhat-developer/vscode-java/issues/3032
Test vsix - [VSCode 1.22.0](https://github.com/snjeza/vscode-test/raw/master/java-1.22.0.vsix)
=> Unable to acquire the state change lock for the module 'buildship'

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
Related to #1918
Related to redhat-developer/vscode-java#2176
This PR fixes (only partially, see discussion below) #1918 via "Option C" described in this comment: https://github.com/eclipse/eclipse.jdt.ls/issues/1918#issuecomment-1597858838
This PR is an alternative to #2709. I believe there are some problems with that workaround, see https://github.com/eclipse/eclipse.jdt.ls/pull/2709#issuecomment-1597033037
To my knowledge, this PR should fix `#1918` completely, ~~without any edge cases.~~ *This was not the case, see review comments in the discussion below.*
=> Prevent caching outdated AST in CoreASTProvider

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandler.java
- There are chances that the AST used for semantic highlighting is out-of-date, which leads to wrong highlighting. This fix simply compares the length of the document with the length of the AST to check if the AST is out-of-date. In most of the case, checking the length is enough, this is guaranteed by the current implementation that document change event is handled in a blocking manner, so the buffer length is always right.
- For root cause analysis, see: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1151
fix #1918 
fix https://github.com/redhat-developer/vscode-java/issues/2176
fix https://github.com/redhat-developer/vscode-java/issues/3147
Openning a relatively complex java file, e.g. BaseDocumentLifeCycleHandler. Then keeping pasting/removing multiple lines of code, like …
=> Fix wrong semantic highlighting due to out-of-date AST being used.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/EventType.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SourceAttachUpdateHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ISourceDownloader.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenSourceDownloader.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SourceAttachUpdateHandlerTest.java
This PR enables switching between decompiled source and original source jar. For example, when you go to a maven library, the language server will try to download its source jar asynchronously. However, the language server will only wait for the download job for 3 seconds. If the source jar is downloaded within that time, it will use the source jar directly. Otherwise, it will use the decompiled source. This works fine for the backend language server, as it will automatically switch to the original source jar when it is ready. But it causes a problem for the client, because the client will cache the class file contents in editors from the first request. This will make the client and server see different sources for class files.
To solve this problem, this PR will send a …
=> Send a SourceInvalidatedEvent to client when source attachment is updated for jar libraries

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SmartDetectionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SmartDetectionParams.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/BufferedDocumentScanner.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/FastJavaPartitionScanner.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/FastJavaPartitioner.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/FastPartitioner.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/ICharacterScanner.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/IJavaPartitions.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/IPartitionTokenScanner.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/IToken.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/ITokenScanner.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/Token.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SmartDetectionHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/703
Requires https://github.com/redhat-developer/vscode-java/pull/3159
=> Smart semicolon autocorrect

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandler.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/CallHierarchyGH2771.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandlerTest.java
The issue is when the second call hierarchy call hits the handler, it comes with the line and char positions based on the range which was resolved from the first call. In the example mentioned in the issue that particular position is resolved to type `Optional` instead of the method `name()` by the CU.codeSelect. 
This works fine when we have `public` at start of the method definition since it doesn't resolve to a element, the CU.codeSelect returns the next best match which Is the method.
The fix try to see if we are trying to do a codeSelect at the start of the line and if so, it tries to find the element by offset if the found element is is a type to see if we can find a method of a field to eliminate the above scenario.
=> Fix call hierarchy position resolution #2771

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java, org.eclipse.jdt.ls.tests/projects/gradle/apt/build.gradle, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
- Use String.valueOf() to avoid type casting error.
fix #2781
=> Fix the compiler arguments parsing failure

org.eclipse.jdt.ls.logback.appender/src/org/eclipse/jdt/ls/logback/appender/JavaLsConfigurator.java
When having `-Djdt.ls.debug=true` set for `java.jdt.ls.vmargs` and importing a project like LemMinX, I noticed the logs would get very large. Approximately 1.5MB in size after just the initial import. I also think it's made worse by the fact that some of the log messages here, are sent on rebuild. I also believe they slow down other operations.
```
!ENTRY org.eclipse.jdt.ls.logback.appender 1 0 2023-07-31 14:41:50.190
!MESSAGE parseClassFile(): path=org/eclipse/lemminx/extensions/colors/utils/ColorUtils.class resource=/home/rgrunber/git/lemminx/org.eclipse.lemminx/target/classes/org/eclipse/lemminx/extensions/colors/utils/ColorUtils.class
...
...
ENTRY org.eclipse.jdt.ls.logback.appender 1 0 2023-07-31 14:41:52.424
!MESSAGE visitClassFile(): …
```
=> Filter out excessive logging of classfile parsing from m2e in "debug mode"

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Fixes https://github.com/redhat-developer/vscode-java/issues/3232
A related PR - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1265
=> Update target platform to I20230806-1800

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ProgressReporterManagerTest.java
Adds the appropriate check for the workDoneProgress client capability according to the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverInitiatedProgress).
=> Add check for workDoneProgress client capability

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Following the remark on https://github.com/redhat-developer/vscode-java/issues/3242#issuecomment-1674583851, I'm updating the Annotation attritbutes to use the `CompletionItemKind.Property` kind.
Before:
After:
As well as use the more apt `CompletionItemKind.Struct` kind for records
Before:
After:
=> Update CompletionItemKinds for annotation attributes and records

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandler.java, org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/NestedSwitchFoldingRange.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandlerTest.java
Fixes redhat-developer/vscode-java#2751
Normal (not collapsed):
Before fix:
After fix:
=> Fix folding ranges for nested switch statements

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandlerTest.java
Fixes redhat-developer/vscode-java#1444
Before:
After:
=> Fix multiline semantic highlighting for 'record'

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/IDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Fixes #2799
Fixes https://github.com/redhat-developer/vscode-java/issues/3199
=> Improve performance of code actions, and certain delegate commands

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.tests/projects/maven/semantic-tokens/src/main/java/foo/Constructors.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandlerTest.java
=> Fix multiline semantic highlighting for 'class' and 'interface'

org.eclipse.jdt.ls.product/scripts/jdtls.bat
Hi, after adding jdtls bin to PATH variable on windows you can't run the lsp server because they are python scripts. I know you can use the java command but then you would need to use a different command for Linux and Windows and it requires you to set the options manually.
Adding a simple batch file to the bin directory allows it to be run from path on Windows with just "jdtls". I think putting it in scripts directory would copy it there? Didn't build it myself.
This change is important for editors, particularly for https://github.com/helix-editor/helix/blob/master/languages.toml#L36 to be able to work out of the box.
Discussion about this here https://github.com/helix-editor/helix/discussions/5861.
=> Support python wrapper for Windows

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/TypeHierarchyHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/TypeHierarchyHandlerTest.java
But keep legacy command which is still used by vscode-java.
Also-by: Mickael Istria <mistria@redhat.com>
=> Add support for LSP-standard TypeHierarchy

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
This seems to fix the issue mentioned in https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2769#issuecomment-1690887502 and it was something I noted originally as the proper approach.
=> Respect client capabilities for type hierarchy.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtilsTest.java
- When the Gradle Java home preference is not set, and the default JDK is not compatible with the project Gradle, try to find compatible JDK if there is one available.
=> Select suitable JDK to launch Gradle.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/gradle/null-analysis/src/main/java/foo/bar/TestJDT.java, org.eclipse.jdt.ls.tests/projects/gradle/null-analysis/src/main/java/foo/bar/TestJavax.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/NullAnalysisTest.java
Fixes redhat-developer/vscode-java#3255
=> Set default of syntactic null analysis for fields to enabled

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandler.java
- When a particular MethodWrapper is queried again for its method calls (eg. incoming/outgoing), it does not report progress
- Use the IProgressMonitor String representation to determine if the MethodWrapper updated progress, and report it as done if not
```
package org.example;
public class Test {
public static void main(String[] args) {
doSomething();
doSomething();
}
private static void doSomething() {
}
}
```
1. Invoking call hierarchy on the `doSomething` method declaration (at the bottom) and it will produce 2 child elements under the `main` node.
2. Expand one of the `doSomething` elements causes the computation to occur and progress is reported
3. Expanding the other `doSomething` element simply uses the cached `MethodWrapper`, which won't report progress.
The result (eg. in VS …
=> Correctly report completed progress for subsequent MethodWrapper calls.

org.eclipse.jdt.ls.product/languageServer.product, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
=> Fix Java LS logging

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandlerTest.java
Fixes redhat-developer/vscode-java#3181
The `StringEscapeUtils.escapeJava()` method from the Apache library escapes Unicode characters as `\uXXXX`, which is not our desired behavior. We modified the method to preserve Unicode characters.
=> Don't escape unicode characters when pasting string literals

org.eclipse.jdt.ls.logback.appender/src/org/eclipse/jdt/ls/logback/appender/JavaLsConfigurator.java
- Fixes #2837 
- Prevent additional logging configurators from disturbing standard output
=> Do not invoke additional configurators after the Java LS Configurator.

CHANGELOG.md
I've set the release for Tuesday, given I'm a bit late with the CHANGELOG. Some time was spent trying to get to the bottom of the m2e regression. Also, I wouldn't mind spending some time to more thoroughly investigate the "Content-Length" behaviour.
=> Changelog for 1.27.0

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/DiagnosticsCommandTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/NonProjectFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionInsertReplaceCapabilityTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListenerTest.java
- I20230912-1800
Today is Eclipse 2023-09 (4.30) GA, so they've removed https://download.eclipse.org/eclipse/updates/4.29-I-builds/, ~~but https://download.eclipse.org/eclipse/updates/4.29/ isn't yet in place, which means I have to bump to 4.30-I-builds. There shouldn't be anything to cause issues.~~
It would be ideal to use updates/4.29, since I20230806-1800 is just a week before 2023-09 M3 but if we need to build now this should also work.
**Update:** Nevermind. I see https://download.eclipse.org/eclipse/updates/4.29/ exists. I was wrongly waiting for 4.30 which definitely isn't going to be released :rofl: 
CC: @testforstephen
=> Update target platform to 4.30-I-builds.

CHANGELOG.md, org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.core/pom.xml, org.eclipse.jdt.ls.filesystem/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.filesystem/pom.xml, org.eclipse.jdt.ls.logback.appender/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.logback.appender/pom.xml, org.eclipse.jdt.ls.product/pom.xml, org.eclipse.jdt.ls.repository/pom.xml, org.eclipse.jdt.ls.target/pom.xml, org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.tests.syntaxserver/pom.xml, org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.tests/pom.xml, pom.xml
I needed to include this update because https://download.eclipse.org/eclipse/updates/4.29-I-builds/ is gone (4.29 went GA and they clean the I-build repo immediately), so we needed an update to 4.29 Release to do a rebuild.
Longer term, being able to rebuild by packaging from the milestones (eg. https://download.eclipse.org/jdtls/milestones/1.27.0/ ) would have solved this, but we rarely need this.
=> Changelog for 1.27.1

README.md
As discussed in https://github.com/eclipse-jdtls/eclipse.jdt.ls/discussions/2852 .
=> Mention in README the minimum required JRE (17) to run language server.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/JavaContextType.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes redhat-developer/vscode-java#725
Before:
After:
=> Correct constructor snippet for additional classes in a file

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/TelemetryManager.java
- Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2842
=> Pass the projects manager to the telemetry manager in a safer manner.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/src/main/java/org/sample/Test2.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3203
=> F2 rename of Lombok @Singular attribute does nothing

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes redhat-developer/vscode-java#1697, including the removal of the ctor snippet within an interface, the modification of the method snippet (removal of the method body, protected choice, and static choice), and the addition of a static_method snippet with a method body.
Before:
After:
=> Update current method snippet and add static_method snippet for interface

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandler.java, org.eclipse.jdt.ls.tests/projects/maven/foldingRange/src/main/java/org/sample/NestedSwitchFoldingRange.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandlerTest.java
=> Add isEmpty() check to avoid java.util.EmptyStackException in FoldingRangeHandler

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/DocumentAdapter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandlerTest.java
The makes that the documentSymbols (and probably some other requests) capable of processing files that are not imported in any way in the workspace.
It consists of mainly
* Adding capability to create an ICompilationUnit for those files
* Adding extra-logic to resolve an URI for ICompilationUnit that are not backed by an IFile.
Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2809
=> documentSymbols to work for Java files that are not resources

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
java.lang.NullPointerException: Cannot invoke
"org.eclipse.jdt.core.IType.getClassFile()" because "type" is null
at org.eclipse.jdt.ls.core.internal.JDTUtils.getClassFile(JDTUtils.java:492)
at org.eclipse.jdt.ls.core.internal.JDTUtils.discardClassFileWorkingCopy(JDTUtils.java:478)
at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.hover(HoverHandler.java:51)
This happens in eclipseide-jdtls, when skipProjectConfiguration=true , and causes an error response when decent response can be returned here.
=> Fix NPE in JDTUtils.getClassFile()

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/DocumentAdapter.java
This integrates better with other bits of Eclipse Platform and allows native synchronization between editor and LS in case LS runs in same workspace.
Also, the FileStore API provides some convenient features that may improve also synchronization with external changes.
=> Use Eclipse FileStore for external files

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes #2705 and redhat-developer/vscode-java#3206
Before:
After:
Note that the completion suggestions disappear after a space is typed in the parameters, though this issue was present before the addition of labelDetails that introduced the original bug in #2705.
Additionally, even with this fix, the highlight does not persist past the entry of `(`, though this is likely a client-side issue.
=> Fix order and filtering of completion items for overloaded methods

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java
- Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2891
=> Add empty '$/setTrace' to avoid UnsupportedOperationException.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ProjectConfigurationUpdateHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ProjectConfigurationUpdateHandlerTest.java
- A new API 'onWillUpdate()' is added to IBuildSupport, which can be used to do some preparation work before updating the project configuration. For example: For the Build Server support, send a reload request to Build Server, then do the real update task in 'update()'.
- When a bunch of projects need to be updated, extract out the invocation of 'registerWatchers()' and 'updateEncoding()'. See: ProjectsManager#updateProjects(Collection<IProject>, boolean force).
=> Add new API 'onWillUpdate()' to IBuildSupport

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2884, https://github.com/redhat-developer/vscode-java/issues/3186, and https://github.com/redhat-developer/vscode-java/issues/3214.
=> Fix first letter matching for method overrides

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerLazyResolveTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes redhat-developer/vscode-java#2584
Before:
After:
=> Move snippet suggestions above keywords in completion list

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerChainTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
We assume that users who have static imports in their Java files want to use them more often. Therefore, we suggest to automatically detect and add these static imports to the favorite static members whitelist when they edit the files. This will enhance the smartness of the Java language server.
=> Automatically add the existing static imports in user code as the favorite static members

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewCUProposal.java
With `java.templates.fileHeader` defined. When a type is annotated as `SampleClass cannot be resolved to a Type`, the `Create {class|interface|enum} SampleClass` code action produces : 
This regressed in https://github.com/eclipse-jdtls/eclipse.jdt.ls/commit/d8e523664639a4e8ccc62200302e30d7e53c9252#diff-253491dd873df873b33c21cb35ead8d713dd6ac01d2a5b0d2cf91ce5b3f942b9R122 . I must have tried to make all templates containing `${filecomment}${package_declaration}` look the same, and so removed the newline from the "newtype" template, not realizing we manually add a line delimiter for the snippet type declaration templates but not for "newtype"
- When a file header template is defined there should be a line delimiter between it and the package declaration (or type declaration)
=> Ensure line delimiter exists after the file header template.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetector.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetectorTest.java
Fixes redhat-developer/vscode-java#3137
Fixes redhat-developer/vscode-java#1156
Fixes #2855
=> Log and continue when the importer scanner encounters a directory that is inaccessible or does not exist

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
=> Fix filterText and sorting for method declaration completions

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixes #2845
It's a Windows specific bug. The root cause for the error 'Invalid project description' is that some importer fails to exclude the already imported projects during scanning, and attempts to import the same projects again. The fix is to exclude the already imported projects from scanning by using valid glob patterns for Windows paths.
=> Fix the error 'Invalid project description' caused by incorrect glob patterns for Windows paths

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2250
=> Reconcile AST node to provide accurate type definition snippets

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandler.java
=> Check for null root in SemanticTokensHandler

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
This PR adds a "Surround with try/catch" proposal to the `RefactorProcessor`. That way, one can surround a block of code (selection range) with a try/catch block. This is especially useful when one is guarding against `RuntimeException`s.
The code in RefactorProcessor.getSurroundWithTryCatchProposal was based on `LocalCorrectionsSubProcessor.addUncaughtExceptionProposals`.
=> "Surround with try/catch" Code Action

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Implements solution proposed in https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2918#issuecomment-1774367339.
=> Add new aliases for sysout and syserr snippets

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.tests/projects/maven/semantic-tokens/src/main/java/foo/Types.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandlerTest.java
Fixes #2920
I added some helper functions for making sure that we only scan the gap between the AST nodes (to avoid overlapping/out-of-order tokens). The more general helper functions can be used in the future if we discover more "gaps" in the AST that we need to scan.
=> Fix wrongly encoded semantic tokens around class keyword

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
- Fixes https://github.com/redhat-developer/vscode-java/issues/3370
When a set of cleanup actions are requested through the LSP, they should take priority over those set through the project's .settings/org.eclipse.jdt.core.prefs.
=> Do not mix cleanup actions from LSP with those set in the project.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BundleUtils.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3349
=> Avoid refreshing bundles whose dependency closure includes JDT-LS.

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferencesTest.java
Internal packages are no longer exported in the Maven artifact (https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar)
- old Orbit artifact exported everything but it's being phased away and the upstream artifact is being used in simrel.
Furthermore the test itself doesn't need neither insert order nor sorting so a plain HashMap is sufficient.
=> Stop using Gson internal LinkedTreeMap in tests

org.eclipse.jdt.ls.product/languageServer.product, org.eclipse.jdt.ls.product/syntaxServer.product
This fragment is empty one and just requires o.e.core.net.win32 one.
=> Stop including o.e.core.net.win32.x86_64 fragments in products

org.eclipse.jdt.ls.product/languageServer.product, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Benefits are:
* Use upstream bundle id
* No longer refer to 4.29 updates
* Move to latest version of commons-codec
=> Update commons-codec to 1.16.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
- Group the configuration files by file names and import them group by group, and
make sure one project type will only be imported by one importer.
=> Import projects by configurations

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3380
=> Add maven.multiModuleProjectDirectory property

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
- Fixes #2975
- Fixes https://github.com/redhat-developer/vscode-java/issues/3399
- If a project has an 'org.eclipse.jdt.ui' preference node (eg. .settings/org.eclipse.jdt.ui.prefs), for clean up fixes, only use it if the client has set the 'canUseInternalSettings' extended client capability
- Fix testNoConflictBetweenLSPAndJDTUI testcase
=> Use project's Eclipse settings if extended client capability permits.

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/VmCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/VmCommandTest.java
Two delegate command is added:
`java.vm.getAllInstalls` - Get all vm installs.
`java.project.updateJdk` - Update the given project's jdk.
They will be used by the configure classpath webview at client side.
related with https://github.com/microsoft/vscode-java-pack/pull/1263
=> Add capability to list all vm installs and update project jdk

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/EventType.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
requires https://github.com/redhat-developer/vscode-java/pull/3398
=> Support add/remove imported projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SimilarElementsRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java
Fixes #2955, see that issue for the detailed explanation on the root cause.
=> Fix the document out-of-sync due to multi threads changing the current workingcopy buffer

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2925
=> Allow package/module references to bypass strict character matching

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
This introduces the following notable improvements :
- [21] JEP 430 String Templates support
- Performance improvement for "Organize Imports" when it calls "getStaticImportFavorites"
- Various refactorings to make API more accessible in jdt.core.manipulation
- Fixes https://github.com/redhat-developer/vscode-java/issues/3383
=> Update target platform to latest 4.31-I-builds.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java, org.eclipse.jdt.ls.tests/projects/maven/semantic-tokens/src/main/java/foo/Constructors.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandlerTest.java
Addresses https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2920#issuecomment-1788029479
Before:
After:
=> Fix multiline semantic highlighting for 'implements', 'extends', and 'permits' keywords

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertMethodReferenceToLambdaTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LambdaQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/VariableQuickFixTest.java
Add new quick fixes namely
- ChangeLambdaBodyToBlock
- ChangeLambdaBodyToExpression
- ConvertLambdaToMethodReference
- AddInferredLambdaParameterTypes
- AddVarLambdaParameterTypes
- RemoveVarOrInferredLambdaParameterTypes
- InvertEqualsExpression
=> Add support for new headless quick fixes from upstream

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java
Adds a delegate command that identifies whether or not some given clipboard text is a piece of java text and returns the correct path to the file to be created given relevant package declarations and/or type name.
Addresses https://github.com/redhat-developer/vscode-java/issues/3323.
=> Introduce delegate command for java file paste

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.filesystem/src/org/eclipse/jdt/ls/core/internal/filesystem/JDTLSFilesystemActivator.java, org.eclipse.jdt.ls.filesystem/src/org/eclipse/jdt/ls/core/internal/filesystem/JLSFile.java, org.eclipse.jdt.ls.filesystem/src/org/eclipse/jdt/ls/core/internal/filesystem/JLSFsUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/filesystem/JLSFsUtilsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2972
Steps to Reproduce:
See https://github.com/redhat-developer/vscode-java/issues/2972#issuecomment-1844050065
Test vsix - [VS Code 1.27.3](https://github.com/snjeza/vscode-test/raw/master/java-1.27.3.vsix)
=> Cannot import maven project from workspace

org.eclipse.jdt.ls.logback.appender/src/org/eclipse/jdt/ls/logback/appender/JavaLsConfigurator.java
See https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2420, https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2785 for some background on what the problem is.
When opening a Maven project whose contents have never been downloaded to the local repository (eg. a clean `$HOME/.m2/repository`), and with the system property `jdt.ls.debug=true` enabled (most commonly in `java.jdt.ls.vmargs` via. `-D`), the client and server logs will be overwhelmed with **many** messages of the form :
**client log**
```
[Info  - 13:39:08] Jan. 4, 2024, 1:38:35 p.m. http-outgoing-1 << "[0x0][0x0][0x8][0x0][0x0]N[0xb0][0xab]V[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0];[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0xed]A@[0x1][0x0][0x0]META-INF/maven/org.codehaus.mojo/build-helper- …
```
=> Filter excessive logging of artifact download from m2e in "debug mode"

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/WrapperValidator.java, org.eclipse.jdt.ls.tests/projects/gradle/no-gradlew/gradle/wrapper/gradle-wrapper.properties, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
In `GradleProjectImporter`, the previously implementation will use `GradleDistribution.fromBuild()` when the `gradlew` exists.
While checking the source of Gradle, the Gradle tooling api will check `gradle/wrapper/gradle-wrapper.properties` instead of the `gradlew`.
See: 
- https://github.com/gradle/gradle/blob/592f269cc959c3620413391e1dad68695e7adad2/platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DefaultGradleConnector.java#L169C48-L169C70
- https://github.com/gradle/gradle/blob/592f269cc959c3620413391e1dad68695e7adad2/platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DistributionFactory.java#L59C59-L59C59
- https://github.com/gradle/gradle/blob/592f269cc959c3620413391e1dad68695e7adad2/platforms/core-runtime/wrapper-shared/src/main/ …
=> Use wrapper distribution when gradle-wrapper.properties exists.

CHANGELOG.md
- I've listed https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2985 as "known regression". I don't think we've ever included things we know will break into the CHANGELOG, but is there a reason not to include that (in addition pinning the issue after release) ?
- https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2994 is mentioned twice because although it's a target platform update, it contained both some basic String templates support, and a performance improvement to "Organize Imports". Felt like the 2 deserved their own entries.
=> Changelog for 1.31.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RenameSupport.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ImplementationsHandlerTest.java
@akurtakov mentioned this is needed for eventually merging https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2963 .
=> Update target platform to latest 4.31-I-build.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AddMissingMethodDeclarationQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
Replace the LS specific implementation with the headless implementation from jdt.core for adding missing method reference quick fix proposals.
=> Use AddMissingMethodDeclarationFixCore from jdt.core.manipulation. 

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
- Fixes redhat-developer/vscode-java#3466
This approach should be ok because we don't seem to use the token value at all when calculating generic snippets. Also, a similar approach in https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/8f0f822a89bf1f6109a9d95d048e7b53110df19f/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/JavadocCompletionProposal.java#L85 .
=> Allow generic snippets to be computed when completion token is null.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3393
Requires https://github.com/redhat-developer/vscode-java/pull/3440
=> Add support for externally provided 'lifecycle-mapping-metadata.xml' file

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
Can be used by other extensions to get the project type.
=> Support get project nature ids

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
- Unnamed classes (JEP 445) has changed diagnostics reported on invalid class declarations
**Before JEP 445**
**With JEP 445**
CC'in @datho7561 for awareness. We should probably run the JDT-LS tests as part of updating the incubator to avoid any surprises.
=> Adjust testcase due to differing diagnostics from JEP 445.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/NullAnalysisTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3501
=> Set o.e.j.c.compiler.problem.nullUncheckedConversion to ignore by default

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2282
Before:
After:
The list of methods should ideally be displayed in signature help after selecting the completion item, though there exists a [bug](https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3052) in which this isn't always the case.
=> Introduce completion item collapse for method overloads

org.eclipse.jdt.ls.product/scripts/jdtls.py
In Windows when I have the JAVA_HOME environment variable, the language server does not use the java version defined in JAVA_HOME. I found out that the python script section that get the java executable has a bug: in Windows the java executable ends with `.exe` but the script does not take it into consideration.
I tested this only by using it through Neovim with `nvim-jdtls` plugin (only on Windows). Also this might be a breaking change for all Windows users as they will use a new java executable if this is fixed.
=> Fix python script to retrieve JAVA_HOME exec in Windows OS

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JdtDomModels.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Child.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/Parent.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/2639
Requires https://github.com/redhat-developer/vscode-java/pull/3495
=> Add methods,inherited fields,inherited methods to Generate toString()

org.eclipse.jdt.ls.product/scripts/jdtls.py
Our project is stuck on JDK 11 and my build env. must point to this archaic JDK, which is insufficient for JDTLS. 
I found the script [org.eclipse.jdt.ls.product/scripts/jdtls.py ](https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.product/scripts/jdtls.py) very useful. However, it would be nice if this script had the ability to specify java executable path on the command line using an option, thus eliminating the need to wrap it in another script that sets up JAVA_HOME.
=> Add --java-executable argument to jdtls.py wrapper

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- To fix the marker property value too long issue - jls#2424.
The issue happens when the gradle project has some errors and buildship failed to import it. When this happens, buildship will add a marker with the full stacktrace as a property of the marker. Unfortunately, Eclipse has a limitation of the max length of the property value. When the length exceeds the limitation, an exception is thrown and abort the import.
fix #2424
=> Update buildship version

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalDescriptionProvider.java
With the pre-release version of Java language support extension installed, triggering method completion on DEBUG CONSOLE will throw NPE exception as below.
```
Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "this.fCollapsedTypes" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "this.fCollapsedTypes" is null
at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalDescriptionProvider.createMethodProposalLabel(CompletionProposalDescriptionProvider.java:334)
at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalDescriptionProvider.updateDescription(CompletionProposalDescriptionProvider.java:745)
at com.microsoft.java.debug.plugin.internal.CompletionProposalRequestor.toCompletionIte …
```
=> Add null check for 'fCollapsedTypes' variable to avoid NPE when invoking completion in DEBUG CONSOLE

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpContext.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
Fixes #3052
Signature help now displays all overloaded methods, though may now display some extra inapplicable methods in select cases. This also fixes an issue where signature help is not displayed for overloaded methods with no parameters, as the completion now places the cursor within the round brackets.
=> Fix signature help for overloaded methods

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java
- Some code actions are broken within unnamed classes mainly due to the unexpected UnnamedClass node which doesn't subclass AbstractTypeDeclaration
- Avoid computing these code actions until they are fixed upstream
- See https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3087
=> Work around broken code actions due to Unnamed classes.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SaveActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
Addresses https://github.com/redhat-developer/vscode-java/issues/3408.
Only applicable for clients that support https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_applyEdit
=> Automatically rename file to type name on save

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServerApplication.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LogReader.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/LogHandler.java, org.eclipse.jdt.ls.tests.syntaxserver/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxServerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JVMConfiguratorTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/DiagnosticsCommandTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/NonProjectFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ShowAllQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerChainTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerLazyResolveTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PostfixCompletionTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectPreferenceChangeListenerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenClasspathTest.java
- Attach a platform log listener sooner (in bundle activation)
- Cache status messages that arrive before client connection set up
- Send cached / server log messages once client is connected
=> Read the server logs in order to discover early startup log messages.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
Used for https://github.com/microsoft/vscode-java-pack/pull/1283
=> Support updating whole classpath of the project

org.eclipse.jdt.ls.tests/pom.xml
Fixes this error:
```
[INFO] --- tycho-surefire:4.0.6:test (default-test) @ org.eclipse.jdt.ls.tests ---
[INFO] {osgi.os=macosx, [osgi.ws](http://osgi.ws/)=cocoa, org.eclipse.update.install.features=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true}
[ERROR] Cannot resolve project dependencies:
[ERROR]   You requested to install ‘org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group 0.0.0’ but it could not be found
[ERROR]
[ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
```
=> Fix tests failing to run on Mac

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
- See https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3116
=> Handle non-existent completion item insert text mode capability.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
When the path of the lib classpath entry points to a file which does not exist on file system, `.getLocation()` could return `null`.
=> Fix NPE when fetching the classpath of the project

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
@angelozerr , can you verify this change fixes things for you ? I also would need to adjust vscode-java as it appears to break it by sending a duplicate `workspace/willRenameFiles`, which causes some problems. Basically that client doesn't want the renames to be applied immediately, but rather get the edits and allow a user to apply/discard them.
- The server capabilities in the initialize response must contain a "willRename" object in the workspace's "fileOperations" object.
- Fixes #3126 
```diff
--- old.txt 2024-04-05 11:22:47.101634192 -0400
+++ new.txt 2024-04-05 11:31:28.769420565 -0400
@@ -1,4 +1,4 @@
-[Trace - 11:22:11] Received response 'initialize - (0)' in 5456ms.
+[Trace - 11:31:03] Received response 'initialize - (0)' in 6603ms.
Result: {
"capabilities": {
"textDocumentSync": …
```
=> Correctly declare support for "workspace/willRenameFiles".

org.eclipse.jdt.ls.product/languageServer.product, org.eclipse.jdt.ls.product/syntaxServer.product, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- Fixes https://github.com/redhat-developer/vscode-java/issues/3564
- https://github.com/eclipse-equinox/equinox/pull/564
I've updated the eclipse-jdt-core-incubator dev branch to 1 commit after I20240327-1800 (since that's what's needed to fix this). I couldn't move the I-build itself to a commit newer than I20240327-1800 without a lot of tests relating to the import of Maven projects failing to locate various types that should be on the classpath. @snjeza We'll need to address that in a separate commit.
=> Update target platform to newer 4.32-I-builds (I20240327-1800).

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
- A search term of 'foo.bar' where 'foo' is the qualifier should search for any qualifier matching '*foo*'
=> Qualifier of workspace symbol search should be wildcard search.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JVMConfiguratorTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/filesystem/GradleProjectMetadataFileTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/filesystem/MavenProjectMetadataFileTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ImportNewProjectsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenBuildSupportTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MultiRootTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
- Default project is configured with a (default) JRE, that will produce
unwanted symbols when other projects don't use the default JRE
- Place default project creation logic into the invisible project
importer since that is the importer requiring it
- Continue to support some special cases where default project should be
created (eg. Maven/Gradle project & opening a standalone file)
- Update testcases & add a testcase
- Fixes https://github.com/redhat-developer/vscode-java/issues/3452
@snjeza , let me know if the PR seems reasonable, or would break something.
The basic issue is when you have some Maven/Gradle project that sets a certain Java version, that is different from the default version (eg. `java.home` or from `java.configuration.runtimes` with `default` set to `true`), then you'll …
=> Create the default project only when it is necessary.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
This PR will likely fail until https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1386 is handled and we update to a TP that includes it. 
It is here for safe-keeping so we don't lose it or remain unsure of how to respond.
=> Make use of new getters in superclass to override javadoc formatting

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Required due to upstream change: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/ac81e89eca51bf80016e59e49fdc9fddbbead291 causing compilation failures
=> Update target platform to newer 4.32-I-builds (I20240507-0220)

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
When a client registers with `CodeActionClientCapabilities.dynamic` equal to `true`, the server will respond with:
```
capabilities: {
...
codeActionProvider: {
codeActionKinds: [...],
resolveProvider: true,
},
}
```
But if `CodeActionClientCapabilities.dynamic` is `false`, then the server responds with:
```
capabilities: {
...
codeActionProvider: {
resolveProvider: true,
},
}
```
The server will never provide `codeActionKinds` when `CodeActionClientCapabilities` is not dynamic. I believe this behavior is a mistake (correct me if I'm wrong), and with this pull request, the server will always respond with `codeActionKinds`.
=> codeActionKinds not sent when CodeActionClientCapabilities is not dynamic.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java
=> Only clean default project when building workspace if it exists.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/IProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3637
Steps to reproduce:
1. exit VS Code
2. [Clean the workspace directory]( https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)
3. clone the repository [quarkus-langchain4j](https://github.com/quarkiverse/quarkus-langchain4j)
4. cd quarkus-langchain4j
5. code .
6. wait for the build to finish
7. reload the VS Code window (it freezes without the PR; takes several seconds with the PR or VS Code 1.32.0)
[Test vsix](https://github.com/snjeza/vscode-test/raw/master/java-1.32.0.vsix)
=> Improve order of operations when importing multi-module Maven projects.

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
Introduce mechanism to address https://github.com/redhat-developer/vscode-java/issues/1263, https://github.com/redhat-developer/vscode-java/issues/2989, https://github.com/redhat-developer/vscode-java/issues/3213.
Then the project setting page can leverage it and expose the project setting, sth like:
=> Support get and update active profiles of the Maven projects

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
- All the options from JavaCore are supported via the delegate command 'java.project.updateSettings'.
=> Support update Java project options.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ClasspathUpdateHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Fixes #3155 
It now re-validates all open files in a project when the project's classpath is updated. This only happens when autobuild is turned off (I assume that when autobuild is on, projects are automatically rebuilt when the classpath changes and files are re-validated in the process).
I implemented this through `ClasspathUpdateHandler` and `DiagnosticsHandler` which is probably not a good idea (e.g. does this code belong in `ClasspathUpdateHandler`? should we re-validate files through `DocumentLifeCycleHandler` to take advantage of debouncing?). Let me know if I should do anything differently.
=> Revalidate open files in project when classpath updates.

org.eclipse.jdt.ls.product/scripts/jdtls.py
This pull request addresses some python errors that occur when trying to run the jdtls.bat file on a Windows machine.
I've tried running on my machine (Windows 10 Version 22H2, Python 3.7.3) after building from source (clone the github repo and run `mvn clean verify`) and was met with the following errors (replaced my system-specific path fragment with %USERPROFILE%):
```sh
Traceback (most recent call last):
File "%USERPROFILE%\eclipse.jdt.ls\org.eclipse.jdt.ls.product\target\repository\bin\/jdtls", line 17, in <module>
jdtls.main(sys.argv[1:])
File "%USERPROFILE%\eclipse.jdt.ls\org.eclipse.jdt.ls.product\target\repository\bin\jdtls.py", line 91, in main
java_executable = get_java_executable(known_args)
File "%USERPROFILE%\eclipse.jdt.ls\org.eclipse.jdt.ls.product\target\repository\bin\jdt …
```
=> fix(scripts): add windows checks for jdtls.py

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServerApplication.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseInitHandler.java
=> Apply autobuilding setting when initializing.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
- Fixes #3183 
- Allow folder renames to trigger workspace/willRenameFiles since the
language server can update source files during such an operation
```diff
--- old.txt	2024-06-12 15:50:40.782112655 -0400
+++ new.txt	2024-06-12 15:53:20.175658497 -0400
@@ -8,6 +8,13 @@
"matches": "file"
},
"scheme": "file"
+                },
+                {
+                    "pattern": {
+                        "glob": "**",
+                        "matches": "folder"
+                    },
+                    "scheme": "file"
}
]
}
```
=> Expand "workspace/willRenameFiles" support to include folders.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/GetRefactorEditHandlerTest.java
Applies when the  `java.codeGeneration.addFinalForNewDeclaration` setting is set to `all` or `variables`. Also applicable for the 'replace all occurrences' extract proposal.
Closes https://github.com/redhat-developer/vscode-java/issues/3308
=> Add 'final' to 'Extract to local variable' result if requested

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/ChainCompletionProposalComputer.java
This will provide completions from either of the completions processing threads that finish first. Most of the time it will be the main chain completion thread. By doing this we try to minimize the chance we will not get any chain completions when there supposed to be.
=> Improve chain completion by waiting for either main or context chains.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
Fixes #3180 
I'm not entirely clear on why history size is tied to processor count. Is it because a client with more processors tends to issue more `textDocument/codeAction` requests? Either way, setting a minimum history size shouldn't cause any problems. Selecting an item from the source action menu tends to issue 2-4 requests, so I chose 8 as a safe minimum size.
=> Give ResponseStore for codeactions a minimum history size of 8

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
=> Enable call hierarchy implementors

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/TypeMismatchSubProcessor.java, org.eclipse.jdt.ls.product/languageServer.product, org.eclipse.jdt.ls.product/syntaxServer.product, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/projects/maven/semantic-tokens/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
- Adjust deprecation test due to eclipse-jdt/eclipse.jdt.core#2679
- Ensure Java 17 compliance is used for projects with sealed classes
- core.net fragments merged into host eclipse-platform/eclipse.platform#1440
=> Update target platform to newer 4.33-I-builds (I20240716-1800).

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/codemanipulation/OverrideMethodsTestCase.java
Using `createCompilationUnit` then `createType` results in duplicated content in the file. This introduces some extra unrelated problems in the file, with both ECJ and Javac, that are not in the scope of this test.
Supporting this extra duplication story is more extra work for the test to pass with Javac. So we fix the test to make it work out of the box with Javac too.
=> Fix duplicated content in test class

org.eclipse.jdt.ls.tests/projects/eclipse/java16/src/main/java/foo/bar/Bar.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
This allows Javac-based JDT to go further and test the actual expected behavior without being interrupted because of missing package declaration.
=> Fix package declaration in test file

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
- Fixes redhat-developer/vscode-java#2150
- Add testcase
=> Add java.diagnostic.filter to exclude files from diagnostic publishing.

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/projects/eclipse/eclipsemaven/pom.xml, org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle1/build.gradle, org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle2/build.gradle, org.eclipse.jdt.ls.tests/projects/gradle/simple-gradle/build.gradle, org.eclipse.jdt.ls.tests/projects/maven/buildhelped/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/salut/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/salut2/pom.xml, org.eclipse.jdt.ls.tests/projects/mixed/simple-gradle/build.gradle, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/JavadocQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/StringConcatenationQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/TypeMismatchQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractGradleBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractMavenBasedTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupportTest.java
- Tests requiring a compiler compliance of Java 1.7 or below cannot be supported
=> Update target platform to newer 4.33-I-builds (I20240728-1800).

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java
Fixes imports with Java 22 and Gradle 8.8, analogous to #3044.
=> Add Gradle 8.8 to compatibility check

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/framework/protobuf/ProtobufSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseInitHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FileEventHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
Fixes #3222 
Requires https://github.com/redhat-developer/vscode-java/pull/3731
=> Recognize custom file extensions

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java, org.eclipse.jdt.ls.tests/projects/gradle/kradle/build.gradle.kts, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtilsTest.java
The related issue - https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/609
=> Fix Gradle tests started with Java 23

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java
Fixes issues pasting text with implicitly declared classes into the file explorer.
=> Fix failed cast to TypeDeclaration in file paste event

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/EventType.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BuildWorkspaceHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
=> Inform clients when Preview support enabled for an incompatible version.

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractSelectionTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractFieldTest.java
- Code actions belonging to diagnostics need to be resolved by setting the invocation range for the particular diagnostic in the evalutation request
=> Fix AbstractQuickFixTest's evaluateCodeActions(..) logic.

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/TypeMismatchQuickFixTest.java
Small improvement due to https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1559 .
=> Update target platform to newer 4.33-I-builds (I20240820-1800).

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java
Related to https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/609
=> Fix ConnectionStreamFactory with javac

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java
When using Javac, the BodyForAbstractMethod problem is well reported. Other problems can be missing.
However, BodyForAbstractMethod seems like a good enough case per so to enable the "remove abstract" quick fix.
This fixes AbstractMethodQuickFixTest.testAbstractMethodInConcreteClass when running with Javac.
=> Allow "remove abstract" quickfix for BodyForAbstractMethod

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionResolveHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/extended/SnippetTextEdit.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionResolveHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3686
https://github.com/redhat-developer/vscode-java/pull/3730
=> Add LinkedProposalModel -> snippet conversion to support linked proposals

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/TypeMismatchSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/TypeMismatchQuickFixTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3040
=> Introduce new type mismatch quickfix for constructor invocations

.github/workflows/licensecheck.yml
Currently, the [licensecheck workflow](https://github.com/eclipse-jdtls/eclipse.jdt.ls/actions/workflows/licensecheck.yml) is failing every time someone makes a push or even comments on an issue (I got an automated email from GitHub about it after posting a comment). It seems like this is caused by the Eclipse Dash License Tool repository being moved to a new organization, see eclipse-dash/dash-licenses#302 and in particular the last couple of comments on that issue. Basically, the GitHub workflow doesn't follow the redirect, so the workflow has to be updated to use the new repository in order for it to work again.
=> Fix license check workflow after repository move

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
The current code being tested has syntax errors. Those errors prevents Javac from properly setting up bindings (and it's not obvious that Javac is more wrong than ECJ, so there are little chance Javac gets changed to behave like ECJ).
Those syntax errors do not seem so relevant for the case being covered. So we get rid of them to focus on the "correct" case and allow Javac to work with it.
=> Improve rename tests so they can work with Javac too

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java, org.eclipse.jdt.ls.tests/projects/gradle/gradle-build-server/.project, org.eclipse.jdt.ls.tests/projects/gradle/gradle-build-server/build.gradle, org.eclipse.jdt.ls.tests/projects/gradle/gradle-build-server/gradle/wrapper/gradle-wrapper.properties, org.eclipse.jdt.ls.tests/projects/gradle/gradle-build-server/gradlew, org.eclipse.jdt.ls.tests/projects/gradle/gradle-build-server/gradlew.bat, org.eclipse.jdt.ls.tests/projects/gradle/gradle-build-server/src/main/java/Library.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
There will be the case when user has imported the gradle project by build server. Then, the user disable/uninstall the gradle extension.
In this case, the build server project should not be excluded when gradle importer scans the folder to import.
But, so far I cannot figure out a perfect way to do that. The nature id for build server is hard coded. @snjeza @rgrunber Do you know if we can have better approach than this?
=> Import Gradle project via Buildship if Gradle Build Server is not available

README.md
Updates the supported Java versions in accordance with #3227 and #3111.
***NOTE*** that this PR is meant as a testing environment for automated license checking, see https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3264#issuecomment-2329183621. However, the PR may still be merged afterwards as I believe the README information should be updated either way.
=> Update supported Java versions in README

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/javafx/JavaFXTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractProjectsManagerBasedTest.java
=> CompletionHandlerTest.testCompletion_Lambda fails randomly

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/AddDeprecatedAnnotationCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/AddOverrideAnnotationCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/ISimpleCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/InstanceofPatternMatch.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/InvertEqualsCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/LambdaExpressionAndMethodRefCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/LambdaExpressionCleanup.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/MemberAccessUsesThisCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/OrganizeImportsCleanup.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/StaticAccessUsesClassNameCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/StringConcatToTextBlockCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/SwitchExpressionCleanup.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/TryWithResourceCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/VariableDeclarationFixCleanup.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/ReorgCorrectionsSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
- 'organizeImports' becomes recognized through the cleanup registry
- Also migrate away from deprecated ICleanUpFixCore & CleanUpContextCore.
=> Add Organize Imports as a clean up.

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Fixing https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3279 .
=> Add missing 'Test' annotation on testJava23Project.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
- Delegate to markdown content access when javadoc node starts with '///'
- Add basic testcase
A continuation of https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3278 .
Note : Links currently don't work. I did try to define a `private static class JdtLsMarkdownAccessImpl extends CoreMarkdownAccessImpl` that copies over the link creation from https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/12b4cbce0a33f9fa3e81e574fc7fe34873bc84f0/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java#L308-L322 . It doesn't seem to work because markdown links seem to be converted to the form `<code><a href="[url]">[label]</a></code>` and Remark doesn't seem to like preserving links within `<code>` blocks.
=> Add Markdown support (JEP 467) for Java 23.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
Fixes #3290 
Without the PR, the `WorkspaceDiagnosticsHandlerTest.testDiagnosticFiltering()` test fails on Windows.
The fix has been based on https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3290#issue-2552110655
@Kamii0909 Thanks!
=> java.diagnostic.filter is broken on Windows

org.eclipse.jdt.ls.product/publish-assembly.xml
- 444 for jar files, 644 for config files and 755 for scripts
- Fixes #3293
=> Set appropriate file permissions within the JDT-LS tarball.

.github/workflows/codeql-analysis.yml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SuppressWarningsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/TelemetryManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.product/languageServer.product, org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, org.eclipse.jdt.ls.tests/.classpath, org.eclipse.jdt.ls.tests/.settings/org.eclipse.jdt.core.prefs, org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.tests/pom.xml, org.eclipse.jdt.ls.tests/projects/maven/mavenlombok/pom.xml, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java, pom.xml
The idea is to run 
> mvn clean verify -Pjavac
But for some reason I run into:
> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8:validate-classpath (default-validate-classpath) on project org.eclipse.jdt.ls.tests: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8:validate-classpath failed: org.osgi.framework.BundleException: Bundle org.eclipse.jdt.ls.tests cannot be resolved:org.eclipse.jdt.ls.tests [293]
[ERROR]   Unresolved requirement: Require-Bundle: org.eclipse.jdt.core.javac
@akurtakov @mickaelistria what am I missing?
=> Support using 'javac' as internal compiler.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
Fixes 
- https://github.com/redhat-developer/vscode-java/issues/3797 
- https://github.com/redhat-developer/vscode-java/issues/3793
- https://github.com/redhat-developer/vscode-java/issues/3715
-
=> Intermittent Class Loading Issues with Java Core Packages

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target, pom.xml
- Where 'javac' compiler not specified (defaulting to ECJ), the version specified by Tycho should be used
- Use 4.34-I-builds "latest" repo to keep up to date with the jdt-core-incubator Jenkins generated repo
=> Remove unnecessary ECJ compiler override.

org.eclipse.jdt.ls.repository/category.xml
Should make https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3001 possible.
This is more of a convenience for those wishing to reproduce the builds.
I've added some bundles that, while not required to compile the JDT-LS bundles, are used in the language server product. As a result, they need to be in the generated repository, or other consumes would not be able to build the products module.
=> Fix o.e.jdt.ls.repository so that it may be reused to build JDT-LS.

org.eclipse.jdt.ls.core/plugin.xml
=> Remove unused extension point

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
=> Improve JDTUtils.resolveCompilationUnit

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/RenameUnusedLocalVariableCleanup.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
- Based on https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1701
=> Add code action for unused pattern variable / unused lambda parameter.

org.eclipse.jdt.ls.tests/.classpath, org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF, org.eclipse.jdt.ls.tests/pom.xml, pom.xml
- Remove dependency from o.e.jdt.ls.tests to org.eclipse.jdt.core.javac
- Use extraRequirements in the target platform configuration to ensure org.eclipse.jdt.core.javac ends up in the test target platform
- Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3326
@mickaelistria , let me know if this makes sense. It seems to be working.
=> Restore JavaSE-17 as the BREE for org.eclipse.jdt.ls.tests.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/RenameUnusedLocalVariableCleanup.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
- The clean up now supports additional cases from upstream.
- Continuing from https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3319
- See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1762
=> Rename 'removeUnusedLambdaParameters' to 'renameUnusedLocalVariables'.

org.eclipse.jdt.ls.tests/.settings/org.eclipse.jdt.core.prefs
- Project resolution fails to resolve the '23' references now that we have set the tests back to '17'
- Continuation of https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3327 .
=> Update JDT core preferences for the o.e.jdt.ls.tests bundle.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
- For JEP 467, JDT parses the markdown comments into the AST Model as a Javadoc node (TagElement & TextElement and Name/MemberRef/MethodRef for links), converting to HTML. JDT-LS converts the HTML back to Markdown using Remark.
- This bypasses the AST model -> HTML conversion by attempting to render the Javadoc comments directly as Markdown, in part because the content is already (mostly) Markdown
**Before**
**After**
Things left to address :
=> Bypass AST model -> HTML Conversion for Markdown Comments

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Ext.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/ITest.java, org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/java/Test.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3813
Requires https://github.com/redhat-developer/vscode-java/pull/3876
Before:
After:
=> Add support for interface and abstract method implementation code lens

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java
- When a sealed class is the target of an empty switch expression, add all the types it permits as case statements
- Based on https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1817 .
@jjohnstn I noticed you did a loooot of good refactoring in the local corrections subprocessor. However I want to properly implement that later, because it's a bit of a manual process. I basically need to go to every copied implementation in the JDT-LS local subprocessor, confirm the base processor in jdt.core.manipulation does things identically (ie. JDT-LS hasn't added any hacks for odd reasons), and if so, delegate to it and reduce duplication. Is it ok if I leave some of those abstract methods unimplemented for now ? We don't currently call them in JDT-LS and it appears they're only called from JDT UI's …
=> Add quick fix for sealed class within empty switch expression.

CHANGELOG.md
- There's just one more PR I'm hoping to merge ( https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3345 ).
=> Changelog for 1.43.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionResolveHandlerTest.java
- A linked correction proposal group may refer to positions whose offset cannot be resolved
- Add testcase
- Fixes redhat-developer/vscode-java#3905
@hopehadfield , if you're interested, it'd be good to know if you agree that this would have always been an issue (I did notice the exact same quick-fix has the exact same problem in Eclipse). I could have sworn there was a case where we discussed how to translate to relative offsets within the edit, but can't really see where we do that. Maybe when we considered splitting up the edits so it wasn't just one giant thing ?
Either way, the issue here is that we want to sync up 2 or more positions inside the actual edit, but we can't because the edit hasn't been applied so there wouldn't be an offset in the sources.
=> Guard against snippet position groups with undefined (-1) offsets.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/ParameterGuesser.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/GenerateToStringHandlerTest.java
- JavaModelUtil.is50OrHigher has also been removed
- Assume such expressions are always true as a lower compliance is no longer supported
=> React to removal of 'is60orHigher' from JDT.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeLensHandlerTest.java
**Before**
**After**
- A base type/method that that is not an interface/abstract (or a member of an interface/abstract class) may still be inherited and that information should be indicated in the implementation code lens
- Add testcase
CC'ing @fbricon & @snjeza .
From https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/301#issuecomment-314597718 , it almost seems like you were aware of this and fine with it. I mean sure, clients might have "Go To Implementations" / "Find All Implementations" which will get you those 6 locations, but might be confusing for users to see implementations work via. code lens for interfaces, and abstract classes but not regular classes. Was there some performance consideration ?
=> Implementation code lens for non interface/abstract base types/methods.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradlePreferenceChangeListener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupportTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3893
=> There is no way to refresh classpath after adding a library

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/ChainCompletionProposalComputer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
- Assume such expressions are always true as a lower compliance is no longer supported
=> React to removal of 'is1d8OrHigher' from JDT.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SuppressWarningsSubProcessor.java
- See https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1942/
- Implement alreadyHasProposal to avoid duplicates
I don't think we are seeing these duplicate entries, so it's worth me having a quick look to see why that is.
**Update:**
It's because of https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/78d72ee9b4e5007248f156efa934cc78173ddc7f/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java#L192-L194
https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/78d72ee9b4e5007248f156efa934cc78173ddc7f/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java#L406-L425
We remove duplicates on our end also
=> Avoid duplicate suppress warning suggestions through new API method.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewCUProposal.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
Note that most of these diagnostics already existed, although there are some cases where the diagnostics might be new as well. What's new is the quick fixes for those diagnostics. Some of these new quick fixes do require a compiler setting to be set to warning/error in order for the problem reporting to diagnose them as they're ignored by default. Most are diagnosed by default though.
- UnqualifiedFieldAccess -> addUnqualifiedFieldAccessProposal
- org.eclipse.jdt.core.compiler.problem.unqualifiedFieldAccess=error 
https://github.com/user-attachments/assets/b2f1ed58-06c4-4c23-ba81-4d350ad9546a
- UnnecessaryInstanceof -> addUnnecessaryInstanceofProposal
- org.eclipse.jdt.core.compiler.problem.unnecessaryTypeCheck=error 
https://github.com/user-attachments/assets/58ba4566-4e74-4fd5-b730-8bca2 …
=> Reuse quick fixes from LocalCorrectionsBaseSubProcessor.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/LocalCorrectionsSubProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
- UninitializedLocalVariable, UninitializedLocalVariableHintMissingDefault -> addUninitializedLocalVariableProposal
https://github.com/user-attachments/assets/939b28da-f453-459a-ae1e-e20e409d2b5a
- UnusedTypeParameter -> addUnusedTypeParameterProposal
- org.eclipse.jdt.core.compiler.problem.unusedTypeParameter
https://github.com/user-attachments/assets/e1079744-1e28-4158-b73e-d808bc52ec5f
- DuplicateInheritedDefaultMethods, InheritedDefaultMethodConflictsWithOtherInherited -> addOverrideDefaultMethodProposal
https://github.com/user-attachments/assets/9b4f6d77-d86b-489e-be37-6f818827b8ca
=> Add some more quick fixes from LocalCorrectionsBaseSubProcessor.

org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AnonymousClassCreationToLambdaTest.java
It looks like https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1999 fixed things so that parts of the anonymous class that remain (ie. the last curly brace) do not lose their comments. It's a bit odd in our particular test case, but comment preservation is probably for the best.
=> React to upstream changes preserving comments in lambda conversions.

org.eclipse.jdt.ls.product/scripts/jdtls.py
Was setting up jdtls on my machine (running Fedora 41) and it was failing to find the equinox launcher jar.
I looked in the plugins directory that the script was searching and the jar was named `org.eclipse.equinox.launcher.jar`.
I updated this script to use that jar and it started working for me.
=> Adjust Equinox launcher detection for mason-registry packaging.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/ReturnTypeSubProcessor.java
- UsingDeprecatedMethod
- org.eclipse.jdt.core.compiler.problem.deprecation 
https://github.com/user-attachments/assets/503b5f1a-6e4a-446e-ae66-dc2e52e328c1
- VarIsNotAllowedHere
https://github.com/user-attachments/assets/4f6f5e3e-6dcc-42be-b67e-66117981e606
- MethodButWithConstructorName
- org.eclipse.jdt.core.compiler.problem.methodWithConstructorName 
https://github.com/user-attachments/assets/f06ffefc-4ce4-4acf-b525-1beef15ccff7
- SwitchExpressionsReturnWithinSwitchExpression
https://github.com/user-attachments/assets/a8139f4d-6a38-4a86-8734-b775a91621d1
- Use the ReturnTypeBaseSubProcessor to reduce duplicated code
=> Detect more problems and support their quick fixes.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
- Fixes https://github.com/redhat-developer/vscode-java/issues/3963
- If 2 or more public type delcarations exist at the top level within a source file, renaming becomes ambiguous, so it should be avoided
(Improves upon https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3091)
=> Only rename source file to match the single public type declaration.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java
- Improving on https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3378 .
=> Fix inherited document symbols to collect interfaces as well.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ExternalFileChange.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/CorrectionMessages.properties, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxProjectsManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ResourceUtilsTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
Generate code action to ignore certain compiler issues.
- Fixes redhat-developer/vscode-java#1791
- Some JDT core compiler problems can be ignored using JDT compiler
settings so offer a code action, "Ignore compiler problem(s)" to do
this for a given error/warning
- This respects (writes to) `java.settings.url` (if present) on the
local filesystem and otherwise writes to the project metadata location
- Add testcase
=> Generate code action to ignore certain compiler issues.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ResourceUtils.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ResourceUtilsTest.java
- Continuation of https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/1765
=> Fix RelativePattern by ensuring base URI contains the scheme.

README.md, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
- Fixes #3108 
- For didChangeConfiguration, incoming preferences should not be assumed to contain a value for every setting
- Create method PreferenceManager.update(Map) that merges some subset of all preferences into the existing configuration
- Add testcase
- Also bump listing of supported project JDKs to include 23
- Set default value for search scope setting
=> Preference manager should merge new preferences instead of overwriting.

.mvn/jvm.config, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattenerTest.java
- Continuing from https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3412
- Add test case
- Also revise JAXP limits based on pre JDK 24 values.
=> Flatten incoming preference map so as to perform merging correctly.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattener.java
- Map flattening logic needs to be able to handle null values
=> Use AbstractMap.SimpleEntry instead of Map.entry to permit null values.

CHANGELOG.md, README.md
Note that https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/1765 really did include the fix to react to changed watched files outside the workspace. Figured I'd include it here (hence why 1765 is referenced twice).
=> Changelog for 1.46.0

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/MapFlattenerTest.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Fixes https://github.com/redhat-developer/vscode-java/issues/3993
Reverts https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3406 , https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3412 , https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3416 , https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3417
Reverts the following :
- "Preference manager should merge new preferences instead of overwriting."
- "Use AbstractMap.SimpleEntry instead of Map.entry to permit null values."
- "Flatten incoming preference map so as to perform merging correctly."
- "Preserve initialization options stored inside Preferences."
=> Revert modifications to preference manager.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewCUProposal.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java
- When a non-existent type is permitted by a sealed class, the newly
created type should implement the necessary methods
- Related #1553
.. turns out it's possible after all. Still need to clean it up a bit though.
=> Implement methods in newly created type from an inherited sealed class.

org.eclipse.jdt.ls.core/pom.xml
- groovy-maven-plugin no longer actively maintained
- Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3434
New Maven dependencies all have a license score >= 60
- https://clearlydefined.io/definitions/maven/mavencentral/org.codehaus.gmavenplus/gmavenplus-plugin/4.2.0
- https://clearlydefined.io/definitions/maven/mavencentral/org.apache.groovy/groovy/4.0.26
- https://clearlydefined.io/definitions/maven/mavencentral/org.apache.groovy/groovy-json/4.0.26
=> Migrate from groovy-maven-plugin to gmavenplus-plugin.

org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
- Retrieve the logback bundles from Eclipse release repository
- Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3469
=> Ensure we use the same versions of logback-{classic,core}.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FoldingRangeHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java
This PR addresses this issue, https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2940
Includes minor refactoring of createScanner method and utilization of the CompilationUnit when for creating the same.
=> refactor: use utility method to share usage of JDT token scanner

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/RedundantComparisonStatementCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/RedundantFallingThroughBlockEndCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/RedundantIfConditionCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/RedundantModifiersCleanUp.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/RedundantSuperCallCleanUp.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
- redundantComparisonStatement, redundantFallingThroughBlockEnd, redundantIfCondition, redundantModifiers, redundantSuperCall
- Addresses https://github.com/redhat-developer/vscode-java/issues/4066
- Requires https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2262
=> Add cleanups for various redundant modifiers/expressions/statements.

org.eclipse.jdt.ls.product/publish-assembly.xml
- Assist downstream clients in managing the installation and align with other installations
- Fixes https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3482
=> Set permissions for bundles to 644 (writeable for owner).

org.eclipse.jdt.ls.core/pom.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseInitHandler.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
The InitHandler will fill the serverInfo with the dynamic Maven version property that is generated by the git-commit-id-maven-plugin.
Fixes #3484
When executing  `:LspInfo` in Neovim I can verify that the provided change works end to end.
```
vim.lsp: Active Clients ~
- jdtls (id: 1)
- Version: 1.50.0-SNAPSHOT
- Root directory: ~/Projekte/Open-Source/sonarlint-language-server
- Command: { "jdtls", "--java-executable", "/usr/lib/jvm/java-21-openjdk/bin/java", "-configuration", "/home/marc/.cache/jdtls/configuration", "-data", "~l/.cache/jdtls/sonarlint-language-server-a2f90f" }
- Settings: {
java = {
configuration = {
runtimes = { {
name = "JavaSE-24",
path = "/usr/lib/jvm/java-24-openjdk"
}, {
name = "JavaSE-21",
path = "/usr/lib/jvm/java-21-openjdk"
}, {
name = "JavaSE-17",
path = …
```
=> Provide server info in response to initialize call.

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
I believe the configuration properties `java.errors.incompleteClasspath.severity` and `java.completion.engine` are not used, so they can be removed.
=> Remove unused options for completion & incomplete classpath severity.

org.eclipse.jdt.ls.core/pom.xml
The wrapper checksum is now inlined in the `versions/all` endpoint.
This means the requests per version can be avoided.
See https://github.com/gradle/gradle/issues/26793
=> Use wrapper checksums from versions/all for checksums.json

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
Fixes #3531 
When applying this PR, the Preferences.updateAnnotationNullAnalysisOptions(boolean) method is about 50% faster when you enable Null Analysis in the [spring-boot](https://github.com/spring-projects/spring-boot) project.
The PR also defers calling Preferences.updateAnnotationNullAnalysisOptions() after the project is built.
cc @rgrunber
=> Improve Null Analysis

org.eclipse.jdt.ls.core/plugin.xml, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/DiagnosticInfoCommand.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/TroubleshootingInfoCommand.java
This PR adds a command to get diagnostic info from the language server. 
This is a "companion"-PR to https://github.com/redhat-developer/vscode-java/pull/4153
=> Add "getTroubleshootingInfo" command

org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintVisitor.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintsPreferenceChangeListener.java, org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java, org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintHandlerTest.java
Return inlay hints for implicit lambda parameter types. Controlled by the "java.inlayHints.parameterTypes.enabled" preference.
=> feat: add inlay hints for lambda parameter types
